-- Spring Quest Indexes:

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_INDICIES[SPRING] = {};
QG_SPRING_INDEX = _G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_INDICIES[SPRING];

-- Quests to add:
-- Family Feast
-- Flower Envy
-- Promoting Pie
-- Springtime's Colours
-- Stretched Too Thin
-- The Gift of Spring
-- The Musicians' Misfortune
-- Well-watered Blooms

local i = 1;
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "A_TASTE_OF_SPRING_PICKUP");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "DAFFODIL_DAYS_DAILY_PICKUP");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "THE_GIFT_OF_SPRING_PICKUP");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "PROMOTING_PIE_PICKUP");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "PROMOTING_PIE_FLIER_1");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "THE_MUSICIANS_MISFORTUNE_PICKUP");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "SPRINGTIMES_COLOURS_PICKUP");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "THE_MUSICIANS_MISFORTUNE_FIDDLE");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "PROMOTING_PIE_FLIER_2");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "SPRINGTIMES_COLOURS_BANNERS_PICKED_UP");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "FLOWER_ENVY_PICKUP");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "FLOWER_ENVY_TALK_1");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "THE_GIFT_OF_SPRING_DAFFODILS_PICKED");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "FAMILY_FEAST_PICKUP");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "THE_MUSICIANS_MISFORTUNE_BODHRAN");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "STRETCHED_TOO_THIN_PICKUP");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "FAMILY_FEAST_LAMB");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "STRETCHED_TOO_THIN_LAMB");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "PROMOTING_PIE_FLIER_3");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "STRETCHED_TOO_THIN_PACKAGE_1");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "WELL_WATERED_BLOOMS_PICKUP");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "PROMOTING_PIE_FLIER_4");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "WELL_WATERED_BLOOMS_WATER_FOUND");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "WELL_WATERED_BLOOMS_WATER_1");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "WELL_WATERED_BLOOMS_WATER_2");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "WELL_WATERED_BLOOMS_WATER_3");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "SPRINGTIMES_COLOURS_BANNERS_PLACED");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "WELL_WATERED_BLOOMS_WATER_4");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "THE_MUSICIANS_MISFORTUNE_BAGPIPES");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "STRETCHED_TOO_THIN_PACKAGE_2");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "PROMOTING_PIE_FLIER_5");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "STRETCHED_TOO_THIN_PACKAGE_3");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "THE_MUSICIANS_MISFORTUNE_FLUTE");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "WELL_WATERED_BLOOMS_WATER_5");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "FLOWER_ENVY_TALK_2");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "STRETCHED_TOO_THIN_PACKAGE_4");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "FAMILY_FEAST_CARROTS");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "FAMILY_FEAST_POTATOES");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "THE_GIFT_OF_SPRING_DAFFODILS_PLANTED");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "THE_MUSICIANS_MISFORTUNE_LUTE");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "THE_MUSICIANS_MISFORTUNE_END");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "FAMILY_FEAST_LEEKS_TALK");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "FAMILY_FEAST_LEEKS");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "SPRINGTIMES_COLOURS_END");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "STRETCHED_TOO_THIN_PACKAGE_5");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "FLOWER_ENVY_TALK_3");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "WELL_WATERED_BLOOMS_END");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "FLOWER_ENVY_TALK_4");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "STRETCHED_TOO_THIN_PACKAGE_6");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "FLOWER_ENVY_BULB_COLLECTED");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "FLOWER_ENVY_END");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "FAMILY_FEAST_END");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "STRETCHED_TOO_THIN_END");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "PROMOTING_PIE_END");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "THE_GIFT_OF_SPRING_END");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "DAFFODIL_DAYS_DAILY_END");
i = AddNextQuickguideValue(QG_SPRING_INDEX, i, "A_TASTE_OF_SPRING_END");

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CHAINS[SPRING] = {
    ["A_TASTE_OF_SPRING"] = {
        [QG_SPRING_INDEX.A_TASTE_OF_SPRING_PICKUP] = true;
        [QG_SPRING_INDEX.A_TASTE_OF_SPRING_END] = true;
    };
    ["DAFFODIL_DAYS_DAILY"] = {
        [QG_SPRING_INDEX.DAFFODIL_DAYS_DAILY_PICKUP] = true;
        [QG_SPRING_INDEX.DAFFODIL_DAYS_DAILY_END] = true;
    };
    ["THE_GIFT_OF_SPRING"] = {
        [QG_SPRING_INDEX.THE_GIFT_OF_SPRING_PICKUP] = true;
        [QG_SPRING_INDEX.THE_GIFT_OF_SPRING_DAFFODILS_PICKED] = true;
        [QG_SPRING_INDEX.THE_GIFT_OF_SPRING_DAFFODILS_PLANTED] = true;
        [QG_SPRING_INDEX.THE_GIFT_OF_SPRING_END] = true;
    };
    ["PROMOTING_PIE"] = {
        [QG_SPRING_INDEX.PROMOTING_PIE_PICKUP] = true;
        [QG_SPRING_INDEX.PROMOTING_PIE_FLIER_1] = true;
        [QG_SPRING_INDEX.PROMOTING_PIE_FLIER_2] = true;
        [QG_SPRING_INDEX.PROMOTING_PIE_FLIER_3] = true;
        [QG_SPRING_INDEX.PROMOTING_PIE_FLIER_4] = true;
        [QG_SPRING_INDEX.PROMOTING_PIE_FLIER_5] = true;
        [QG_SPRING_INDEX.PROMOTING_PIE_END] = true;
    };
    ["FLOWER_ENVY"] = {
        [QG_SPRING_INDEX.FLOWER_ENVY_PICKUP] = true;
        [QG_SPRING_INDEX.FLOWER_ENVY_TALK_1] = true;
        [QG_SPRING_INDEX.FLOWER_ENVY_TALK_2] = true;
        [QG_SPRING_INDEX.FLOWER_ENVY_TALK_3] = true;
        [QG_SPRING_INDEX.FLOWER_ENVY_TALK_4] = true;
        [QG_SPRING_INDEX.FLOWER_ENVY_BULB_COLLECTED] = true;
        [QG_SPRING_INDEX.FLOWER_ENVY_END] = true;
    };
    ["THE_MUSICIANS_MISFORTUNE"] = {
        [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_PICKUP] = true;
        [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_FIDDLE] = true;
        [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_BAGPIPES] = true;
        [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_FLUTE] = true;
        [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_LUTE] = true;
        [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_BODHRAN] = true;
        [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_END] = true;
    };
    ["SPRINGTIMES_COLOURS"] = {
        [QG_SPRING_INDEX.SPRINGTIMES_COLOURS_PICKUP] = true;
        [QG_SPRING_INDEX.SPRINGTIMES_COLOURS_BANNERS_PICKED_UP] = true;
        [QG_SPRING_INDEX.SPRINGTIMES_COLOURS_BANNERS_PLACED] = true;
        [QG_SPRING_INDEX.SPRINGTIMES_COLOURS_END] = true;
    };
    ["STRETCHED_TOO_THIN"] = {
        [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PICKUP] = true;
        [QG_SPRING_INDEX.STRETCHED_TOO_THIN_LAMB] = true;
        [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_1] = true;
        [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_2] = true;
        [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_3] = true;
        [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_4] = true;
        [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_5] = true;
        [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_6] = true;
        [QG_SPRING_INDEX.STRETCHED_TOO_THIN_END] = true;
    };
    ["WELL_WATERED_BLOOMS"] = {
        [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_PICKUP] = true;
        [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_FOUND] = true;
        [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_1] = true;
        [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_2] = true;
        [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_3] = true;
        [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_4] = true;
        [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_5] = true;
        [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_END] = true;
    };
    ["FAMILY_FEAST"] = {
        [QG_SPRING_INDEX.FAMILY_FEAST_PICKUP] = true;
        [QG_SPRING_INDEX.FAMILY_FEAST_LAMB] = true;
        [QG_SPRING_INDEX.FAMILY_FEAST_CARROTS] = true;
        [QG_SPRING_INDEX.FAMILY_FEAST_POTATOES] = true;
        [QG_SPRING_INDEX.FAMILY_FEAST_LEEKS_TALK] = true;
        [QG_SPRING_INDEX.FAMILY_FEAST_LEEKS] = true;
        [QG_SPRING_INDEX.FAMILY_FEAST_END] = true;
    };
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CHAIN_LOOKUP[SPRING] = {
    [QG_SPRING_INDEX.A_TASTE_OF_SPRING_PICKUP] = "A_TASTE_OF_SPRING";
    [QG_SPRING_INDEX.A_TASTE_OF_SPRING_END] = "A_TASTE_OF_SPRING";

    [QG_SPRING_INDEX.DAFFODIL_DAYS_DAILY_PICKUP] = "DAFFODIL_DAYS_DAILY";
    [QG_SPRING_INDEX.DAFFODIL_DAYS_DAILY_END] = "DAFFODIL_DAYS_DAILY";

    [QG_SPRING_INDEX.THE_GIFT_OF_SPRING_PICKUP] = "THE_GIFT_OF_SPRING";
    [QG_SPRING_INDEX.THE_GIFT_OF_SPRING_DAFFODILS_PICKED] = "THE_GIFT_OF_SPRING";
    [QG_SPRING_INDEX.THE_GIFT_OF_SPRING_DAFFODILS_PLANTED] = "THE_GIFT_OF_SPRING";
    [QG_SPRING_INDEX.THE_GIFT_OF_SPRING_END] = "THE_GIFT_OF_SPRING";

    [QG_SPRING_INDEX.PROMOTING_PIE_PICKUP] = "PROMOTING_PIE";
    [QG_SPRING_INDEX.PROMOTING_PIE_FLIER_1] = "PROMOTING_PIE";
    [QG_SPRING_INDEX.PROMOTING_PIE_FLIER_2] = "PROMOTING_PIE";
    [QG_SPRING_INDEX.PROMOTING_PIE_FLIER_3] = "PROMOTING_PIE";
    [QG_SPRING_INDEX.PROMOTING_PIE_FLIER_4] = "PROMOTING_PIE";
    [QG_SPRING_INDEX.PROMOTING_PIE_FLIER_5] = "PROMOTING_PIE";
    [QG_SPRING_INDEX.PROMOTING_PIE_END] = "PROMOTING_PIE";

    [QG_SPRING_INDEX.FLOWER_ENVY_PICKUP] = "FLOWER_ENVY";
    [QG_SPRING_INDEX.FLOWER_ENVY_TALK_1] = "FLOWER_ENVY";
    [QG_SPRING_INDEX.FLOWER_ENVY_TALK_2] = "FLOWER_ENVY";
    [QG_SPRING_INDEX.FLOWER_ENVY_TALK_3] = "FLOWER_ENVY";
    [QG_SPRING_INDEX.FLOWER_ENVY_TALK_4] = "FLOWER_ENVY";
    [QG_SPRING_INDEX.FLOWER_ENVY_BULB_COLLECTED] = "FLOWER_ENVY";
    [QG_SPRING_INDEX.FLOWER_ENVY_END] = "FLOWER_ENVY";

    [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_PICKUP] = "THE_MUSICIANS_MISFORTUNE";
    [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_FIDDLE] = "THE_MUSICIANS_MISFORTUNE";
    [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_BAGPIPES] = "THE_MUSICIANS_MISFORTUNE";
    [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_FLUTE] = "THE_MUSICIANS_MISFORTUNE";
    [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_LUTE] = "THE_MUSICIANS_MISFORTUNE";
    [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_BODHRAN] = "THE_MUSICIANS_MISFORTUNE";
    [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_END] = "THE_MUSICIANS_MISFORTUNE";

    [QG_SPRING_INDEX.SPRINGTIMES_COLOURS_PICKUP] = "SPRINGTIMES_COLOURS";
    [QG_SPRING_INDEX.SPRINGTIMES_COLOURS_BANNERS_PICKED_UP] = "SPRINGTIMES_COLOURS";
    [QG_SPRING_INDEX.SPRINGTIMES_COLOURS_BANNERS_PLACED] = "SPRINGTIMES_COLOURS";
    [QG_SPRING_INDEX.SPRINGTIMES_COLOURS_END] = "SPRINGTIMES_COLOURS";

    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PICKUP] = "STRETCHED_TOO_THIN";
    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_LAMB] = "STRETCHED_TOO_THIN";
    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_1] = "STRETCHED_TOO_THIN";
    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_2] = "STRETCHED_TOO_THIN";
    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_3] = "STRETCHED_TOO_THIN";
    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_4] = "STRETCHED_TOO_THIN";
    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_5] = "STRETCHED_TOO_THIN";
    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_6] = "STRETCHED_TOO_THIN";
    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_END] = "STRETCHED_TOO_THIN";

    [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_PICKUP] = "WELL_WATERED_BLOOMS";
    [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_FOUND] = "WELL_WATERED_BLOOMS";
    [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_1] = "WELL_WATERED_BLOOMS";
    [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_2] = "WELL_WATERED_BLOOMS";
    [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_3] = "WELL_WATERED_BLOOMS";
    [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_4] = "WELL_WATERED_BLOOMS";
    [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_5] = "WELL_WATERED_BLOOMS";
    [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_END] = "WELL_WATERED_BLOOMS";

    [QG_SPRING_INDEX.FAMILY_FEAST_PICKUP] = "FAMILY_FEAST";
    [QG_SPRING_INDEX.FAMILY_FEAST_LAMB] = "FAMILY_FEAST";
    [QG_SPRING_INDEX.FAMILY_FEAST_CARROTS] = "FAMILY_FEAST";
    [QG_SPRING_INDEX.FAMILY_FEAST_POTATOES] = "FAMILY_FEAST";
    [QG_SPRING_INDEX.FAMILY_FEAST_LEEKS_TALK] = "FAMILY_FEAST";
    [QG_SPRING_INDEX.FAMILY_FEAST_LEEKS] = "FAMILY_FEAST";
    [QG_SPRING_INDEX.FAMILY_FEAST_END] = "FAMILY_FEAST";
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE[SPRING] = {
    [QG_SPRING_INDEX.A_TASTE_OF_SPRING_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_TASTE_OF_SPRING";
    };

    [QG_SPRING_INDEX.A_TASTE_OF_SPRING_END] = {
        ["CHAIN_END"] = "A_TASTE_OF_SPRING";
    };

    [QG_SPRING_INDEX.DAFFODIL_DAYS_DAILY_PICKUP] = {
        ["CHAIN_BEGIN"] = "DAFFODIL_DAYS_DAILY";
        ["TIMER_START"] = true;
    };
    [QG_SPRING_INDEX.DAFFODIL_DAYS_DAILY_END] = {
        ["CHAIN_END"] = "DAFFODIL_DAYS_DAILY";
        ["TIMER_STOP"] = true;
    };
    [QG_SPRING_INDEX.THE_GIFT_OF_SPRING_PICKUP] = {
        ["CHAIN_BEGIN"] = "THE_GIFT_OF_SPRING";
    };
    [QG_SPRING_INDEX.THE_GIFT_OF_SPRING_DAFFODILS_PICKED] = {
        ["TOTAL"] = 8;
    };
    [QG_SPRING_INDEX.THE_GIFT_OF_SPRING_DAFFODILS_PLANTED] = {
        ["TOTAL"] = 8;
    };
    [QG_SPRING_INDEX.THE_GIFT_OF_SPRING_END] = {
        ["CHAIN_END"] = "THE_GIFT_OF_SPRING";
    };
    [QG_SPRING_INDEX.PROMOTING_PIE_PICKUP] = {
        ["CHAIN_BEGIN"] = "PROMOTING_PIE";
    };
    [QG_SPRING_INDEX.PROMOTING_PIE_FLIER_1] = {};
    [QG_SPRING_INDEX.PROMOTING_PIE_FLIER_2] = {};
    [QG_SPRING_INDEX.PROMOTING_PIE_FLIER_3] = {};
    [QG_SPRING_INDEX.PROMOTING_PIE_FLIER_4] = {};
    [QG_SPRING_INDEX.PROMOTING_PIE_FLIER_5] = {};
    [QG_SPRING_INDEX.PROMOTING_PIE_END] = {
        ["CHAIN_END"] = "PROMOTING_PIE";
    };
    [QG_SPRING_INDEX.FLOWER_ENVY_PICKUP] = {
        ["CHAIN_BEGIN"] = "FLOWER_ENVY";
    };
    [QG_SPRING_INDEX.FLOWER_ENVY_TALK_1] = {};
    [QG_SPRING_INDEX.FLOWER_ENVY_TALK_2] = {};
    [QG_SPRING_INDEX.FLOWER_ENVY_TALK_3] = {};
    [QG_SPRING_INDEX.FLOWER_ENVY_TALK_4] = {};
    [QG_SPRING_INDEX.FLOWER_ENVY_BULB_COLLECTED] = {};
    [QG_SPRING_INDEX.FLOWER_ENVY_END] = {
        ["CHAIN_END"] = "FLOWER_ENVY";
    };
    [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_PICKUP] = {
        ["CHAIN_BEGIN"] = "THE_MUSICIANS_MISFORTUNE";
    };
    [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_FIDDLE] = {};
    [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_BAGPIPES] = {};
    [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_FLUTE] = {};
    [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_LUTE] = {};
    [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_BODHRAN] = {};
    [QG_SPRING_INDEX.THE_MUSICIANS_MISFORTUNE_END] = {
        ["CHAIN_END"] = "THE_MUSICIANS_MISFORTUNE";
    };
    [QG_SPRING_INDEX.SPRINGTIMES_COLOURS_PICKUP] = {
        ["CHAIN_BEGIN"] = "SPRINGTIMES_COLOURS";
    };
    [QG_SPRING_INDEX.SPRINGTIMES_COLOURS_BANNERS_PICKED_UP] = {};
    [QG_SPRING_INDEX.SPRINGTIMES_COLOURS_BANNERS_PLACED] = {
        ["TOTAL"] = 6;
    };
    [QG_SPRING_INDEX.SPRINGTIMES_COLOURS_END] = {
        ["CHAIN_END"] = "SPRINGTIMES_COLOURS";
    };
    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PICKUP] = {
        ["CHAIN_BEGIN"] = "STRETCHED_TOO_THIN";
    };
    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_LAMB] = {};
    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_1] = {};
    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_2] = {};
    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_3] = {};
    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_4] = {};
    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_5] = {};
    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_PACKAGE_6] = {};
    [QG_SPRING_INDEX.STRETCHED_TOO_THIN_END] = {
        ["CHAIN_END"] = "STRETCHED_TOO_THIN";
    };
    [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_PICKUP] = {
        ["CHAIN_BEGIN"] = "WELL_WATERED_BLOOMS";
    };
    [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_FOUND] = {};
    [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_1] = {};
    [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_2] = {};
    [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_3] = {};
    [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_4] = {};
    [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_WATER_5] = {};
    [QG_SPRING_INDEX.WELL_WATERED_BLOOMS_END] = {
        ["CHAIN_END"] = "WELL_WATERED_BLOOMS";
    };
    [QG_SPRING_INDEX.FAMILY_FEAST_PICKUP] = {
        ["CHAIN_BEGIN"] = "FAMILY_FEAST";
    };
    [QG_SPRING_INDEX.FAMILY_FEAST_LAMB] = {};
    [QG_SPRING_INDEX.FAMILY_FEAST_CARROTS] = {};
    [QG_SPRING_INDEX.FAMILY_FEAST_POTATOES] = {};
    [QG_SPRING_INDEX.FAMILY_FEAST_LEEKS_TALK] = {};
    [QG_SPRING_INDEX.FAMILY_FEAST_LEEKS] = {};
    [QG_SPRING_INDEX.FAMILY_FEAST_END] = {
        ["CHAIN_END"] = "FAMILY_FEAST";
    };

};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_PROGRESS[SPRING] = {};

if (CLIENTLANG == "FRENCH") then
    import "CubePlugins.FestivalBuddyII.QuickGuides.Spring.QuickGuideStrings_SpringFR";
elseif (CLIENTLANG == "GERMAN") then
    import "CubePlugins.FestivalBuddyII.QuickGuides.Spring.QuickGuideStrings_SpringDE";
else
    import "CubePlugins.FestivalBuddyII.QuickGuides.Spring.QuickGuideStrings_SpringEN";
end