-- Inn League / Ale Association Quest Indexes:

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_INDICIES[ILAA] = {};
QG_ILAA_INDEX = _G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_INDICIES[ILAA];

local i = 1;
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_BIT_OF_WHITE_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_CONVOLUTED_WINE_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_DARK_PRANK_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_DIFFERENT_REMINDER_OF_RIVENDELL_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_DRINK_OF_THE_BEST_CHARACTER_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "ALL_BUT_THE_GOOD_CIDER_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "BOMBURS_BREATH_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "NEVER_FURTHER_FROM_HOME_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "NOT_ATLIS_FAVOURITE_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "ONE_DRINK_TOO_FEW_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "QUITE_A_TICKLE_PICKUP");

i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "QUITE_A_TICKLE_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "QUITE_A_TICKLE_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "QUITE_A_PICKLE_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "QUITE_A_PICKLE_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "QUITE_A_PICKLE_END");

i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "NEVER_FURTHER_FROM_HOME_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "ONE_DRINK_TOO_FEW_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "ONE_DRINK_TOO_FEW_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "ONE_DRINK_TOO_MANY_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "ONE_DRINK_TOO_MANY_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "ONE_DRINK_TOO_MANY_END");

i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "NEVER_FURTHER_FROM_HOME_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "NEVER_FAR_FROM_HOME_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "NEVER_FAR_FROM_HOME_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "NEVER_FAR_FROM_HOME_END");

i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "ALL_BUT_THE_GOOD_CIDER_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_CONVOLUTED_WINE_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_BIT_OF_WHITE_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "BOMBURS_BREATH_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "NOT_ATLIS_FAVOURITE_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_DARK_PRANK_DRINK");

i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "BOMBURS_BREATH_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_MEMBER_IN_NEED_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_MEMBER_IN_NEED_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_MEMBER_IN_NEED_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_BIT_OF_WHITE_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_BIT_OF_BROWN_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_BIT_OF_BROWN_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_BIT_OF_BROWN_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "ALL_BUT_THE_GOOD_CIDER_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "ALL_BUT_THE_CIDER_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "ALL_BUT_THE_CIDER_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "ALL_BUT_THE_CIDER_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_DRINK_OF_THE_BEST_CHARACTER_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "NOT_ATLIS_FAVOURITE_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "ATLIS_FAVOURITE_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "ATLIS_FAVOURITE_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "ATLIS_FAVOURITE_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_DIFFERENT_REMINDER_OF_RIVENDELL_DRINK");

i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_CONVOLUTED_WINE_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_SIMPLE_WINE_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_SIMPLE_WINE_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_SIMPLE_WINE_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_DARK_PRANK_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_DARK_DAY_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_DARK_DAY_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_DARK_DAY_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_DRINK_OF_THE_BEST_CHARACTER_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_DRINK_OF_THE_WORST_CHARACTER_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_DRINK_OF_THE_WORST_CHARACTER_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_DRINK_OF_THE_WORST_CHARACTER_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_DIFFERENT_REMINDER_OF_RIVENDELL_END");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_REMINDER_OF_RIVENDELL_PICKUP");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_REMINDER_OF_RIVENDELL_DRINK");
i = AddNextQuickguideValue(QG_ILAA_INDEX, i, "A_REMINDER_OF_RIVENDELL_END");


_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CHAINS[ILAA] = {
    ["ALL_BUT_THE_GOOD_CIDER"] = {
        [QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_PICKUP] = true;
        [QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_DRINK] = true;
        [QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_END] = true;
    };
    ["ALL_BUT_THE_CIDER"] = {
        [QG_ILAA_INDEX.ALL_BUT_THE_CIDER_PICKUP] = true;
        [QG_ILAA_INDEX.ALL_BUT_THE_CIDER_DRINK] = true;
        [QG_ILAA_INDEX.ALL_BUT_THE_CIDER_END] = true;
    };
    ["NEVER_FURTHER_FROM_HOME"] = {
        [QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_PICKUP] = true;
        [QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_DRINK] = true;
        [QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_END] = true;
    };
    ["NEVER_FAR_FROM_HOME"] = {
        [QG_ILAA_INDEX.NEVER_FAR_FROM_HOME_PICKUP] = true;
        [QG_ILAA_INDEX.NEVER_FAR_FROM_HOME_DRINK] = true;
        [QG_ILAA_INDEX.NEVER_FAR_FROM_HOME_END] = true;
    };
    ["ONE_DRINK_TOO_FEW"] = {
        [QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_PICKUP] = true;
        [QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_DRINK] = true;
        [QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_END] = true;
    };
    ["ONE_DRINK_TOO_MANY"] = {
        [QG_ILAA_INDEX.ONE_DRINK_TOO_MANY_PICKUP] = true;
        [QG_ILAA_INDEX.ONE_DRINK_TOO_MANY_DRINK] = true;
        [QG_ILAA_INDEX.ONE_DRINK_TOO_MANY_END] = true;
    };
    ["QUITE_A_TICKLE"] = {
        [QG_ILAA_INDEX.QUITE_A_TICKLE_PICKUP] = true;
        [QG_ILAA_INDEX.QUITE_A_TICKLE_DRINK] = true;
        [QG_ILAA_INDEX.QUITE_A_TICKLE_END] = true;
    };
    ["QUITE_A_PICKLE"] = {
        [QG_ILAA_INDEX.QUITE_A_PICKLE_PICKUP] = true;
        [QG_ILAA_INDEX.QUITE_A_PICKLE_DRINK] = true;
        [QG_ILAA_INDEX.QUITE_A_PICKLE_END] = true;
    };
    ["A_BIT_OF_WHITE"] = {
        [QG_ILAA_INDEX.A_BIT_OF_WHITE_PICKUP] = true;
        [QG_ILAA_INDEX.A_BIT_OF_WHITE_DRINK] = true;
        [QG_ILAA_INDEX.A_BIT_OF_WHITE_END] = true;
    };
    ["A_BIT_OF_BROWN"] = {
        [QG_ILAA_INDEX.A_BIT_OF_BROWN_PICKUP] = true;
        [QG_ILAA_INDEX.A_BIT_OF_BROWN_DRINK] = true;
        [QG_ILAA_INDEX.A_BIT_OF_BROWN_END] = true;
    };
    ["BOMBURS_BREATH"] = {
        [QG_ILAA_INDEX.BOMBURS_BREATH_PICKUP] = true;
        [QG_ILAA_INDEX.BOMBURS_BREATH_DRINK] = true;
        [QG_ILAA_INDEX.BOMBURS_BREATH_END] = true;
    };
    ["A_MEMBER_IN_NEED"] = {
        [QG_ILAA_INDEX.A_MEMBER_IN_NEED_PICKUP] = true;
        [QG_ILAA_INDEX.A_MEMBER_IN_NEED_DRINK] = true;
        [QG_ILAA_INDEX.A_MEMBER_IN_NEED_END] = true;
    };
    ["A_DIFFERENT_REMINDER_OF_RIVENDELL"] = {
        [QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_PICKUP] = true;
        [QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_DRINK] = true;
        [QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_END] = true;
    };
    ["A_REMINDER_OF_RIVENDELL"] = {
        [QG_ILAA_INDEX.A_REMINDER_OF_RIVENDELL_PICKUP] = true;
        [QG_ILAA_INDEX.A_REMINDER_OF_RIVENDELL_DRINK] = true;
        [QG_ILAA_INDEX.A_REMINDER_OF_RIVENDELL_END] = true;
    };
    ["A_DRINK_OF_THE_BEST_CHARACTER"] = {
        [QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_PICKUP] = true;
        [QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_DRINK] = true;
        [QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_END] = true;
    };
    ["A_DRINK_OF_THE_WORST_CHARACTER"] = {
        [QG_ILAA_INDEX.A_DRINK_OF_THE_WORST_CHARACTER_PICKUP] = true;
        [QG_ILAA_INDEX.A_DRINK_OF_THE_WORST_CHARACTER_DRINK] = true;
        [QG_ILAA_INDEX.A_DRINK_OF_THE_WORST_CHARACTER_END] = true;
    };
    ["A_CONVOLUTED_WINE"] = {
        [QG_ILAA_INDEX.A_CONVOLUTED_WINE_PICKUP] = true;
        [QG_ILAA_INDEX.A_CONVOLUTED_WINE_DRINK] = true;
        [QG_ILAA_INDEX.A_CONVOLUTED_WINE_END] = true;
    };
    ["A_SIMPLE_WINE"] = {
        [QG_ILAA_INDEX.A_SIMPLE_WINE_PICKUP] = true;
        [QG_ILAA_INDEX.A_SIMPLE_WINE_DRINK] = true;
        [QG_ILAA_INDEX.A_SIMPLE_WINE_END] = true;
    };
    ["A_DARK_PRANK"] = {
        [QG_ILAA_INDEX.A_DARK_PRANK_PICKUP] = true;
        [QG_ILAA_INDEX.A_DARK_PRANK_DRINK] = true;
        [QG_ILAA_INDEX.A_DARK_PRANK_END] = true;
    };
    ["A_DARK_DAY"] = {
        [QG_ILAA_INDEX.A_DARK_DAY_PICKUP] = true;
        [QG_ILAA_INDEX.A_DARK_DAY_DRINK] = true;
        [QG_ILAA_INDEX.A_DARK_DAY_END] = true;
    };
    ["NOT_ATLIS_FAVOURITE"] = {
        [QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_PICKUP] = true;
        [QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_DRINK] = true;
        [QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_END] = true;
    };
    ["ATLIS_FAVOURITE"] = {
        [QG_ILAA_INDEX.ATLIS_FAVOURITE_PICKUP] = true;
        [QG_ILAA_INDEX.ATLIS_FAVOURITE_DRINK] = true;
        [QG_ILAA_INDEX.ATLIS_FAVOURITE_END] = true;
    };
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CHAIN_LOOKUP[ILAA] = {
    [QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_PICKUP] = "ALL_BUT_THE_GOOD_CIDER";
    [QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_DRINK] = "ALL_BUT_THE_GOOD_CIDER";
    [QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_END] = "ALL_BUT_THE_GOOD_CIDER";

    [QG_ILAA_INDEX.ALL_BUT_THE_CIDER_PICKUP] = "ALL_BUT_THE_CIDER";
    [QG_ILAA_INDEX.ALL_BUT_THE_CIDER_DRINK] = "ALL_BUT_THE_CIDER";
    [QG_ILAA_INDEX.ALL_BUT_THE_CIDER_END] = "ALL_BUT_THE_CIDER";

    [QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_PICKUP] = "NEVER_FURTHER_FROM_HOME";
    [QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_DRINK] = "NEVER_FURTHER_FROM_HOME";
    [QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_END] = "NEVER_FURTHER_FROM_HOME";

    [QG_ILAA_INDEX.NEVER_FAR_FROM_HOME_PICKUP] = "NEVER_FAR_FROM_HOME";
    [QG_ILAA_INDEX.NEVER_FAR_FROM_HOME_DRINK] = "NEVER_FAR_FROM_HOME";
    [QG_ILAA_INDEX.NEVER_FAR_FROM_HOME_END] = "NEVER_FAR_FROM_HOME";

    [QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_PICKUP] = "ONE_DRINK_TOO_FEW";
    [QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_DRINK] = "ONE_DRINK_TOO_FEW";
    [QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_END] = "ONE_DRINK_TOO_FEW";

    [QG_ILAA_INDEX.ONE_DRINK_TOO_MANY_PICKUP] = "ONE_DRINK_TOO_MANY";
    [QG_ILAA_INDEX.ONE_DRINK_TOO_MANY_DRINK] = "ONE_DRINK_TOO_MANY";
    [QG_ILAA_INDEX.ONE_DRINK_TOO_MANY_END] = "ONE_DRINK_TOO_MANY";

    [QG_ILAA_INDEX.QUITE_A_TICKLE_PICKUP] = "QUITE_A_TICKLE";
    [QG_ILAA_INDEX.QUITE_A_TICKLE_DRINK] = "QUITE_A_TICKLE";
    [QG_ILAA_INDEX.QUITE_A_TICKLE_END] = "QUITE_A_TICKLE";

    [QG_ILAA_INDEX.QUITE_A_PICKLE_PICKUP] = "QUITE_A_PICKLE";
    [QG_ILAA_INDEX.QUITE_A_PICKLE_DRINK] = "QUITE_A_PICKLE";
    [QG_ILAA_INDEX.QUITE_A_PICKLE_END] = "QUITE_A_PICKLE";

    [QG_ILAA_INDEX.A_BIT_OF_WHITE_PICKUP] = "A_BIT_OF_WHITE";
    [QG_ILAA_INDEX.A_BIT_OF_WHITE_DRINK] = "A_BIT_OF_WHITE";
    [QG_ILAA_INDEX.A_BIT_OF_WHITE_END] = "A_BIT_OF_WHITE";

    [QG_ILAA_INDEX.A_BIT_OF_BROWN_PICKUP] = "A_BIT_OF_BROWN";
    [QG_ILAA_INDEX.A_BIT_OF_BROWN_DRINK] = "A_BIT_OF_BROWN";
    [QG_ILAA_INDEX.A_BIT_OF_BROWN_END] = "A_BIT_OF_BROWN";

    [QG_ILAA_INDEX.BOMBURS_BREATH_PICKUP] = "BOMBURS_BREATH";
    [QG_ILAA_INDEX.BOMBURS_BREATH_DRINK] = "BOMBURS_BREATH";
    [QG_ILAA_INDEX.BOMBURS_BREATH_END] = "BOMBURS_BREATH";

    [QG_ILAA_INDEX.A_MEMBER_IN_NEED_PICKUP] = "A_MEMBER_IN_NEED";
    [QG_ILAA_INDEX.A_MEMBER_IN_NEED_DRINK] = "A_MEMBER_IN_NEED";
    [QG_ILAA_INDEX.A_MEMBER_IN_NEED_END] = "A_MEMBER_IN_NEED";

    [QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_PICKUP] = "A_DIFFERENT_REMINDER_OF_RIVENDELL";
    [QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_DRINK] = "A_DIFFERENT_REMINDER_OF_RIVENDELL";
    [QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_END] = "A_DIFFERENT_REMINDER_OF_RIVENDELL";

    [QG_ILAA_INDEX.A_REMINDER_OF_RIVENDELL_PICKUP] = "A_REMINDER_OF_RIVENDELL";
    [QG_ILAA_INDEX.A_REMINDER_OF_RIVENDELL_DRINK] = "A_REMINDER_OF_RIVENDELL";
    [QG_ILAA_INDEX.A_REMINDER_OF_RIVENDELL_END] = "A_REMINDER_OF_RIVENDELL";

    [QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_PICKUP] = "A_DRINK_OF_THE_BEST_CHARACTER";
    [QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_DRINK] = "A_DRINK_OF_THE_BEST_CHARACTER";
    [QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_END] = "A_DRINK_OF_THE_BEST_CHARACTER";

    [QG_ILAA_INDEX.A_DRINK_OF_THE_WORST_CHARACTER_PICKUP] = "A_DRINK_OF_THE_WORST_CHARACTER";
    [QG_ILAA_INDEX.A_DRINK_OF_THE_WORST_CHARACTER_DRINK] = "A_DRINK_OF_THE_WORST_CHARACTER";
    [QG_ILAA_INDEX.A_DRINK_OF_THE_WORST_CHARACTER_END] = "A_DRINK_OF_THE_WORST_CHARACTER";

    [QG_ILAA_INDEX.A_CONVOLUTED_WINE_PICKUP] = "A_CONVOLUTED_WINE";
    [QG_ILAA_INDEX.A_CONVOLUTED_WINE_DRINK] = "A_CONVOLUTED_WINE";
    [QG_ILAA_INDEX.A_CONVOLUTED_WINE_END] = "A_CONVOLUTED_WINE";

    [QG_ILAA_INDEX.A_SIMPLE_WINE_PICKUP] = "A_SIMPLE_WINE";
    [QG_ILAA_INDEX.A_SIMPLE_WINE_DRINK] = "A_SIMPLE_WINE";
    [QG_ILAA_INDEX.A_SIMPLE_WINE_END] = "A_SIMPLE_WINE";

    [QG_ILAA_INDEX.A_DARK_PRANK_PICKUP] = "A_DARK_PRANK";
    [QG_ILAA_INDEX.A_DARK_PRANK_DRINK] = "A_DARK_PRANK";
    [QG_ILAA_INDEX.A_DARK_PRANK_END] = "A_DARK_PRANK";

    [QG_ILAA_INDEX.A_DARK_DAY_PICKUP] = "A_DARK_DAY";
    [QG_ILAA_INDEX.A_DARK_DAY_DRINK] = "A_DARK_DAY";
    [QG_ILAA_INDEX.A_DARK_DAY_END] = "A_DARK_DAY";

    [QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_PICKUP] = "NOT_ATLIS_FAVOURITE";
    [QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_DRINK] = "NOT_ATLIS_FAVOURITE";
    [QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_END] = "NOT_ATLIS_FAVOURITE";

    [QG_ILAA_INDEX.ATLIS_FAVOURITE_PICKUP] = "ATLIS_FAVOURITE";
    [QG_ILAA_INDEX.ATLIS_FAVOURITE_DRINK] = "ATLIS_FAVOURITE";
    [QG_ILAA_INDEX.ATLIS_FAVOURITE_END] = "ATLIS_FAVOURITE";
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE[ILAA] = {
    [QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_PICKUP] = {
        ["CHAIN_BEGIN"] = "ALL_BUT_THE_GOOD_CIDER";
    };
    [QG_ILAA_INDEX.ALL_BUT_THE_CIDER_PICKUP] = {
        ["CHAIN_BEGIN"] = "ALL_BUT_THE_CIDER";
    };
    [QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_PICKUP] = {
        ["CHAIN_BEGIN"] = "NEVER_FURTHER_FROM_HOME";
    };
    [QG_ILAA_INDEX.NEVER_FAR_FROM_HOME_PICKUP] = {
        ["CHAIN_BEGIN"] = "NEVER_FAR_FROM_HOME";
    };
    [QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_PICKUP] = {
        ["CHAIN_BEGIN"] = "ONE_DRINK_TOO_FEW";
    };
    [QG_ILAA_INDEX.ONE_DRINK_TOO_MANY_PICKUP] = {
        ["CHAIN_BEGIN"] = "ONE_DRINK_TOO_MANY";
    };
    [QG_ILAA_INDEX.QUITE_A_TICKLE_PICKUP] = {
        ["CHAIN_BEGIN"] = "QUITE_A_TICKLE";
    };
    [QG_ILAA_INDEX.QUITE_A_PICKLE_PICKUP] = {
        ["CHAIN_BEGIN"] = "QUITE_A_PICKLE";
    };
    [QG_ILAA_INDEX.A_BIT_OF_WHITE_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_BIT_OF_WHITE";
        ["TIMER_START"] = true;
    };
    [QG_ILAA_INDEX.A_BIT_OF_BROWN_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_BIT_OF_BROWN";
    };
    [QG_ILAA_INDEX.BOMBURS_BREATH_PICKUP] = {
        ["CHAIN_BEGIN"] = "BOMBURS_BREATH";
    };
    [QG_ILAA_INDEX.A_MEMBER_IN_NEED_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_MEMBER_IN_NEED";
    };
    [QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_DIFFERENT_REMINDER_OF_RIVENDELL";
    };
    [QG_ILAA_INDEX.A_REMINDER_OF_RIVENDELL_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_REMINDER_OF_RIVENDELL";
    };
    [QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_DRINK_OF_THE_BEST_CHARACTER";
    };
    [QG_ILAA_INDEX.A_DRINK_OF_THE_WORST_CHARACTER_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_DRINK_OF_THE_WORST_CHARACTER";
    };
    [QG_ILAA_INDEX.A_CONVOLUTED_WINE_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_CONVOLUTED_WINE";
    };
    [QG_ILAA_INDEX.A_SIMPLE_WINE_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_SIMPLE_WINE";
    };
    [QG_ILAA_INDEX.A_DARK_PRANK_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_DARK_PRANK";
    };
    [QG_ILAA_INDEX.A_DARK_DAY_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_DARK_DAY";
    };
    [QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_PICKUP] = {
        ["CHAIN_BEGIN"] = "NOT_ATLIS_FAVOURITE";
    };
    [QG_ILAA_INDEX.ATLIS_FAVOURITE_PICKUP] = {
        ["CHAIN_BEGIN"] = "ATLIS_FAVOURITE";
    };

    [QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_DRINK] = {};
    [QG_ILAA_INDEX.ALL_BUT_THE_CIDER_DRINK] = {};
    [QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_DRINK] = {};
    [QG_ILAA_INDEX.NEVER_FAR_FROM_HOME_DRINK] = {};
    [QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_DRINK] = {};
    [QG_ILAA_INDEX.ONE_DRINK_TOO_MANY_DRINK] = {};
    [QG_ILAA_INDEX.QUITE_A_TICKLE_DRINK] = {};
    [QG_ILAA_INDEX.QUITE_A_PICKLE_DRINK] = {};
    [QG_ILAA_INDEX.A_BIT_OF_WHITE_DRINK] = {};
    [QG_ILAA_INDEX.A_BIT_OF_BROWN_DRINK] = {};
    [QG_ILAA_INDEX.BOMBURS_BREATH_DRINK] = {};
    [QG_ILAA_INDEX.A_MEMBER_IN_NEED_DRINK] = {};
    [QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_DRINK] = {};
    [QG_ILAA_INDEX.A_REMINDER_OF_RIVENDELL_DRINK] = {};
    [QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_DRINK] = {};
    [QG_ILAA_INDEX.A_DRINK_OF_THE_WORST_CHARACTER_DRINK] = {};
    [QG_ILAA_INDEX.A_CONVOLUTED_WINE_DRINK] = {};
    [QG_ILAA_INDEX.A_SIMPLE_WINE_DRINK] = {};
    [QG_ILAA_INDEX.A_DARK_PRANK_DRINK] = {};
    [QG_ILAA_INDEX.A_DARK_DAY_DRINK] = {};
    [QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_DRINK] = {};
    [QG_ILAA_INDEX.ATLIS_FAVOURITE_DRINK] = {};

    [QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_END] = {
        ["CHAIN_END"] = "ALL_BUT_THE_GOOD_CIDER";
    };
    [QG_ILAA_INDEX.ALL_BUT_THE_CIDER_END] = {
        ["CHAIN_END"] = "ALL_BUT_THE_CIDER";
    };
    [QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_END] = {
        ["CHAIN_END"] = "NEVER_FURTHER_FROM_HOME";
    };
    [QG_ILAA_INDEX.NEVER_FAR_FROM_HOME_END] = {
        ["CHAIN_END"] = "NEVER_FAR_FROM_HOME";
    };
    [QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_END] = {
        ["CHAIN_END"] = "ONE_DRINK_TOO_FEW";
    };
    [QG_ILAA_INDEX.ONE_DRINK_TOO_MANY_END] = {
        ["CHAIN_END"] = "ONE_DRINK_TOO_MANY";
    };
    [QG_ILAA_INDEX.QUITE_A_TICKLE_END] = {
        ["CHAIN_END"] = "QUITE_A_TICKLE";
    };
    [QG_ILAA_INDEX.QUITE_A_PICKLE_END] = {
        ["CHAIN_END"] = "QUITE_A_PICKLE";
    };
    [QG_ILAA_INDEX.A_BIT_OF_WHITE_END] = {
        ["CHAIN_END"] = "A_BIT_OF_WHITE";
    };
    [QG_ILAA_INDEX.A_BIT_OF_BROWN_END] = {
        ["CHAIN_END"] = "A_BIT_OF_BROWN";
    };
    [QG_ILAA_INDEX.BOMBURS_BREATH_END] = {
        ["CHAIN_END"] = "BOMBURS_BREATH";
    };
    [QG_ILAA_INDEX.A_MEMBER_IN_NEED_END] = {
        ["CHAIN_END"] = "A_MEMBER_IN_NEED";
    };
    [QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_END] = {
        ["CHAIN_END"] = "A_DIFFERENT_REMINDER_OF_RIVENDELL";
    };
    [QG_ILAA_INDEX.A_REMINDER_OF_RIVENDELL_END] = {
        ["CHAIN_END"] = "A_REMINDER_OF_RIVENDELL";
        ["TIMER_STOP"] = true;
    };
    [QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_END] = {
        ["CHAIN_END"] = "A_DRINK_OF_THE_BEST_CHARACTER";
    };
    [QG_ILAA_INDEX.A_DRINK_OF_THE_WORST_CHARACTER_END] = {
        ["CHAIN_END"] = "A_DRINK_OF_THE_WORST_CHARACTER";
    };
    [QG_ILAA_INDEX.A_CONVOLUTED_WINE_END] = {
        ["CHAIN_END"] = "A_CONVOLUTED_WINE";
    };
    [QG_ILAA_INDEX.A_SIMPLE_WINE_END] = {
        ["CHAIN_END"] = "A_SIMPLE_WINE";
    };
    [QG_ILAA_INDEX.A_DARK_PRANK_END] = {
        ["CHAIN_END"] = "A_DARK_PRANK";
    };
    [QG_ILAA_INDEX.A_DARK_DAY_END] = {
        ["CHAIN_END"] = "A_DARK_DAY";
    };
    [QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_END] = {
        ["CHAIN_END"] = "NOT_ATLIS_FAVOURITE";
    };
    [QG_ILAA_INDEX.ATLIS_FAVOURITE_END] = {
        ["CHAIN_END"] = "ATLIS_FAVOURITE";
    };
}

if (CLIENTLANG == "FRENCH") then
    import "CubePlugins.FestivalBuddyII.QuickGuides.InnLeagueAleAssociation.QuickGuideStrings_InnLeagueAleAssociationFR";
elseif (CLIENTLANG == "GERMAN") then
    import "CubePlugins.FestivalBuddyII.QuickGuides.InnLeagueAleAssociation.QuickGuideStrings_InnLeagueAleAssociationDE";
else
    import "CubePlugins.FestivalBuddyII.QuickGuides.InnLeagueAleAssociation.QuickGuideStrings_InnLeagueAleAssociationEN";
end