-- Inn League / Ale Association Quest Indexes:

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_INDICIES[ILAA] = {};
QG_ILAA_INDEX = _G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_INDICIES[ILAA];

local index = 1;
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "A_BIT_OF_WHITE_PICKUP");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "A_CONVOLUTED_WINE_PICKUP");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "A_DARK_PRANK_PICKUP");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "A_DIFFERENT_REMINDER_OF_RIVENDELL_PICKUP");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "A_DRINK_OF_THE_BEST_CHARACTER_PICKUP");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "ALL_BUT_THE_GOOD_CIDER_PICKUP");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "BOMBURS_BREATH_PICKUP");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "NEVER_FURTHER_FROM_HOME_PICKUP");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "NOT_ATLIS_FAVOURITE_PICKUP");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "ONE_DRINK_TOO_FEW_PICKUP");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "QUITE_A_TICKLE_PICKUP");

index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "QUITE_A_TICKLE_DRINK");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "QUITE_A_TICKLE_END");

index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "NEVER_FURTHER_FROM_HOME_DRINK");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "ONE_DRINK_TOO_FEW_DRINK");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "ONE_DRINK_TOO_FEW_END");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "NEVER_FURTHER_FROM_HOME_END");

index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "ALL_BUT_THE_GOOD_CIDER_DRINK");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "A_CONVOLUTED_WINE_DRINK");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "A_BIT_OF_WHITE_DRINK");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "BOMBURS_BREATH_DRINK");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "NOT_ATLIS_FAVOURITE_DRINK");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "A_DARK_PRANK_DRINK");

index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "BOMBURS_BREATH_END");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "A_BIT_OF_WHITE_END");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "ALL_BUT_THE_GOOD_CIDER_END");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "A_DRINK_OF_THE_BEST_CHARACTER_DRINK");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "NOT_ATLIS_FAVOURITE_END");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "A_DIFFERENT_REMINDER_OF_RIVENDELL_DRINK");

index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "A_CONVOLUTED_WINE_END");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "A_DARK_PRANK_END");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "A_DRINK_OF_THE_BEST_CHARACTER_END");
index = AddNextQuickguideValue(QG_ILAA_INDEX, index, "A_DIFFERENT_REMINDER_OF_RIVENDELL_END");

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CHAINS[ILAA] = {
    ["ALL_BUT_THE_GOOD_CIDER"] = {
        [QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_PICKUP] = true;
        [QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_DRINK] = true;
        [QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_END] = true;
    };
    ["NEVER_FURTHER_FROM_HOME"] = {
        [QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_PICKUP] = true;
        [QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_DRINK] = true;
        [QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_END] = true;
    };
    ["ONE_DRINK_TOO_FEW"] = {
        [QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_PICKUP] = true;
        [QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_DRINK] = true;
        [QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_END] = true;
    };
    ["QUITE_A_TICKLE"] = {
        [QG_ILAA_INDEX.QUITE_A_TICKLE_PICKUP] = true;
        [QG_ILAA_INDEX.QUITE_A_TICKLE_DRINK] = true;
        [QG_ILAA_INDEX.QUITE_A_TICKLE_END] = true;
    };
    ["A_BIT_OF_WHITE"] = {
        [QG_ILAA_INDEX.A_BIT_OF_WHITE_PICKUP] = true;
        [QG_ILAA_INDEX.A_BIT_OF_WHITE_DRINK] = true;
        [QG_ILAA_INDEX.A_BIT_OF_WHITE_END] = true;
    };
    ["BOMBURS_BREATH"] = {
        [QG_ILAA_INDEX.BOMBURS_BREATH_PICKUP] = true;
        [QG_ILAA_INDEX.BOMBURS_BREATH_DRINK] = true;
        [QG_ILAA_INDEX.BOMBURS_BREATH_END] = true;
    };
    ["A_DIFFERENT_REMINDER_OF_RIVENDELL"] = {
        [QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_PICKUP] = true;
        [QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_DRINK] = true;
        [QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_END] = true;
    };
    ["A_DRINK_OF_THE_BEST_CHARACTER"] = {
        [QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_PICKUP] = true;
        [QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_DRINK] = true;
        [QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_END] = true;
    };
    ["A_CONVOLUTED_WINE"] = {
        [QG_ILAA_INDEX.A_CONVOLUTED_WINE_PICKUP] = true;
        [QG_ILAA_INDEX.A_CONVOLUTED_WINE_DRINK] = true;
        [QG_ILAA_INDEX.A_CONVOLUTED_WINE_END] = true;
    };
    ["A_DARK_PRANK"] = {
        [QG_ILAA_INDEX.A_DARK_PRANK_PICKUP] = true;
        [QG_ILAA_INDEX.A_DARK_PRANK_DRINK] = true;
        [QG_ILAA_INDEX.A_DARK_PRANK_END] = true;
    };
    ["NOT_ATLIS_FAVOURITE"] = {
        [QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_PICKUP] = true;
        [QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_DRINK] = true;
        [QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_END] = true;
    };
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CHAIN_LOOKUP[ILAA] = {
	[QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_PICKUP] = "ALL_BUT_THE_GOOD_CIDER";
	[QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_DRINK] = "ALL_BUT_THE_GOOD_CIDER";
	[QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_END] = "ALL_BUT_THE_GOOD_CIDER";

	[QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_PICKUP] = "NEVER_FURTHER_FROM_HOME";
	[QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_DRINK] = "NEVER_FURTHER_FROM_HOME";
	[QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_END] = "NEVER_FURTHER_FROM_HOME";

	[QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_PICKUP] = "ONE_DRINK_TOO_FEW";
	[QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_DRINK] = "ONE_DRINK_TOO_FEW";
	[QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_END] = "ONE_DRINK_TOO_FEW";

	[QG_ILAA_INDEX.QUITE_A_TICKLE_PICKUP] = "QUITE_A_TICKLE";
	[QG_ILAA_INDEX.QUITE_A_TICKLE_DRINK] = "QUITE_A_TICKLE";
	[QG_ILAA_INDEX.QUITE_A_TICKLE_END] = "QUITE_A_TICKLE";

	[QG_ILAA_INDEX.A_BIT_OF_WHITE_PICKUP] = "A_BIT_OF_WHITE";
	[QG_ILAA_INDEX.A_BIT_OF_WHITE_DRINK] = "A_BIT_OF_WHITE";
	[QG_ILAA_INDEX.A_BIT_OF_WHITE_END] = "A_BIT_OF_WHITE";

	[QG_ILAA_INDEX.BOMBURS_BREATH_PICKUP] = "BOMBURS_BREATH";
	[QG_ILAA_INDEX.BOMBURS_BREATH_DRINK] = "BOMBURS_BREATH";
	[QG_ILAA_INDEX.BOMBURS_BREATH_END] = "BOMBURS_BREATH";

	[QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_PICKUP] = "A_DIFFERENT_REMINDER_OF_RIVENDELL";
	[QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_DRINK] = "A_DIFFERENT_REMINDER_OF_RIVENDELL";
	[QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_END] = "A_DIFFERENT_REMINDER_OF_RIVENDELL";

	[QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_PICKUP] = "A_DRINK_OF_THE_BEST_CHARACTER";
	[QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_DRINK] = "A_DRINK_OF_THE_BEST_CHARACTER";
	[QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_END] = "A_DRINK_OF_THE_BEST_CHARACTER";

	[QG_ILAA_INDEX.A_CONVOLUTED_WINE_PICKUP] = "A_CONVOLUTED_WINE";
	[QG_ILAA_INDEX.A_CONVOLUTED_WINE_DRINK] = "A_CONVOLUTED_WINE";
	[QG_ILAA_INDEX.A_CONVOLUTED_WINE_END] = "A_CONVOLUTED_WINE";

	[QG_ILAA_INDEX.A_DARK_PRANK_PICKUP] = "A_DARK_PRANK";
	[QG_ILAA_INDEX.A_DARK_PRANK_DRINK] = "A_DARK_PRANK";
	[QG_ILAA_INDEX.A_DARK_PRANK_END] = "A_DARK_PRANK";

	[QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_PICKUP] = "NOT_ATLIS_FAVOURITE";
	[QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_DRINK] = "NOT_ATLIS_FAVOURITE";
	[QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_END] = "NOT_ATLIS_FAVOURITE";
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE[ILAA] = {
    [QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_PICKUP] = {
        ["CHAIN_BEGIN"] = "ALL_BUT_THE_GOOD_CIDER";
    };
    [QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_PICKUP] = {
        ["CHAIN_BEGIN"] = "NEVER_FURTHER_FROM_HOME";
    };
    [QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_PICKUP] = {
        ["CHAIN_BEGIN"] = "ONE_DRINK_TOO_FEW";
    };
    [QG_ILAA_INDEX.QUITE_A_TICKLE_PICKUP] = {
        ["CHAIN_BEGIN"] = "QUITE_A_TICKLE";
    };
    [QG_ILAA_INDEX.A_BIT_OF_WHITE_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_BIT_OF_WHITE";
    };
    [QG_ILAA_INDEX.BOMBURS_BREATH_PICKUP] = {
        ["CHAIN_BEGIN"] = "BOMBURS_BREATH";
    };
    [QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_DIFFERENT_REMINDER_OF_RIVENDELL";
    };
    [QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_DRINK_OF_THE_BEST_CHARACTER";
    };
    [QG_ILAA_INDEX.A_CONVOLUTED_WINE_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_CONVOLUTED_WINE";
    };
    [QG_ILAA_INDEX.A_DARK_PRANK_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_DARK_PRANK";
    };
    [QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_PICKUP] = {
        ["CHAIN_BEGIN"] = "NOT_ATLIS_FAVOURITE";
    };

    [QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_DRINK] = {};
    [QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_DRINK] = {};
    [QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_DRINK] = {};
    [QG_ILAA_INDEX.QUITE_A_TICKLE_DRINK] = {};
    [QG_ILAA_INDEX.A_BIT_OF_WHITE_DRINK] = {};
    [QG_ILAA_INDEX.BOMBURS_BREATH_DRINK] = {};
    [QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_DRINK] = {};
    [QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_DRINK] = {};
    [QG_ILAA_INDEX.A_CONVOLUTED_WINE_DRINK] = {};
    [QG_ILAA_INDEX.A_DARK_PRANK_DRINK] = {};
    [QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_DRINK] = {};

    [QG_ILAA_INDEX.ALL_BUT_THE_GOOD_CIDER_END] = {
        ["CHAIN_END"] = "ALL_BUT_THE_GOOD_CIDER";
    };
    [QG_ILAA_INDEX.NEVER_FURTHER_FROM_HOME_END] = {
        ["CHAIN_END"] = "NEVER_FURTHER_FROM_HOME";
    };
    [QG_ILAA_INDEX.ONE_DRINK_TOO_FEW_END] = {
        ["CHAIN_END"] = "ONE_DRINK_TOO_FEW";
    };
    [QG_ILAA_INDEX.QUITE_A_TICKLE_END] = {
        ["CHAIN_END"] = "QUITE_A_TICKLE";
    };
    [QG_ILAA_INDEX.A_BIT_OF_WHITE_END] = {
        ["CHAIN_END"] = "A_BIT_OF_WHITE";
    };
    [QG_ILAA_INDEX.BOMBURS_BREATH_END] = {
        ["CHAIN_END"] = "BOMBURS_BREATH";
    };
    [QG_ILAA_INDEX.A_DIFFERENT_REMINDER_OF_RIVENDELL_END] = {
        ["CHAIN_END"] = "A_DIFFERENT_REMINDER_OF_RIVENDELL";
    };
    [QG_ILAA_INDEX.A_DRINK_OF_THE_BEST_CHARACTER_END] = {
        ["CHAIN_END"] = "A_DRINK_OF_THE_BEST_CHARACTER";
    };
    [QG_ILAA_INDEX.A_CONVOLUTED_WINE_END] = {
        ["CHAIN_END"] = "A_CONVOLUTED_WINE";
    };
    [QG_ILAA_INDEX.A_DARK_PRANK_END] = {
        ["CHAIN_END"] = "A_DARK_PRANK";
    };
    [QG_ILAA_INDEX.NOT_ATLIS_FAVOURITE_END] = {
        ["CHAIN_END"] = "NOT_ATLIS_FAVOURITE";
    };
}

if (CLIENTLANG == "FRENCH") then
    import "CubePlugins.FestivalBuddyII.QuickGuides.InnLeagueAleAssociation.QuickGuideStrings_InnLeagueAleAssociationFR";
elseif (CLIENTLANG == "GERMAN") then
    import "CubePlugins.FestivalBuddyII.QuickGuides.InnLeagueAleAssociation.QuickGuideStrings_InnLeagueAleAssociationDE";
else
    import "CubePlugins.FestivalBuddyII.QuickGuides.InnLeagueAleAssociation.QuickGuideStrings_InnLeagueAleAssociationEN";
end