-- Yule Quest Indexes:

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_INDICIES[YULE] = {};
QG_YULE_INDEX = _G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_INDICIES[YULE];

local index = 1;
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "IN_THE_SPIRIT_OF_YULE_PICKUP");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "MOVING_THEM_OFF_PICKUP");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "THE_ABOMINABLE_SNOW_BEASTS_PICKUP");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "MOVING_THEM_OFF_BARRETTNOWELL");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "MOVING_THEM_OFF_TEDIVES");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "COLD_AS_ICE_PICKUP");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "MAKING_MISCHIEF_PICKUP");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "MOVING_THEM_OFF_REGINAJUDSON");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "MOVING_THEM_OFF_JACKJUDSON");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "MOVING_THEM_OFF_BILLHYDE");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "MAKING_MISCHIEF_FIREWORKS");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "MAKING_MISCHIEF_LOOT");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "EMPTY_KEG_EMERGENCY_PICKUP");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "TIDYING_UP_PICKUP");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "STUFFING_THE_STUFFED_PICKUP");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "UNWILLING_FIREWOOD_PICKUP");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "TIDYING_UP_DISHES");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "TIDYING_UP_SPILLS");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "TIDYING_UP_GARBAGE");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "TIDYING_UP_END");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "THE_BIGGEST_STOMACH_OF_THEM_ALL_PICKUP");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "THE_BIGGEST_STOMACH_OF_THEM_ALL_WAIT");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "FILLING_THE_FIELD_PICKUP");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "A_BROKEN_SNOWMAN_PICKUP");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "A_BROKEN_SNOWMAN_STICK");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "STUFFING_THE_STUFFED_EGGS");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "UNWILLING_FIREWOOD_COLLECT");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "COLD_AS_ICE_DISPERSE");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "STUFFING_THE_STUFFED_BERRIES");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "THE_ABOMINABLE_SNOW_BEASTS_CHEER");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "STUFFING_THE_STUFFED_MUSHROOMS");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "MOVING_THEM_OFF_END");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "THE_ABOMINABLE_SNOW_BEASTS_END");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "COLD_AS_ICE_END");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "A_CHARITABLE_SPIRIT_PICKUP");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "MAKING_MISCHIEF_END");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "A_CHARITABLE_SPIRIT_REGINAJUDSON");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "A_CHARITABLE_SPIRIT_JACKJUDSON");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "A_CHARITABLE_SPIRIT_BILLHYDE");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "A_BROKEN_SNOWMAN_COAL");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "STUFFING_THE_STUFFED_BREAD");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "EMPTY_KEG_EMERGENCY_AVERT");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "EMPTY_KEG_EMERGENCY_END");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "STUFFING_THE_STUFFED_END");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "UNWILLING_FIREWOOD_END");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "A_BROKEN_SNOWMAN_END");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "FILLING_THE_FIELD_END");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "A_CHARITABLE_SPIRIT_BARRETTNOWELL");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "A_CHARITABLE_SPIRIT_TEDIVES");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "A_CHARITABLE_SPIRIT_END");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "YULE_FESTIVAL_DAILY_END");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "IN_THE_SPIRIT_OF_YULE_END");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION1");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "THE_BIGGEST_STOMACH_OF_THEM_ALL_END");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION2");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "THE_BIGGEST_STOMACH_OF_THEM_ALL_END_2");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION3");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "THE_BIGGEST_STOMACH_OF_THEM_ALL_END_3");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION4");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "THE_BIGGEST_STOMACH_OF_THEM_ALL_END_4");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION5");
index = AddNextQuickguideValue(QG_YULE_INDEX, index, "THE_BIGGEST_STOMACH_OF_THEM_ALL_END_5");


_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CHAINS[YULE] = {
    ["IN_THE_SPIRIT_OF_YULE"] = {
        [QG_YULE_INDEX.IN_THE_SPIRIT_OF_YULE_END] = true;
        [QG_YULE_INDEX.IN_THE_SPIRIT_OF_YULE_PICKUP] = true;
    };

    ["MOVING_THEM_OFF"] = {
        [QG_YULE_INDEX.MOVING_THEM_OFF_PICKUP] = true;
        [QG_YULE_INDEX.MOVING_THEM_OFF_BARRETTNOWELL] = true;
        [QG_YULE_INDEX.MOVING_THEM_OFF_TEDIVES] = true;
        [QG_YULE_INDEX.MOVING_THEM_OFF_REGINAJUDSON] = true;
        [QG_YULE_INDEX.MOVING_THEM_OFF_JACKJUDSON] = true;
        [QG_YULE_INDEX.MOVING_THEM_OFF_BILLHYDE] = true;
        [QG_YULE_INDEX.MOVING_THEM_OFF_END] = true;
    };

    ["THE_ABOMINABLE_SNOW_BEASTS"] = {
        [QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_PICKUP] = true;
        [QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_CHEER] = true;
        [QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_END] = true;
    };

    ["COLD_AS_ICE"] = {
        [QG_YULE_INDEX.COLD_AS_ICE_PICKUP] = true;
        [QG_YULE_INDEX.COLD_AS_ICE_DISPERSE] = true;
        [QG_YULE_INDEX.COLD_AS_ICE_END] = true;
    };

    ["MAKING_MISCHIEF"] = {
        [QG_YULE_INDEX.MAKING_MISCHIEF_PICKUP] = true;
        [QG_YULE_INDEX.MAKING_MISCHIEF_FIREWORKS] = true;
        [QG_YULE_INDEX.MAKING_MISCHIEF_LOOT] = true;
        [QG_YULE_INDEX.MAKING_MISCHIEF_END] = true;
    };

    ["EMPTY_KEG_EMERGENCY"] = {
        [QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_PICKUP] = true;
        [QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_AVERT] = true;
        [QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_END] = true;
    };

    ["TIDYING_UP"] = {
        [QG_YULE_INDEX.TIDYING_UP_DISHES] = true;
        [QG_YULE_INDEX.TIDYING_UP_END] = true;
        [QG_YULE_INDEX.TIDYING_UP_GARBAGE] = true;
        [QG_YULE_INDEX.TIDYING_UP_PICKUP] = true;
        [QG_YULE_INDEX.TIDYING_UP_SPILLS] = true;
    };

    ["STUFFING_THE_STUFFED"] = {
        [QG_YULE_INDEX.STUFFING_THE_STUFFED_BERRIES] = true;
        [QG_YULE_INDEX.STUFFING_THE_STUFFED_BREAD] = true;
        [QG_YULE_INDEX.STUFFING_THE_STUFFED_EGGS] = true;
        [QG_YULE_INDEX.STUFFING_THE_STUFFED_END] = true;
        [QG_YULE_INDEX.STUFFING_THE_STUFFED_MUSHROOMS] = true;
        [QG_YULE_INDEX.STUFFING_THE_STUFFED_PICKUP] = true;
    };

    ["UNWILLING_FIREWOOD"] = {
        [QG_YULE_INDEX.UNWILLING_FIREWOOD_COLLECT] = true;
        [QG_YULE_INDEX.UNWILLING_FIREWOOD_END] = true;
        [QG_YULE_INDEX.UNWILLING_FIREWOOD_PICKUP] = true;
    };

    ["FILLING_THE_FIELD"] = {
        [QG_YULE_INDEX.FILLING_THE_FIELD_PICKUP] = true;
        [QG_YULE_INDEX.FILLING_THE_FIELD_END] = true;
    };

    ["A_BROKEN_SNOWMAN"] = {
        [QG_YULE_INDEX.A_BROKEN_SNOWMAN_COAL] = true;
        [QG_YULE_INDEX.A_BROKEN_SNOWMAN_END] = true;
        [QG_YULE_INDEX.A_BROKEN_SNOWMAN_PICKUP] = true;
        [QG_YULE_INDEX.A_BROKEN_SNOWMAN_STICK] = true;
    };

    ["A_CHARITABLE_SPIRIT"] = {
        [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_BARRETTNOWELL] = true;
        [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_BILLHYDE] = true;
        [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_END] = true;
        [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_JACKJUDSON] = true;
        [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_PICKUP] = true;
        [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_REGINAJUDSON] = true;
        [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_TEDIVES] = true;
    };

    ["THE_BIGGEST_STOMACH_OF_THEM_ALL"] = {
        [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_PICKUP] = true;
        [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION1] = true;
        [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_WAIT] = true;
        [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END] = true;
    };

    ["THE_BIGGEST_STOMACH_OF_THEM_ALL_2"] = {
        [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_2] = true;
        [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION2] = true;
    };

    ["THE_BIGGEST_STOMACH_OF_THEM_ALL_3"] = {
        [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_3] = true;
        [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION3] = true;
    };

    ["THE_BIGGEST_STOMACH_OF_THEM_ALL_4"] = {
        [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_4] = true;
        [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION4] = true;
    };

    ["THE_BIGGEST_STOMACH_OF_THEM_ALL_5"] = {
        [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_5] = true;
        [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION5] = true;
    };

};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CHAIN_LOOKUP[YULE] = {
    [QG_YULE_INDEX.A_BROKEN_SNOWMAN_COAL] = "A_BROKEN_SNOWMAN";
    [QG_YULE_INDEX.A_BROKEN_SNOWMAN_END] = "A_BROKEN_SNOWMAN";
    [QG_YULE_INDEX.A_BROKEN_SNOWMAN_PICKUP] = "A_BROKEN_SNOWMAN";
    [QG_YULE_INDEX.A_BROKEN_SNOWMAN_STICK] = "A_BROKEN_SNOWMAN";
    [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_BARRETTNOWELL] = "A_CHARITABLE_SPIRIT";
    [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_BILLHYDE] = "A_CHARITABLE_SPIRIT";
    [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_END] = "A_CHARITABLE_SPIRIT";
    [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_JACKJUDSON] = "A_CHARITABLE_SPIRIT";
    [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_PICKUP] = "A_CHARITABLE_SPIRIT";
    [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_REGINAJUDSON] = "A_CHARITABLE_SPIRIT";
    [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_TEDIVES] = "A_CHARITABLE_SPIRIT";
    [QG_YULE_INDEX.COLD_AS_ICE_DISPERSE] = "COLD_AS_ICE";
    [QG_YULE_INDEX.COLD_AS_ICE_END] = "COLD_AS_ICE";
    [QG_YULE_INDEX.COLD_AS_ICE_PICKUP] = "COLD_AS_ICE";
    [QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_END] = "EMPTY_KEG_EMERGENCY";
    [QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_AVERT] = "EMPTY_KEG_EMERGENCY";
    [QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_PICKUP] = "EMPTY_KEG_EMERGENCY";
    [QG_YULE_INDEX.FILLING_THE_FIELD_END] = "FILLING_THE_FIELD";
    [QG_YULE_INDEX.FILLING_THE_FIELD_PICKUP] = "FILLING_THE_FIELD";
    [QG_YULE_INDEX.IN_THE_SPIRIT_OF_YULE_END] = "IN_THE_SPIRIT_OF_YULE";
    [QG_YULE_INDEX.IN_THE_SPIRIT_OF_YULE_PICKUP] = "IN_THE_SPIRIT_OF_YULE";
    [QG_YULE_INDEX.MAKING_MISCHIEF_END] = "MAKING_MISCHIEF";
    [QG_YULE_INDEX.MAKING_MISCHIEF_FIREWORKS] = "MAKING_MISCHIEF";
    [QG_YULE_INDEX.MAKING_MISCHIEF_LOOT] = "MAKING_MISCHIEF";
    [QG_YULE_INDEX.MAKING_MISCHIEF_PICKUP] = "MAKING_MISCHIEF";
    [QG_YULE_INDEX.MAKING_MISCHIEF_PICKUP] = "MAKING_MISCHIEF";
    [QG_YULE_INDEX.MOVING_THEM_OFF_BARRETTNOWELL] = "MOVING_THEM_OFF";
    [QG_YULE_INDEX.MOVING_THEM_OFF_BILLHYDE] = "MOVING_THEM_OFF";
    [QG_YULE_INDEX.MOVING_THEM_OFF_END] = "MOVING_THEM_OFF";
    [QG_YULE_INDEX.MOVING_THEM_OFF_JACKJUDSON] = "MOVING_THEM_OFF";
    [QG_YULE_INDEX.MOVING_THEM_OFF_PICKUP] = "MOVING_THEM_OFF";
    [QG_YULE_INDEX.MOVING_THEM_OFF_REGINAJUDSON] = "MOVING_THEM_OFF";
    [QG_YULE_INDEX.MOVING_THEM_OFF_TEDIVES] = "MOVING_THEM_OFF";
    [QG_YULE_INDEX.STUFFING_THE_STUFFED_BERRIES] = "STUFFING_THE_STUFFED";
    [QG_YULE_INDEX.STUFFING_THE_STUFFED_BREAD] = "STUFFING_THE_STUFFED";
    [QG_YULE_INDEX.STUFFING_THE_STUFFED_EGGS] = "STUFFING_THE_STUFFED";
    [QG_YULE_INDEX.STUFFING_THE_STUFFED_END] = "STUFFING_THE_STUFFED";
    [QG_YULE_INDEX.STUFFING_THE_STUFFED_MUSHROOMS] = "STUFFING_THE_STUFFED";
    [QG_YULE_INDEX.STUFFING_THE_STUFFED_PICKUP] = "STUFFING_THE_STUFFED";
    [QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_CHEER] = "THE_ABOMINABLE_SNOW_BEASTS";
    [QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_END] = "THE_ABOMINABLE_SNOW_BEASTS";
    [QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_PICKUP] = "THE_ABOMINABLE_SNOW_BEASTS";
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_PICKUP] = "THE_BIGGEST_STOMACH_OF_THEM_ALL";
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_WAIT] = "THE_BIGGEST_STOMACH_OF_THEM_ALL";
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION1] = "THE_BIGGEST_STOMACH_OF_THEM_ALL";
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END] = "THE_BIGGEST_STOMACH_OF_THEM_ALL";
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION2] = "THE_BIGGEST_STOMACH_OF_THEM_ALL_2";
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_2] = "THE_BIGGEST_STOMACH_OF_THEM_ALL_2";
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION3] = "THE_BIGGEST_STOMACH_OF_THEM_ALL_3";
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_3] = "THE_BIGGEST_STOMACH_OF_THEM_ALL_3";
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION4] = "THE_BIGGEST_STOMACH_OF_THEM_ALL_4";
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_4] = "THE_BIGGEST_STOMACH_OF_THEM_ALL_4";
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION5] = "THE_BIGGEST_STOMACH_OF_THEM_ALL_5";
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_5] = "THE_BIGGEST_STOMACH_OF_THEM_ALL_5";
    [QG_YULE_INDEX.TIDYING_UP_DISHES] = "TIDYING_UP";
    [QG_YULE_INDEX.TIDYING_UP_END] = "TIDYING_UP";
    [QG_YULE_INDEX.TIDYING_UP_GARBAGE] = "TIDYING_UP";
    [QG_YULE_INDEX.TIDYING_UP_PICKUP] = "TIDYING_UP";
    [QG_YULE_INDEX.TIDYING_UP_SPILLS] = "TIDYING_UP";
    [QG_YULE_INDEX.UNWILLING_FIREWOOD_COLLECT] = "UNWILLING_FIREWOOD";
    [QG_YULE_INDEX.UNWILLING_FIREWOOD_END] = "UNWILLING_FIREWOOD";
    [QG_YULE_INDEX.UNWILLING_FIREWOOD_PICKUP] = "UNWILLING_FIREWOOD";
    [QG_YULE_INDEX.YULE_FESTIVAL_DAILY_END] = "YULE_FESTIVAL_DAILY";
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE[YULE] = {
    [QG_YULE_INDEX.IN_THE_SPIRIT_OF_YULE_PICKUP] = {
        ["CHAIN_BEGIN"] = "IN_THE_SPIRIT_OF_YULE";
    };
    [QG_YULE_INDEX.MOVING_THEM_OFF_PICKUP] = {
        ["CHAIN_BEGIN"] = "MOVING_THEM_OFF";
    };
    [QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_PICKUP] = {
        ["CHAIN_BEGIN"] = "THE_ABOMINABLE_SNOW_BEASTS";
    };
    [QG_YULE_INDEX.MOVING_THEM_OFF_BARRETTNOWELL] = {
    };
    [QG_YULE_INDEX.MOVING_THEM_OFF_TEDIVES] = {
    };
    [QG_YULE_INDEX.COLD_AS_ICE_PICKUP] = {
        ["CHAIN_BEGIN"] = "COLD_AS_ICE";
    };
    [QG_YULE_INDEX.MAKING_MISCHIEF_PICKUP] = {
        ["CHAIN_BEGIN"] = "MAKING_MISCHIEF";
    };
    [QG_YULE_INDEX.MOVING_THEM_OFF_REGINAJUDSON] = {
    };
    [QG_YULE_INDEX.MOVING_THEM_OFF_JACKJUDSON] = {
    };
    [QG_YULE_INDEX.MOVING_THEM_OFF_BILLHYDE] = {
    };
    [QG_YULE_INDEX.MAKING_MISCHIEF_FIREWORKS] = {
    };
    [QG_YULE_INDEX.MAKING_MISCHIEF_LOOT] = {
    };
    [QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_PICKUP] = {
        ["CHAIN_BEGIN"] = "EMPTY_KEG_EMERGENCY";
    };
    [QG_YULE_INDEX.TIDYING_UP_PICKUP] = {
        ["CHAIN_BEGIN"] = "TIDYING_UP";
    };
    [QG_YULE_INDEX.STUFFING_THE_STUFFED_PICKUP] = {
        ["CHAIN_BEGIN"] = "STUFFING_THE_STUFFED";
    };
    [QG_YULE_INDEX.UNWILLING_FIREWOOD_PICKUP] = {
        ["CHAIN_BEGIN"] = "UNWILLING_FIREWOOD";
    };
    [QG_YULE_INDEX.TIDYING_UP_DISHES] = {
    };
    [QG_YULE_INDEX.TIDYING_UP_SPILLS] = {
    };
    [QG_YULE_INDEX.TIDYING_UP_GARBAGE] = {
    };
    [QG_YULE_INDEX.MAKING_MISCHIEF_END] = {
        ["CHAIN_END"] = "MAKING_MISCHIEF";
    };
    [QG_YULE_INDEX.STUFFING_THE_STUFFED_BREAD] = {
    };
    [QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_AVERT] = {
    };
    [QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_END] = {
        ["CHAIN_END"] = "EMPTY_KEG_EMERGENCY";
    };
    [QG_YULE_INDEX.TIDYING_UP_END] = {
        ["CHAIN_END"] = "TIDYING_UP";
    };
    [QG_YULE_INDEX.FILLING_THE_FIELD_PICKUP] = {
        ["CHAIN_BEGIN"] = "FILLING_THE_FIELD";
    };
    [QG_YULE_INDEX.A_BROKEN_SNOWMAN_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_BROKEN_SNOWMAN";
    };
    [QG_YULE_INDEX.A_BROKEN_SNOWMAN_STICK] = {
    };
    [QG_YULE_INDEX.STUFFING_THE_STUFFED_EGGS] = {
    };
    [QG_YULE_INDEX.UNWILLING_FIREWOOD_COLLECT] = {
    };
    [QG_YULE_INDEX.COLD_AS_ICE_DISPERSE] = {
    };
    [QG_YULE_INDEX.STUFFING_THE_STUFFED_BERRIES] = {
    };
    [QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_CHEER] = {
    };
    [QG_YULE_INDEX.STUFFING_THE_STUFFED_MUSHROOMS] = {
    };
    [QG_YULE_INDEX.YULE_FESTIVAL_DAILY_END] = {
        ["CHAIN_END"] = "YULE_FESTIVAL_DAILY";
    };
    [QG_YULE_INDEX.MOVING_THEM_OFF_END] = {
        ["CHAIN_END"] = "MOVING_THEM_OFF";
    };
    [QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_END] = {
        ["CHAIN_END"] = "THE_ABOMINABLE_SNOW_BEASTS";
    };
    [QG_YULE_INDEX.STUFFING_THE_STUFFED_END] = {
        ["CHAIN_END"] = "STUFFING_THE_STUFFED";
    };
    [QG_YULE_INDEX.UNWILLING_FIREWOOD_END] = {
        ["CHAIN_END"] = "UNWILLING_FIREWOOD";
    };
    [QG_YULE_INDEX.A_BROKEN_SNOWMAN_COAL] = {
    };
    [QG_YULE_INDEX.A_BROKEN_SNOWMAN_END] = {
        ["CHAIN_END"] = "A_BROKEN_SNOWMAN";
    };
    [QG_YULE_INDEX.FILLING_THE_FIELD_END] = {
        ["CHAIN_END"] = "FILLING_THE_FIELD";
    };
    [QG_YULE_INDEX.COLD_AS_ICE_END] = {
        ["CHAIN_END"] = "COLD_AS_ICE";
    };
    [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_CHARITABLE_SPIRIT";
    };
    [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_REGINAJUDSON] = {
    };
    [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_JACKJUDSON] = {
    };
    [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_BILLHYDE] = {
    };
    [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_BARRETTNOWELL] = {
    };
    [QG_YULE_INDEX.IN_THE_SPIRIT_OF_YULE_END] = {
        ["CHAIN_END"] = "IN_THE_SPIRIT_OF_YULE";
    };
    [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_TEDIVES] = {
    };
    [QG_YULE_INDEX.A_CHARITABLE_SPIRIT_END] = {
        ["CHAIN_END"] = "A_CHARITABLE_SPIRIT";
    };
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_PICKUP] = {
        ["CHAIN_BEGIN"] = "THE_BIGGEST_STOMACH_OF_THEM_ALL";
    };
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_WAIT] = {
    };
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION1] = {
    };
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END] = {
        ["CHAIN_END"] = "THE_BIGGEST_STOMACH_OF_THEM_ALL";
    };
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION2] = {
    };
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_2] = {
        ["CHAIN_END"] = "THE_BIGGEST_STOMACH_OF_THEM_ALL_2";
    };
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION3] = {
    };
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_3] = {
        ["CHAIN_END"] = "THE_BIGGEST_STOMACH_OF_THEM_ALL_3";
    };
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION4] = {
    };
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_4] = {
        ["CHAIN_END"] = "THE_BIGGEST_STOMACH_OF_THEM_ALL_4";
    };
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION5] = {
    };
    [QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_5] = {
        ["CHAIN_END"] = "THE_BIGGEST_STOMACH_OF_THEM_ALL_5";
    };
}

local language = Turbine.Engine:GetLanguage();
if (language == Turbine.Language.French) then
    import "CubePlugins.FestivalBuddyII.QuickGuides.Yule.QuickGuideStrings_YuleFR";
elseif (language == Turbine.Language.German) then
    import "CubePlugins.FestivalBuddyII.QuickGuides.Yule.QuickGuideStrings_YuleDE";
else
    import "CubePlugins.FestivalBuddyII.QuickGuides.Yule.QuickGuideStrings_YuleEN";
end