_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CREDITS[YULE] = "\nThis guide created by Cube during the 2023 Yule.";

QG_YULE = _G.CubePlugins.FestivalBuddyII._QUICK_GUIDE[YULE];
QG_YULE[QG_YULE_INDEX.IN_THE_SPIRIT_OF_YULE_PICKUP].DISPLAY = "Take 'L'esprit de Yule' from Mara Bassableux in Hibernaville";
QG_YULE[QG_YULE_INDEX.MOVING_THEM_OFF_PICKUP].DISPLAY = "Take 'Circulez' from Garde Kember";
QG_YULE[QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_PICKUP].DISPLAY = "Take 'Les abominables bêtes des neiges' from Garde Kember";
QG_YULE[QG_YULE_INDEX.MOVING_THEM_OFF_BARRETTNOWELL].DISPLAY = "Circulez: Continue quest with Barrett Patraque (next to Mara Bassableux)";
QG_YULE[QG_YULE_INDEX.MOVING_THEM_OFF_TEDIVES].DISPLAY = "Circulez: Continue quest with Ted Fermeron (midway between Ona Kay and Daley Escarpette)";
QG_YULE[QG_YULE_INDEX.COLD_AS_ICE_PICKUP].DISPLAY = "Take 'Froid mortel' from Daley Escarpette";
QG_YULE[QG_YULE_INDEX.MAKING_MISCHIEF_PICKUP].DISPLAY = "Take 'Mauvais tours' from Gareth Larouille";
QG_YULE[QG_YULE_INDEX.MOVING_THEM_OFF_REGINAJUDSON].DISPLAY = "Circulez: Continue quest with Régine Latombe (midway between Daley Escarpette and the Théâtre de Rivegel)";
QG_YULE[QG_YULE_INDEX.MOVING_THEM_OFF_JACKJUDSON].DISPLAY = "Circulez: Continue quest with Jacques Latombe (next to the Théâtre de Rivegel)";
QG_YULE[QG_YULE_INDEX.MOVING_THEM_OFF_BILLHYDE].DISPLAY = "Circulez: Continue quest with Bill Cachette (next to final Le plus gros estomac table)";
QG_YULE[QG_YULE_INDEX.MAKING_MISCHIEF_FIREWORKS].DISPLAY = "Mauvais tours: Set off feux d'artifice";
QG_YULE[QG_YULE_INDEX.MAKING_MISCHIEF_LOOT].DISPLAY = "Mauvais tours: Loot 8 distracted patrons";
QG_YULE[QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_PICKUP].DISPLAY = "Take 'Des tonneaux presque vides' from Basile Ventbon";
QG_YULE[QG_YULE_INDEX.TIDYING_UP_PICKUP].DISPLAY = "Take 'Grand nettoyage' from Basile Ventbon";
QG_YULE[QG_YULE_INDEX.STUFFING_THE_STUFFED_PICKUP].DISPLAY = "Take 'Gaver les participants' from Mabel Passegué";
QG_YULE[QG_YULE_INDEX.UNWILLING_FIREWOOD_PICKUP].DISPLAY = "Take 'Les fagots récalcitrants' from Mabel Passegué";
QG_YULE[QG_YULE_INDEX.TIDYING_UP_DISHES].DISPLAY = "Grand nettoyage: Ramassez 10 assiettes sales";
QG_YULE[QG_YULE_INDEX.TIDYING_UP_SPILLS].DISPLAY = "Grand nettoyage: Epongez 10 liquide renversé";
QG_YULE[QG_YULE_INDEX.TIDYING_UP_GARBAGE].DISPLAY = "Grand nettoyage: Ramassez 10 déchets qui empestent";
QG_YULE[QG_YULE_INDEX.MAKING_MISCHIEF_END].DISPLAY = "Turn in 'Mauvais tours' to Gareth Larouille";
QG_YULE[QG_YULE_INDEX.STUFFING_THE_STUFFED_BREAD].DISPLAY = "Gaver les participants: Faites 3 pain";
QG_YULE[QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_AVERT].DISPLAY = "Des tonneaux presque vides: Récupérez l'un des tonneaux et apportez-le"
QG_YULE[QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_END].DISPLAY = "Turn in 'Des tonneaux presque vides' to Basile Ventbon";
QG_YULE[QG_YULE_INDEX.TIDYING_UP_END].DISPLAY = "Turn in 'Grand nettoyage' to Basile Ventbon (if you already did 'Le plus gros estomac du monde', this can be delayed)";
QG_YULE[QG_YULE_INDEX.FILLING_THE_FIELD_PICKUP].DISPLAY = "Take 'Des bonshommes, sur le champ' from Virgil Verchamps";
QG_YULE[QG_YULE_INDEX.A_BROKEN_SNOWMAN_PICKUP].DISPLAY = "Take 'Un bonhomme de neige cassé ?' from Bonhomme de neige cassé de Virgil";
QG_YULE[QG_YULE_INDEX.A_BROKEN_SNOWMAN_STICK].DISPLAY = "Un bonhomme de neige cassé ?: Récupérez des brindilles";
QG_YULE[QG_YULE_INDEX.STUFFING_THE_STUFFED_EGGS].DISPLAY = "Gaver les participants: Ramassez 5 oeufs";
QG_YULE[QG_YULE_INDEX.UNWILLING_FIREWOOD_COLLECT].DISPLAY = "Les fagots récalcitrants: Ramassez 9 bois pour le feu";
QG_YULE[QG_YULE_INDEX.COLD_AS_ICE_DISPERSE].DISPLAY = "Froid mortel: Dispersez 4 temps glacial";
QG_YULE[QG_YULE_INDEX.STUFFING_THE_STUFFED_BERRIES].DISPLAY = "Gaver les participants: Cueillez 5 baies ";
QG_YULE[QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_CHEER].DISPLAY = "Les abominables bêtes des neiges: /bravo la bête 3 fois";
QG_YULE[QG_YULE_INDEX.STUFFING_THE_STUFFED_MUSHROOMS].DISPLAY = "Gaver les participants: Ramassez 5 champignons";
QG_YULE[QG_YULE_INDEX.YULE_FESTIVAL_DAILY_END].DISPLAY = "Turn in 'Festival de Yule (Quotidien)' to Mara Bassableux";
QG_YULE[QG_YULE_INDEX.MOVING_THEM_OFF_END].DISPLAY = "Turn in 'Circulez' to Garde Kember";
QG_YULE[QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_END].DISPLAY = "Turn in 'Les abominables bêtes des neiges' to Garde Kember";
QG_YULE[QG_YULE_INDEX.STUFFING_THE_STUFFED_END].DISPLAY = "Turn in 'Gaver les participants' to Mabel Passegué";
QG_YULE[QG_YULE_INDEX.UNWILLING_FIREWOOD_END].DISPLAY = "Turn in 'Les fagots récalcitrants' to Mabel Passegué";
QG_YULE[QG_YULE_INDEX.A_BROKEN_SNOWMAN_COAL].DISPLAY = "Un bonhomme de neige cassé ?: Récupérez du charbon";
QG_YULE[QG_YULE_INDEX.A_BROKEN_SNOWMAN_END].DISPLAY = "Turn in 'Un bonhomme de neige cassé ?' to Tas de neige";
QG_YULE[QG_YULE_INDEX.FILLING_THE_FIELD_END].DISPLAY = "Turn in 'Des bonshommes, sur le champ' to Virgil Verchamps";
QG_YULE[QG_YULE_INDEX.COLD_AS_ICE_END].DISPLAY = "Turn in 'Froid mortel' to Daley Escarpette";
QG_YULE[QG_YULE_INDEX.A_CHARITABLE_SPIRIT_PICKUP].DISPLAY = "Pick up 'Un esprit charitable' from Daley Escarpette";
QG_YULE[QG_YULE_INDEX.A_CHARITABLE_SPIRIT_REGINAJUDSON].DISPLAY = "Un esprit charitable: Continue quest with Régine Latombe (midway between Daley Escarpette and the Théâtre de Rivegel)";
QG_YULE[QG_YULE_INDEX.A_CHARITABLE_SPIRIT_JACKJUDSON].DISPLAY = "Un esprit charitable: Continue quest with Jacques Latombe (next to Théâtre de Rivegel)";
QG_YULE[QG_YULE_INDEX.A_CHARITABLE_SPIRIT_BILLHYDE].DISPLAY = "Un esprit charitable: Continue quest with Bill Cachette (next to final Le plus gros estomac table)";
QG_YULE[QG_YULE_INDEX.A_CHARITABLE_SPIRIT_BARRETTNOWELL].DISPLAY = "Un esprit charitable: Continue quest with Barrett Patraque (next to Mara Bassableux)";
QG_YULE[QG_YULE_INDEX.IN_THE_SPIRIT_OF_YULE_END].DISPLAY = "Turn in 'L'esprit de Yule' to Mara Bassableux.";
QG_YULE[QG_YULE_INDEX.A_CHARITABLE_SPIRIT_TEDIVES].DISPLAY = "Un esprit charitable: Continue quest with Ted Fermeron (midway between Ona Kay and Daley Escarpette)";
QG_YULE[QG_YULE_INDEX.A_CHARITABLE_SPIRIT_END].DISPLAY = "Turn in 'Un esprit charitable' to Daley Escarpette";
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_PICKUP].DISPLAY = "Pick up 'Le plus gros estomac du monde' from Ona Kay";
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_WAIT].DISPLAY = "Wait for the eating contest to begin. (Keep questing in Rivegel)";
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION1].DISPLAY = "Mangez au premier poste";
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END].DISPLAY = "Turn in 'Le plus gros estomac du monde' to Ona Kay";
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION2].DISPLAY = "Mangez au deuxième poste";
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_2].DISPLAY = "Turn in 'Le plus gros estomac du monde (partie II)' to Freddy Siméon";
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION3].DISPLAY = "Mangez au troisième poste";
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_3].DISPLAY = "Turn in 'Le plus gros estomac du monde (partie III)' to Jacques Passegué";
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION4].DISPLAY = "Mangez au quatrième poste";
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_4].DISPLAY = "Turn in 'Le plus gros estomac du monde (partie IV)' to Nora Levisson";
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION5].DISPLAY = "Mangez au cinquième poste";
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_5].DISPLAY = "Turn in 'Le plus gros estomac du monde (partie V)' to Ian Prudhomme";

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_PROGRESS[YULE] = {
    ["Vous avez fait les poches d'un visiteur fortuné %((%d+)/(%d+)%)"] = QG_YULE_INDEX.MAKING_MISCHIEF_LOOT;
    ["Assiettes sales ramassées %((%d+)/(%d+)%)"] = QG_YULE_INDEX.TIDYING_UP_DISHES;
    ["Liquides renversés nettoyés %((%d+)/(%d+)%)"] = QG_YULE_INDEX.TIDYING_UP_SPILLS;
    ["Déchets pestilentiels ramassés %((%d+)/(%d+)%)"] = QG_YULE_INDEX.TIDYING_UP_GARBAGE;
    ["Œufs ramassés %((%d+)/(%d+)%)"] = QG_YULE_INDEX.STUFFING_THE_STUFFED_EGGS;
    ["Fagots récalcitrants récupérés %((%d+)/(%d+)%)"] = QG_YULE_INDEX.UNWILLING_FIREWOOD_COLLECT;
    ["Temps glacial dispersé %((%d+)/(%d+)%)"] = QG_YULE_INDEX.COLD_AS_ICE_DISPERSE;
    ["Baies cueillies %((%d+)/(%d+)%)"] = QG_YULE_INDEX.STUFFING_THE_STUFFED_BERRIES;
    ["Joie apportée aux bêtes des neiges %((%d+)/(%d+)%)"] = QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_CHEER;
    ["Champignons ramassés %((%d+)/(%d+)%)"] = QG_YULE_INDEX.STUFFING_THE_STUFFED_MUSHROOMS;
    ["Pains cuits %((%d+)/(%d+)%)"] = QG_YULE_INDEX.STUFFING_THE_STUFFED_BREAD;
    ["Nourriture avalée au premier poste %((%d+)/(%d+)%)"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION1;
    ["Nourriture avalée au deuxième poste %((%d+)/(%d+)%)"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION2;
    ["Nourriture avalée au troisième poste %((%d+)/(%d+)%)"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION3;
    ["Nourriture avalée au quatrième poste %((%d+)/(%d+)%)"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION4;
    ["Nourriture avalée au cinquième poste %((%d+)/(%d+)%)"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION5;
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_NEW_QUEST_STRINGS[YULE] = {
    ["Nouvelle quête : L'esprit de Yule"] = QG_YULE_INDEX.IN_THE_SPIRIT_OF_YULE_PICKUP;
    ["Nouvelle quête : Circulez"] = QG_YULE_INDEX.MOVING_THEM_OFF_PICKUP;
    ["Nouvelle quête : Les abominables bêtes des neiges"] = QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_PICKUP;
    ["Nouvelle quête : Froid mortel"] = QG_YULE_INDEX.COLD_AS_ICE_PICKUP;
    ["Nouvelle quête : Mauvais tours"] = QG_YULE_INDEX.MAKING_MISCHIEF_PICKUP;
    ["Nouvelle quête : Des tonneaux presque vides"] = QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_PICKUP;
    ["Nouvelle quête : Grand nettoyage"] = QG_YULE_INDEX.TIDYING_UP_PICKUP;
    ["Nouvelle quête : Gaver les participants"] = QG_YULE_INDEX.STUFFING_THE_STUFFED_PICKUP;
    ["Nouvelle quête : Les fagots récalcitrants"] = QG_YULE_INDEX.UNWILLING_FIREWOOD_PICKUP;
    ["Nouvelle quête : Des bonshommes, sur le champ"] = QG_YULE_INDEX.FILLING_THE_FIELD_PICKUP;
    ["Nouvelle quête : Un bonhomme de neige cassé ?"] = QG_YULE_INDEX.A_BROKEN_SNOWMAN_PICKUP;
    ["Nouvelle quête : Un esprit charitable"] = QG_YULE_INDEX.A_CHARITABLE_SPIRIT_PICKUP;
    ["Nouvelle quête : Le plus gros estomac du monde"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_PICKUP;
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_COMPLETED_QUEST_STRINGS[YULE] = {
    ["Terminé :\nGrand nettoyage\n"] = QG_YULE_INDEX.TIDYING_UP_END;
    ["Terminé :\nFestival de Yule (Quotidien)\n"] = QG_YULE_INDEX.YULE_FESTIVAL_DAILY_END;
    ["Terminé :\nCirculez\n"] = QG_YULE_INDEX.MOVING_THEM_OFF_END;
    ["Terminé :\nLes abominables bêtes des neiges\n"] = QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_END;
    ["Terminé :\nDes tonneaux presque vides\n"] = QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_END;
    ["Terminé :\nGaver les participants\n"] = QG_YULE_INDEX.STUFFING_THE_STUFFED_END;
    ["Terminé :\nLes fagots récalcitrants\n"] = QG_YULE_INDEX.UNWILLING_FIREWOOD_END;
    ["Terminé :\nUn bonhomme de neige cassé ?\n"] = QG_YULE_INDEX.A_BROKEN_SNOWMAN_END;
    ["Terminé :\nDes bonshommes, sur le champ\n"] = QG_YULE_INDEX.FILLING_THE_FIELD_END;
    ["Terminé :\nFroid mortel\n"] = QG_YULE_INDEX.COLD_AS_ICE_END;
    ["Terminé :\nMauvais tours\n"] = QG_YULE_INDEX.MAKING_MISCHIEF_END;
    ["Terminé :\nL'esprit de Yule\n"] = QG_YULE_INDEX.IN_THE_SPIRIT_OF_YULE_END;
    ["Terminé :\nUn esprit charitable\n"] = QG_YULE_INDEX.A_CHARITABLE_SPIRIT_END;
    ["Terminé :\nLe plus gros estomac du monde\n"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END;
    ["Terminé :\nLe plus gros estomac du monde (partie II)\n"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_2;
    ["Terminé :\nLe plus gros estomac du monde (partie III)\n"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_3;
    ["Terminé :\nLe plus gros estomac du monde (partie IV)\n"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_4;
    ["Terminé :\nLe plus gros estomac du monde (partie V)\n"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_5;
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_QUEST_OBJECTIVE_STRINGS[YULE] = {
    ["Barrett Patraque s'en va à contrecœur, ne sachant où aller"] = QG_YULE_INDEX.MOVING_THEM_OFF_BARRETTNOWELL; -- key:620872121:136263297
    ["Ted Fermeron vous lance un regard déçu, mais finit par s'en aller"] = QG_YULE_INDEX.MOVING_THEM_OFF_TEDIVES;
    ["Régine Latombe s'éloigne, l'air triste"] = QG_YULE_INDEX.MOVING_THEM_OFF_REGINAJUDSON;
    ["Jacques Latombe se dépêche, l'air consterné"] = QG_YULE_INDEX.MOVING_THEM_OFF_JACKJUDSON;
    ["Le visage de Bill Lacachette est rougi par le froid, mais il s'éloigne tristement du feu"] = QG_YULE_INDEX.MOVING_THEM_OFF_BILLHYDE;

    ["Vous avez tiré un feu d'artifice distrayant"] = QG_YULE_INDEX.MAKING_MISCHIEF_FIREWORKS;
    ["Vous avez fait les poches d'un visiteur fortuné (8/8)"] = QG_YULE_INDEX.MAKING_MISCHIEF_LOOT; -- key:620872989:22075075

    ["Assiettes sales ramassées (10/10)"] = QG_YULE_INDEX.TIDYING_UP_DISHES; -- key:620872029:136263297
    ["Liquides renversés nettoyés (10/10)"] = QG_YULE_INDEX.TIDYING_UP_SPILLS; -- key:620872029:136263299
    ["Déchets pestilentiels ramassés (10/10)"] = QG_YULE_INDEX.TIDYING_UP_GARBAGE; -- key:620872029:136263298

    ["Pains cuits (3/3)"] = QG_YULE_INDEX.STUFFING_THE_STUFFED_BREAD; -- key:620872025:136263300
    ["Vous avez évité la crise liée aux tonneaux vides"] = QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_AVERT;
    ["Brindille récupérée dans un buisson à proximité"] = QG_YULE_INDEX.A_BROKEN_SNOWMAN_STICK;
    ["Œufs ramassés (5/5)"] = QG_YULE_INDEX.STUFFING_THE_STUFFED_EGGS; -- key:620766239:136263297
    ["Fagots récalcitrants récupérés (9/9)"] = QG_YULE_INDEX.UNWILLING_FIREWOOD_COLLECT; -- key:620872026:262676277
    ["Temps glacial dispersé (4/4)"] = QG_YULE_INDEX.COLD_AS_ICE_DISPERSE; -- key:620889754:262676277
    ["Baies cueillies (5/5)"] = QG_YULE_INDEX.STUFFING_THE_STUFFED_BERRIES; -- key:620836600:136263297
    ["Joie apportée aux bêtes des neiges (3/3)"] = QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_CHEER; -- key:620890253:136263300
    ["Champignons ramassés (5/5)"] = QG_YULE_INDEX.STUFFING_THE_STUFFED_MUSHROOMS; -- key:620872025:136263299
    ["Charbon récupéré près du four des serviteurs"] = QG_YULE_INDEX.A_BROKEN_SNOWMAN_COAL;
    ["Votre générosité émeut beaucoup Régina Latombe"] = QG_YULE_INDEX.A_CHARITABLE_SPIRIT_REGINAJUDSON;
    ["Votre gentillesse émeut beaucoup Jacques Latombe"] = QG_YULE_INDEX.A_CHARITABLE_SPIRIT_JACKJUDSON;
    ["Votre bonne action émeut beaucoup Bill Lacachette"] = QG_YULE_INDEX.A_CHARITABLE_SPIRIT_BILLHYDE;
    ["Votre généreux cadeau émeut beaucoup Barrett Patraque"] = QG_YULE_INDEX.A_CHARITABLE_SPIRIT_BARRETTNOWELL;
    ["Votre cadeau émeut beaucoup Ted Fermeron"] = QG_YULE_INDEX.A_CHARITABLE_SPIRIT_TEDIVES;
    ["Que la goinfrade commence !"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_WAIT;
    ["Nourriture avalée au premier poste (5/5)"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION1; -- key:620872118:84765777
    ["Nourriture avalée au deuxième poste (5/5)"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION2; -- key:620872286:84765777
    ["Nourriture avalée au troisième poste (5/5)"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION3; -- key:620872322:84765777
    ["Nourriture avalée au quatrième poste (5/5)"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION4; -- key:620872323:84765777
    ["Nourriture avalée au cinquième poste (5/5)"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION5; -- key:620872325:84765777
};
