
_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CREDITS[YULE] = "\nThis guide created by Cube during the 2023 Yule.";

QG_YULE = _G.CubePlugins.FestivalBuddyII._QUICK_GUIDE[YULE];
QG_YULE[QG_YULE_INDEX.IN_THE_SPIRIT_OF_YULE_PICKUP].DISPLAY = function() return string.format("Take %s from %s in %s", HighlightQuest("In the Spirit of Yule"), HighlightNpc("Mara Sandydowns"), HighlightLocation("Winterhome")); end
QG_YULE[QG_YULE_INDEX.MOVING_THEM_OFF_PICKUP].DISPLAY = function() return TakeFrom("Moving Them Off", "Guard Kember"); end
QG_YULE[QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_PICKUP].DISPLAY = function() return TakeFrom("The Abominable Snow-beasts", "Guard Kember"); end
QG_YULE[QG_YULE_INDEX.MOVING_THEM_OFF_BARRETTNOWELL].DISPLAY = function() return ContinueWith("Moving Them Off", "Barrett Nowell (next to Mara Sandydowns)"); end
QG_YULE[QG_YULE_INDEX.MOVING_THEM_OFF_TEDIVES].DISPLAY = function() return ContinueWith("Moving Them Off", "Ted Ives (midway between Ona Kay and Daley Utteridge)"); end
QG_YULE[QG_YULE_INDEX.COLD_AS_ICE_PICKUP].DISPLAY = function() return TakeFrom("Cold as Ice", "Daley Utteridge"); end
QG_YULE[QG_YULE_INDEX.MAKING_MISCHIEF_PICKUP].DISPLAY = function() return TakeFrom("Making Mischief", "Gareth Rust"); end
QG_YULE[QG_YULE_INDEX.MOVING_THEM_OFF_REGINAJUDSON].DISPLAY = function() return ContinueWith("Moving Them Off", "Regina Judson") .. " (midway between Daley Utteridge and the Theatre)"; end
QG_YULE[QG_YULE_INDEX.MOVING_THEM_OFF_JACKJUDSON].DISPLAY = function() return ContinueWith("Moving Them Off", "Jack Judson") .. " (next to Theatre entrance)"; end
QG_YULE[QG_YULE_INDEX.MOVING_THEM_OFF_BILLHYDE].DISPLAY = function() return ContinueWith("Moving Them Off", "Bill Hyde") .. " (next to final Biggest Stomach table)"; end
QG_YULE[QG_YULE_INDEX.MAKING_MISCHIEF_FIREWORKS].DISPLAY = function() return Continue("Making Mischief", "Set off fireworks"); end
QG_YULE[QG_YULE_INDEX.MAKING_MISCHIEF_LOOT].DISPLAY = function() return Continue("Making Mischief", "Loot 8 distracted patrons"); end
QG_YULE[QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_PICKUP].DISPLAY = function() return TakeFrom("Empty Keg Emergency", "Basil Wyndham"); end
QG_YULE[QG_YULE_INDEX.TIDYING_UP_PICKUP].DISPLAY = function() return TakeFrom("Tidying Up", "Basil Wyndham"); end
QG_YULE[QG_YULE_INDEX.STUFFING_THE_STUFFED_PICKUP].DISPLAY = function() return TakeFrom("Stuffing the Stuffed", "Mabel Mitford"); end
QG_YULE[QG_YULE_INDEX.UNWILLING_FIREWOOD_PICKUP].DISPLAY = function() return TakeFrom("Unwilling Firewood", "Mabel Mitford"); end
QG_YULE[QG_YULE_INDEX.TIDYING_UP_DISHES].DISPLAY = function() return Continue("Tidying Up", "Pick up 10 dirty dishes"); end
QG_YULE[QG_YULE_INDEX.TIDYING_UP_SPILLS].DISPLAY = function() return Continue("Tidying Up", "Clean up 10 liquid spills"); end
QG_YULE[QG_YULE_INDEX.TIDYING_UP_GARBAGE].DISPLAY = function() return Continue("Tidying Up", "Clean up 10 reeking garbage"); end
QG_YULE[QG_YULE_INDEX.MAKING_MISCHIEF_END].DISPLAY = function() return TurnInTo("Making Mischief", "Gareth Rust"); end
QG_YULE[QG_YULE_INDEX.STUFFING_THE_STUFFED_BREAD].DISPLAY = function() return Continue("Stuffing the Stuffed", "Make 3 fresh breads"); end
QG_YULE[QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_AVERT].DISPLAY = function() return Continue("Empty Keg Emergency", "Pick up one of the kegs and deliver the replacement keg"); end
QG_YULE[QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_END].DISPLAY = function() return TurnInTo("Empty Keg Emergency", "Basil Wyndham"); end
QG_YULE[QG_YULE_INDEX.TIDYING_UP_END].DISPLAY = function() return string.format("Turn in %s to %s (if you already did %s, this can be delayed)", HighlightQuest("Tidying Up"), HighlightNpc("Basil Wyndham"), HighlightQuest("The Biggest Stomach of Them All")); end
QG_YULE[QG_YULE_INDEX.FILLING_THE_FIELD_PICKUP].DISPLAY = function() return TakeFrom("Filling the Field", "Virgil Greenfield"); end
QG_YULE[QG_YULE_INDEX.A_BROKEN_SNOWMAN_PICKUP].DISPLAY = function() return TakeFrom("A Broken Snowman?", "Virgil's Broken Snowman"); end
QG_YULE[QG_YULE_INDEX.A_BROKEN_SNOWMAN_STICK].DISPLAY = function() return Continue("A Broken Snowman?", "Gather a stick"); end
QG_YULE[QG_YULE_INDEX.STUFFING_THE_STUFFED_EGGS].DISPLAY = function() return Continue("Stuffing the Stuffed", "Collect 5 eggs"); end
QG_YULE[QG_YULE_INDEX.UNWILLING_FIREWOOD_COLLECT].DISPLAY = function() return Continue("Unwilling Firewood", "Collect 9 firewood"); end
QG_YULE[QG_YULE_INDEX.COLD_AS_ICE_DISPERSE].DISPLAY = function() return Continue("Cold as Ice", "Disperse 4 Wintry Weather"); end
QG_YULE[QG_YULE_INDEX.STUFFING_THE_STUFFED_BERRIES].DISPLAY = function() return Continue("Stuffing the Stuffed", "Collect 5 fresh winterberries"); end
QG_YULE[QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_CHEER].DISPLAY = function() return Continue("The Abominable Snow-beasts", "/cheer at snow-beasts 3 times"); end
QG_YULE[QG_YULE_INDEX.STUFFING_THE_STUFFED_MUSHROOMS].DISPLAY = function() return Continue("Stuffing the Stuffed", "Collect 5 pampered mushrooms"); end
QG_YULE[QG_YULE_INDEX.YULE_FESTIVAL_DAILY_END].DISPLAY = function() return TurnInTo("Yule Festival (Daily)", "Mara Sandydowns"); end
QG_YULE[QG_YULE_INDEX.MOVING_THEM_OFF_END].DISPLAY = function() return TurnInTo("Moving Them Off", "Guard Kember"); end
QG_YULE[QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_END].DISPLAY = function() return TurnInTo("The Abominable Snow-beasts", "Guard Kember"); end
QG_YULE[QG_YULE_INDEX.STUFFING_THE_STUFFED_END].DISPLAY = function() return TurnInTo("Stuffing the Stuffed", "Mabel Mitford"); end
QG_YULE[QG_YULE_INDEX.UNWILLING_FIREWOOD_END].DISPLAY = function() return TurnInTo("Unwilling Firewood", "Mabel Mitford"); end
QG_YULE[QG_YULE_INDEX.A_BROKEN_SNOWMAN_COAL].DISPLAY = function() return Continue("A Broken Snowman?", "Gather coal"); end
QG_YULE[QG_YULE_INDEX.A_BROKEN_SNOWMAN_END].DISPLAY = function() return string.format("Turn in %s to %s. (The giant version is at 12.67N, 95.21W)", HighlightQuest("A Broken Snowman?"), HighlightNpc("Snowpile")); end
QG_YULE[QG_YULE_INDEX.FILLING_THE_FIELD_END].DISPLAY = function() return TurnInTo("Filling the Field", "Virgil Greenfield"); end
QG_YULE[QG_YULE_INDEX.COLD_AS_ICE_END].DISPLAY = function() return TurnInTo("Cold as Ice", "Daley Utteridge"); end
QG_YULE[QG_YULE_INDEX.A_CHARITABLE_SPIRIT_PICKUP].DISPLAY = function() return TakeFrom("A Charitable Spirit", "Daley Utteridge"); end
QG_YULE[QG_YULE_INDEX.A_CHARITABLE_SPIRIT_REGINAJUDSON].DISPLAY = function() return ContinueWith("A Charitable Spirit", "Regina Judson") .. " (midway between Daley Utteridge and the Theatre)"; end
QG_YULE[QG_YULE_INDEX.A_CHARITABLE_SPIRIT_JACKJUDSON].DISPLAY = function() return ContinueWith("A Charitable Spirit", "Jack Judson") .. " (next to Theatre entrance)"; end
QG_YULE[QG_YULE_INDEX.A_CHARITABLE_SPIRIT_BILLHYDE].DISPLAY = function() return ContinueWith("A Charitable Spirit", "Bill Hyde") .. " (next to final Biggest Stomach table)"; end
QG_YULE[QG_YULE_INDEX.A_CHARITABLE_SPIRIT_BARRETTNOWELL].DISPLAY = function() return ContinueWith("A Charitable Spirit", "Barrett Nowell") .. " (next to Mara Sandydowns)"; end
QG_YULE[QG_YULE_INDEX.IN_THE_SPIRIT_OF_YULE_END].DISPLAY = function() return TurnInTo("In the Spirit of Yule", "Mara Sandydowns"); end
QG_YULE[QG_YULE_INDEX.A_CHARITABLE_SPIRIT_TEDIVES].DISPLAY = function() return ContinueWith("A Charitable Spirit", "Ted Ives") .. " (midway between Ona Kay and Daley Utteridge)"; end
QG_YULE[QG_YULE_INDEX.A_CHARITABLE_SPIRIT_END].DISPLAY = function() return TurnInTo("A Charitable Spirit", "Daley Utteridge"); end
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_PICKUP].DISPLAY = function() return TakeFrom("The Biggest Stomach of Them All", "Ona Kay"); end
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_WAIT].DISPLAY = function() return "Wait for the eating contest to begin. (Keep questing in Frostbluff)"; end
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION1].DISPLAY = function() return Continue("The Biggest Stomach of Them All", "Eat food at the first station"); end
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END].DISPLAY = function() return TurnInTo("The Biggest Stomach of Them All", "Ona Kay"); end
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION2].DISPLAY = function() return Continue("The Biggest Stomach of Them All (Part II)", "Eat food at the second station"); end
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_2].DISPLAY = function() return TurnInTo("The Biggest Stomach of Them All (Part II)", "Freddie Symonds"); end
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION3].DISPLAY = function() return Continue("The Biggest Stomach of Them All (Part III)", "Eat food at the third station"); end
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_3].DISPLAY = function() return TurnInTo("The Biggest Stomach of Them All (Part III)", "Jack Mitford"); end
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION4].DISPLAY = function() return Continue("The Biggest Stomach of Them All (Part IV)", "Eat food at the fourth station"); end
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_4].DISPLAY = function() return TurnInTo("The Biggest Stomach of Them All (Part IV)", "Nora Lewison"); end
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION5].DISPLAY = function() return Continue("The Biggest Stomach of Them All (Part V)", "Eat food at the fifth station"); end
QG_YULE[QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_5].DISPLAY = function() return TurnInTo("The Biggest Stomach of Them All (Part V)", "Ian Prudholm"); end

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_NEW_QUEST_STRINGS[YULE] = {
    ["New Quest: In the Spirit of Yule"] = QG_YULE_INDEX.IN_THE_SPIRIT_OF_YULE_PICKUP;
    ["New Quest: Moving Them Off"] = QG_YULE_INDEX.MOVING_THEM_OFF_PICKUP;
    ["New Quest: The Abominable Snow-beasts"] = QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_PICKUP;
    ["New Quest: Cold as Ice"] = QG_YULE_INDEX.COLD_AS_ICE_PICKUP;
    ["New Quest: Making Mischief"] = QG_YULE_INDEX.MAKING_MISCHIEF_PICKUP;
    ["New Quest: Empty Keg Emergency"] = QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_PICKUP;
    ["New Quest: Tidying Up"] = QG_YULE_INDEX.TIDYING_UP_PICKUP;
    ["New Quest: Stuffing the Stuffed"] = QG_YULE_INDEX.STUFFING_THE_STUFFED_PICKUP;
    ["New Quest: Unwilling Firewood"] = QG_YULE_INDEX.UNWILLING_FIREWOOD_PICKUP;
    ["New Quest: Filling The Field"] = QG_YULE_INDEX.FILLING_THE_FIELD_PICKUP;
    ["New Quest: A Broken Snowman?"] = QG_YULE_INDEX.A_BROKEN_SNOWMAN_PICKUP;
    ["New Quest: A Charitable Spirit"] = QG_YULE_INDEX.A_CHARITABLE_SPIRIT_PICKUP;
    ["New Quest: The Biggest Stomach of Them All"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_PICKUP;
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_COMPLETED_QUEST_STRINGS[YULE] = {
    ["Completed:\nTidying Up\n"] = QG_YULE_INDEX.TIDYING_UP_END;
    ["Completed:\nYule Festival (Daily)\n"] = QG_YULE_INDEX.YULE_FESTIVAL_DAILY_END;
    ["Completed:\nMoving Them Off\n"] = QG_YULE_INDEX.MOVING_THEM_OFF_END;
    ["Completed:\nThe Abominable Snow-beasts\n"] = QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_END;
    ["Completed:\nEmpty Keg Emergency\n"] = QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_END;
    ["Completed:\nStuffing the Stuffed\n"] = QG_YULE_INDEX.STUFFING_THE_STUFFED_END;
    ["Completed:\nUnwilling Firewood\n"] = QG_YULE_INDEX.UNWILLING_FIREWOOD_END;
    ["Completed:\nA Broken Snowman?\n"] = QG_YULE_INDEX.A_BROKEN_SNOWMAN_END;
    ["Completed:\nFilling The Field\n"] = QG_YULE_INDEX.FILLING_THE_FIELD_END;
    ["Completed:\nCold as Ice\n"] = QG_YULE_INDEX.COLD_AS_ICE_END;
    ["Completed:\nMaking Mischief\n"] = QG_YULE_INDEX.MAKING_MISCHIEF_END;
    ["Completed:\nIn the Spirit of Yule\n"] = QG_YULE_INDEX.IN_THE_SPIRIT_OF_YULE_END;
    ["Completed:\nA Charitable Spirit\n"] = QG_YULE_INDEX.A_CHARITABLE_SPIRIT_END;
    ["Completed:\nThe Biggest Stomach of Them All\n"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END;
    ["Completed:\nThe Biggest Stomach of Them All (Part II)\n"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_2;
    ["Completed:\nThe Biggest Stomach of Them All (Part III)\n"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_3;
    ["Completed:\nThe Biggest Stomach of Them All (Part IV)\n"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_4;
    ["Completed:\nThe Biggest Stomach of Them All (Part V)\n"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_END_5;
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_QUEST_OBJECTIVE_STRINGS[YULE] = {
    ["Barrett Nowell reluctantly moves along, unsure of where to go"] = QG_YULE_INDEX.MOVING_THEM_OFF_BARRETTNOWELL;
    ["Ted Ives gives you a disappointed look, but moves along"] = QG_YULE_INDEX.MOVING_THEM_OFF_TEDIVES;
    ["Regina Judson looks very sorrowful as she dashes away"] = QG_YULE_INDEX.MOVING_THEM_OFF_REGINAJUDSON;
    ["Jack Judson hurries away, looking most appalled"] = QG_YULE_INDEX.MOVING_THEM_OFF_JACKJUDSON;
    ["Bill Hyde's face is reddened by the cold, but he walks away from the fire sadly"] = QG_YULE_INDEX.MOVING_THEM_OFF_BILLHYDE;

    ["You have set off some distracting fireworks"] = QG_YULE_INDEX.MAKING_MISCHIEF_FIREWORKS;
    ["Looted a distracted patron (8/8)"] = QG_YULE_INDEX.MAKING_MISCHIEF_LOOT;

    ["Picked up dirty dishes (10/10)"] = QG_YULE_INDEX.TIDYING_UP_DISHES;
    ["Cleaned up liquid spills (10/10)"] = QG_YULE_INDEX.TIDYING_UP_SPILLS;
    ["Cleaned up reeking garbage (10/10)"] = QG_YULE_INDEX.TIDYING_UP_GARBAGE;

    ["Baked bread (3/3)"] = QG_YULE_INDEX.STUFFING_THE_STUFFED_BREAD;
    ["You have averted the empty keg crisis"] = QG_YULE_INDEX.EMPTY_KEG_EMERGENCY_AVERT;
    ["Gathered a stick from a nearby bush"] = QG_YULE_INDEX.A_BROKEN_SNOWMAN_STICK;
    ["Collected eggs (5/5)"] = QG_YULE_INDEX.STUFFING_THE_STUFFED_EGGS;
    ["Collected unwilling firewood (9/9)"] = QG_YULE_INDEX.UNWILLING_FIREWOOD_COLLECT;
    ["Dispersed Wintry Weather (4/4)"] = QG_YULE_INDEX.COLD_AS_ICE_DISPERSE;
    ["Collected berries (5/5)"] = QG_YULE_INDEX.STUFFING_THE_STUFFED_BERRIES;
    ["Brought cheer to the snow-beasts (3/3)"] = QG_YULE_INDEX.THE_ABOMINABLE_SNOW_BEASTS_CHEER;
    ["Collected mushrooms (5/5)"] = QG_YULE_INDEX.STUFFING_THE_STUFFED_MUSHROOMS;
    ["Gathered coal near the servants' oven"] = QG_YULE_INDEX.A_BROKEN_SNOWMAN_COAL;
    ["Regina Judson is moved by your generosity"] = QG_YULE_INDEX.A_CHARITABLE_SPIRIT_REGINAJUDSON;
    ["Jack Judson is moved by your kindness"] = QG_YULE_INDEX.A_CHARITABLE_SPIRIT_JACKJUDSON;
    ["Bill Hyde is moved by your good deed"] = QG_YULE_INDEX.A_CHARITABLE_SPIRIT_BILLHYDE;
    ["Barrett Nowell is moved by your generous gift"] = QG_YULE_INDEX.A_CHARITABLE_SPIRIT_BARRETTNOWELL;
    ["Ted Ives is moved by your gift"] = QG_YULE_INDEX.A_CHARITABLE_SPIRIT_TEDIVES;
    ["Let the stuffing begin!"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_WAIT;
    ["Ate food at the first station (5/5)"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION1;
    ["Ate food at the second station (5/5)"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION2;
    ["Ate food at the third station (5/5)"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION3;
    ["Ate food at the fourth station (5/5)"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION4;
    ["Ate food at the fifth station (5/5)"] = QG_YULE_INDEX.THE_BIGGEST_STOMACH_OF_THEM_ALL_STATION5;
};
