-- Midsummer Quest Indexes:

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_INDICIES[MIDSUMMER] = {};
QG_MIDSUMMER_INDEX = _G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_INDICIES[MIDSUMMER];

local index = 1;
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "IN_CELEBRATION_OF_MIDSUMMER_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "SOMETHING_FLORAL_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "TO_THE_LAST_DROP_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "WEDDING_SUPPLIES_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "WHAT_ALES_YOU_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "TASTY_MORSELS_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "ARRANGING_ARRANGEMENTS_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "FLORAL_CROWNS_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "AIDING_THE_STABLE_HANDS_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "AIDING_THE_STABLE_HANDS_BRUSH");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "AIDING_THE_STABLE_HANDS_APPLES");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "AIDING_THE_STABLE_HANDS_GROOM");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "AIDING_THE_STABLE_HANDS_FEED");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "AIDING_THE_STABLE_HANDS_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "FLORAL_CROWNS_COLLECT");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "FLORAL_CROWNS_CRAFT");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "ARTISTIC_DIRECTION_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "TOSS_A_COIN_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "TOSS_A_COIN_COMPLETE");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "WHAT_ALES_YOU_1");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "TO_THE_LAST_DROP_COMPLETE");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "TOSS_A_COIN_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "WHAT_ALES_YOU_2");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "ARTISTIC_DIRECTION_LEBADAR");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "GROWING_PAINS_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "UNHELPFUL_HOUNDS_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "UNHELPFUL_HOUNDS_CONTINUE");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "UNHELPFUL_HOUNDS_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "WEDDING_SUPPLIES_1");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "ARTISTIC_DIRECTION_POTTER");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "WEDDING_SUPPLIES_3");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "HONOURING_HEALERS_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "GROWING_PAINS_WATER");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "GROWING_PAINS_WEEDS");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "GROWING_PAINS_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "ARTISTIC_DIRECTION_CIRIEL");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "SWEET_TREATS_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "SWEET_TREATS_2");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "WEDDING_SUPPLIES_4");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "SWEET_TREATS_4");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "WEDDING_SUPPLIES_5");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "ARRANGING_ARRANGEMENTS_2");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "WHAT_ALES_YOU_3");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "SWEET_TREATS_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "ARTISTIC_DIRECTION_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "TASTY_MORSELS_COMPLETE");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "SOMETHING_MISPLACED_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "SOMETHING_MISPLACED_HOLLUR");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "SOMETHING_MISPLACED_POLLA");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "SOMETHING_MISPLACED_FROKI");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "SOMETHING_MISPLACED_DAENAR");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "SOMETHING_MISPLACED_ROBBO");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "SOMETHING_MISPLACED_GORD");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "SOMETHING_MISPLACED_COMPLETE");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "ARRANGING_ARRANGEMENTS_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "SOMETHING_MISPLACED_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "A_CURE_FOR_ALL_ILLS_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "A_CURE_FOR_ALL_ILLS_BOTTLES");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "A_CURE_FOR_ALL_ILLS_REVELLERS");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "A_CURE_FOR_ALL_ILLS_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "HONOURING_HEALERS_COMPLETE");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "SOMETHING_FLORAL_COMPLETE");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "LOVE_IS_IN_THE_AIR_PICKUP");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "LOVE_IS_IN_THE_AIR_COMPLETE");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "LOVE_IS_IN_THE_AIR_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "WHAT_ALES_YOU_4");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "IN_CELEBRATION_OF_MIDSUMMER_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "HONOURING_HEALERS_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "SOMETHING_FLORAL_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "TO_THE_LAST_DROP_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "WEDDING_SUPPLIES_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "WHAT_ALES_YOU_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "TASTY_MORSELS_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "FLORAL_CROWNS_END");
index = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, index, "RESET");

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CHAINS[MIDSUMMER] = {
    ["A_CURE_FOR_ALL_ILLS"] = {
        [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_BOTTLES] = true;
        [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_END] = true;
        [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_REVELLERS] = true;
    };

    ["AIDING_THE_STABLE_HANDS"] = {
        [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_APPLES] = true;
        [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_BRUSH] = true;
        [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_END] = true;
        [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_FEED] = true;
        [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_GROOM] = true;
        [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_PICKUP] = true;
    };

    ["ARRANGING_ARRANGEMENTS"] = {
        [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_2] = true;
        [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_END] = true;
        [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_PICKUP] = true;
    };

    ["ARTISTIC_DIRECTION"] = {
        [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_CIRIEL] = true;
        [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_END] = true;
        [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_LEBADAR] = true;
        [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_POTTER] = true;
    };

    ["FLORAL_CROWNS"] = {
        [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_COLLECT] = true;
        [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_CRAFT] = true;
        [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_END] = true;
        [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_PICKUP] = true;
    };

    ["GROWING_PAINS"] = {
        [QG_MIDSUMMER_INDEX.GROWING_PAINS_END] = true;
        [QG_MIDSUMMER_INDEX.GROWING_PAINS_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.GROWING_PAINS_WATER] = true;
        [QG_MIDSUMMER_INDEX.GROWING_PAINS_WEEDS] = true;
    };

    ["HONOURING_HEALERS"] = {
        [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_COMPLETE] = true;
        [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_END] = true;
        [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_PICKUP] = true;
    };

    ["IN_CELEBRATION_OF_MIDSUMMER"] = {
        [QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_END] = true;
        [QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_PICKUP] = true;
    };

    ["LOVE_IS_IN_THE_AIR"] = {
        [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_COMPLETE] = true;
        [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_END] = true;
        [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_PICKUP] = true;
    };

    ["SOMETHING_FLORAL"] = {
        [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_COMPLETE] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_END] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_PICKUP] = true;
    };

    ["SOMETHING_MISPLACED"] = {
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_COMPLETE] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_DAENAR] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_END] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_FROKI] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_GORD] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_HOLLUR] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_POLLA] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_ROBBO] = true;
    };

    ["SWEET_TREATS"] = {
        [QG_MIDSUMMER_INDEX.SWEET_TREATS_2] = true;
        [QG_MIDSUMMER_INDEX.SWEET_TREATS_4] = true;
        [QG_MIDSUMMER_INDEX.SWEET_TREATS_END] = true;
        [QG_MIDSUMMER_INDEX.SWEET_TREATS_PICKUP] = true;
    };

    ["TASTY_MORSELS"] = {
        [QG_MIDSUMMER_INDEX.TASTY_MORSELS_COMPLETE] = true;
        [QG_MIDSUMMER_INDEX.TASTY_MORSELS_END] = true;
        [QG_MIDSUMMER_INDEX.TASTY_MORSELS_PICKUP] = true;
    };

    ["TO_THE_LAST_DROP"] = {
        [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_COMPLETE] = true;
        [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_END] = true;
        [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_PICKUP] = true;
    };

    ["TOSS_A_COIN"] = {
        [QG_MIDSUMMER_INDEX.TOSS_A_COIN_COMPLETE] = true;
        [QG_MIDSUMMER_INDEX.TOSS_A_COIN_END] = true;
        [QG_MIDSUMMER_INDEX.TOSS_A_COIN_PICKUP] = true;
    };

    ["UNHELPFUL_HOUNDS"] = {
        [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_CONTINUE] = true;
        [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_END] = true;
        [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_PICKUP] = true;
    };

    ["WEDDING_SUPPLIES"] = {
        [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_1] = true;
        [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_3] = true;
        [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_4] = true;
        [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_5] = true;
        [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_END] = true;
        [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_PICKUP] = true;
    };

    ["WHAT_ALES_YOU"] = {
        [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_1] = true;
        [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_2] = true;
        [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_3] = true;
        [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_4] = true;
        [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_END] = true;
        [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_PICKUP] = true;
    };
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CHAIN_LOOKUP[MIDSUMMER] = {
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_BOTTLES] = "A_CURE_FOR_ALL_ILLS";
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_END] = "A_CURE_FOR_ALL_ILLS";
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_PICKUP] = "A_CURE_FOR_ALL_ILLS";
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_REVELLERS] = "A_CURE_FOR_ALL_ILLS";

    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_APPLES] = "AIDING_THE_STABLE_HANDS";
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_BRUSH] = "AIDING_THE_STABLE_HANDS";
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_END] = "AIDING_THE_STABLE_HANDS";
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_FEED] = "AIDING_THE_STABLE_HANDS";
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_GROOM] = "AIDING_THE_STABLE_HANDS";
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_PICKUP] = "AIDING_THE_STABLE_HANDS";

    [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_2] = "ARRANGING_ARRANGEMENTS";
    [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_END] = "ARRANGING_ARRANGEMENTS";
    [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_PICKUP] = "ARRANGING_ARRANGEMENTS";

    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_CIRIEL] = "ARTISTIC_DIRECTION";
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_END] = "ARTISTIC_DIRECTION";
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_LEBADAR] = "ARTISTIC_DIRECTION";
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_PICKUP] = "ARTISTIC_DIRECTION";
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_POTTER] = "ARTISTIC_DIRECTION";

    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_COLLECT] = "FLORAL_CROWNS";
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_CRAFT] = "FLORAL_CROWNS";
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_END] = "FLORAL_CROWNS";
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_PICKUP] = "FLORAL_CROWNS";

    [QG_MIDSUMMER_INDEX.GROWING_PAINS_END] = "GROWING_PAINS";
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_PICKUP] = "GROWING_PAINS";
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_WATER] = "GROWING_PAINS";
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_WEEDS] = "GROWING_PAINS";

    [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_COMPLETE] = "HONOURING_HEALERS";
    [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_END] = "HONOURING_HEALERS";
    [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_PICKUP] = "HONOURING_HEALERS";

    [QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_END] = "IN_CELEBRATION_OF_MIDSUMMER";
    [QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_PICKUP] = "IN_CELEBRATION_OF_MIDSUMMER";

    [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_COMPLETE] = "LOVE_IS_IN_THE_AIR";
    [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_END] = "LOVE_IS_IN_THE_AIR";
    [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_PICKUP] = "LOVE_IS_IN_THE_AIR";

    [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_COMPLETE] = "SOMETHING_FLORAL";
    [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_END] = "SOMETHING_FLORAL";
    [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_PICKUP] = "SOMETHING_FLORAL";

    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_COMPLETE] = "SOMETHING_MISPLACED";
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_DAENAR] = "SOMETHING_MISPLACED";
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_END] = "SOMETHING_MISPLACED";
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_FROKI] = "SOMETHING_MISPLACED";
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_GORD] = "SOMETHING_MISPLACED";
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_HOLLUR] = "SOMETHING_MISPLACED";
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_PICKUP] = "SOMETHING_MISPLACED";
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_POLLA] = "SOMETHING_MISPLACED";
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_ROBBO] = "SOMETHING_MISPLACED";

    [QG_MIDSUMMER_INDEX.SWEET_TREATS_2] = "SWEET_TREATS";
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_4] = "SWEET_TREATS";
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_END] = "SWEET_TREATS";
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_PICKUP] = "SWEET_TREATS";

    [QG_MIDSUMMER_INDEX.TASTY_MORSELS_COMPLETE] = "TASTY_MORSELS";
    [QG_MIDSUMMER_INDEX.TASTY_MORSELS_END] = "TASTY_MORSELS";
    [QG_MIDSUMMER_INDEX.TASTY_MORSELS_PICKUP] = "TASTY_MORSELS";

    [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_COMPLETE] = "TO_THE_LAST_DROP";
    [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_END] = "TO_THE_LAST_DROP";
    [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_PICKUP] = "TO_THE_LAST_DROP";

    [QG_MIDSUMMER_INDEX.TOSS_A_COIN_COMPLETE] = "TOSS_A_COIN";
    [QG_MIDSUMMER_INDEX.TOSS_A_COIN_END] = "TOSS_A_COIN";
    [QG_MIDSUMMER_INDEX.TOSS_A_COIN_PICKUP] = "TOSS_A_COIN";

    [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_CONTINUE] = "UNHELPFUL_HOUNDS";
    [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_END] = "UNHELPFUL_HOUNDS";
    [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_PICKUP] = "UNHELPFUL_HOUNDS";

    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_1] = "WEDDING_SUPPLIES";
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_3] = "WEDDING_SUPPLIES";
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_4] = "WEDDING_SUPPLIES";
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_5] = "WEDDING_SUPPLIES";
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_END] = "WEDDING_SUPPLIES";
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_PICKUP] = "WEDDING_SUPPLIES";

    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_1] = "WHAT_ALES_YOU";
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_2] = "WHAT_ALES_YOU";
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_3] = "WHAT_ALES_YOU";
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_4] = "WHAT_ALES_YOU";
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_END] = "WHAT_ALES_YOU";
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_PICKUP] = "WHAT_ALES_YOU";
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE[MIDSUMMER] = {
    [QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_PICKUP] = {
        ["CHAIN_BEGIN"] = "IN_CELEBRATION_OF_MIDSUMMER";
        ["TIMER_START"] = true;
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_PICKUP] = {
        ["CHAIN_BEGIN"] = "SOMETHING_FLORAL";
    };
    [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_PICKUP] = {
        ["CHAIN_BEGIN"] = "TO_THE_LAST_DROP";
    };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_PICKUP] = {
        ["CHAIN_BEGIN"] = "WEDDING_SUPPLIES";
    };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_PICKUP] = {
        ["CHAIN_BEGIN"] = "WHAT_ALES_YOU";
    };
    [QG_MIDSUMMER_INDEX.TASTY_MORSELS_PICKUP] = {
        ["CHAIN_BEGIN"] = "TASTY_MORSELS";
    };
    [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_PICKUP] = {
        ["CHAIN_BEGIN"] = "ARRANGING_ARRANGEMENTS";
    };
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_PICKUP] = {
        ["CHAIN_BEGIN"] = "FLORAL_CROWNS";
    };
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_PICKUP] = {
        ["CHAIN_BEGIN"] = "AIDING_THE_STABLE_HANDS";
    };
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_BRUSH] = {
    };
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_APPLES] = {
    };
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_GROOM] = {
    };
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_FEED] = {
    };
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_END] = {
        ["LOAD_QUEST"] = "FLORAL_CROWNS";
        ["CHAIN_END"] = "AIDING_THE_STABLE_HANDS";
    };
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_COLLECT] = {
    };
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_CRAFT] = {
    };
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_PICKUP] = {
        ["LOAD_QUEST"] = "TOSS_A_COIN";
        ["CHAIN_BEGIN"] = "ARTISTIC_DIRECTION";
    };
    [QG_MIDSUMMER_INDEX.TOSS_A_COIN_PICKUP] = {
        ["CHAIN_BEGIN"] = "TOSS_A_COIN";
    };
    [QG_MIDSUMMER_INDEX.TOSS_A_COIN_COMPLETE] = {
    };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_1] = {
        ["LOAD_QUEST"] = "TO_THE_LAST_DROP";
    };
    [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_COMPLETE] = {
        ["LOAD_QUEST"] = "TOSS_A_COIN";
    };
    [QG_MIDSUMMER_INDEX.TOSS_A_COIN_END] = {
        ["LOAD_QUEST"] = "WHAT_ALES_YOU";
        ["CHAIN_END"] = "TOSS_A_COIN";
    };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_2] = {
        ["LOAD_QUEST"] = "ARTISTIC_DIRECTION";
    };
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_LEBADAR] = {
    };
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_PICKUP] = {
        ["CHAIN_BEGIN"] = "GROWING_PAINS";
    };
    [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_PICKUP] = {
        ["CHAIN_BEGIN"] = "UNHELPFUL_HOUNDS";
    };
    [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_CONTINUE] = {
    };
    [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_END] = {
        ["LOAD_QUEST"] = "WEDDING_SUPPLIES";
        ["CHAIN_END"] = "UNHELPFUL_HOUNDS";
    };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_1] = {
        ["LOAD_QUEST"] = "ARTISTIC_DIRECTION";
    };
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_POTTER] = {
        ["LOAD_QUEST"] = "WEDDING_SUPPLIES";
    };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_3] = {
        ["LOAD_QUEST"] = "GROWING_PAINS";
    };
    [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_PICKUP] = {
        ["LOAD_QUEST"] = "GROWING_PAINS";
        ["CHAIN_BEGIN"] = "HONOURING_HEALERS";
    };
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_WATER] = {
    };
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_WEEDS] = {
    };
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_END] = {
        ["LOAD_QUEST"] = "ARTISTIC_DIRECTION";
        ["CHAIN_END"] = "GROWING_PAINS";
    };
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_CIRIEL] = {
    };
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_PICKUP] = {
        ["CHAIN_BEGIN"] = "SWEET_TREATS";
    };
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_2] = {
        ["LOAD_QUEST"] = "WEDDING_SUPPLIES";
    };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_4] = {
    };
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_4] = {
        ["LOAD_QUEST"] = "ARRANGING_ARRANGEMENTS";
    };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_5] = {
        ["LOAD_QUEST"] = "SWEET_TREATS";
    };
    [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_2] = {
        ["LOAD_QUEST"] = "WHAT_ALES_YOU";
    };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_3] = {
        ["LOAD_QUEST"] = "SWEET_TREATS";
    };
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_END] = {
        ["LOAD_QUEST"] = "ARTISTIC_DIRECTION";
        ["CHAIN_END"] = "SWEET_TREATS";
    };
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_END] = {
        ["LOAD_QUEST"] = "TASTY_MORSELS";
        ["CHAIN_END"] = "ARTISTIC_DIRECTION";
    };
    [QG_MIDSUMMER_INDEX.TASTY_MORSELS_COMPLETE] = {
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_PICKUP] = {
        ["CHAIN_BEGIN"] = "SOMETHING_MISPLACED";
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_HOLLUR] = {
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_POLLA] = {
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_FROKI] = {
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_DAENAR] = {
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_ROBBO] = {
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_GORD] = {
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_COMPLETE] = {
        ["LOAD_QUEST"] = "ARRANGING_ARRANGEMENTS";
        ["ALSO_COMPLETES"] = {
            [1] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_HOLLUR;
            [2] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_POLLA;
            [3] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_FROKI;
            [4] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_DAENAR;
            [5] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_ROBBO;
            [6] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_GORD;
        };
    };
    [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_END] = {
        ["LOAD_QUEST"] = "A_CURE_FOR_ALL_ILLS";
        ["CHAIN_END"] = "ARRANGING_ARRANGEMENTS";
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_END] = {
        ["LOAD_QUEST"] = "A_CURE_FOR_ALL_ILLS";
        ["CHAIN_END"] = "SOMETHING_MISPLACED";
    };
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_CURE_FOR_ALL_ILLS";
    };
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_BOTTLES] = {
    };
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_REVELLERS] = {
    };
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_END] = {
        ["LOAD_QUEST"] = "HONOURING_HEALERS";
        ["CHAIN_END"] = "A_CURE_FOR_ALL_ILLS";
    };
    [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_COMPLETE] = {
        ["LOAD_QUEST"] = "SOMETHING_FLORAL";
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_COMPLETE] = {
        ["LOAD_QUEST"] = "LOVE_IS_IN_THE_AIR";
    };
    [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_PICKUP] = {
        ["CHAIN_BEGIN"] = "LOVE_IS_IN_THE_AIR";
    };
    [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_COMPLETE] = {
    };
    [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_END] = {
        ["LOAD_QUEST"] = "WHAT_ALES_YOU";
        ["CHAIN_END"] = "LOVE_IS_IN_THE_AIR";
    };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_4] = {
        ["LOAD_QUEST"] = "IN_CELEBRATION_OF_MIDSUMMER";
    };
    [QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_END] = {
        ["LOAD_QUEST"] = "HONOURING_HEALERS";
        ["CHAIN_END"] = "IN_CELEBRATION_OF_MIDSUMMER";
    };
    [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_END] = {
        ["LOAD_QUEST"] = "SOMETHING_FLORAL";
        ["CHAIN_END"] = "HONOURING_HEALERS";
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_END] = {
        ["LOAD_QUEST"] = "TO_THE_LAST_DROP";
        ["CHAIN_END"] = "SOMETHING_FLORAL";
    };
    [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_END] = {
        ["LOAD_QUEST"] = "WEDDING_SUPPLIES";
        ["CHAIN_END"] = "TO_THE_LAST_DROP";
    };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_END] = {
        ["LOAD_QUEST"] = "WHAT_ALES_YOU";
        ["CHAIN_END"] = "WEDDING_SUPPLIES";
    };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_END] = {
        ["LOAD_QUEST"] = "TASTY_MORSELS";
        ["CHAIN_END"] = "WHAT_ALES_YOU";
    };
    [QG_MIDSUMMER_INDEX.TASTY_MORSELS_END] = {
        ["LOAD_QUEST"] = "FLORAL_CROWNS";
        ["CHAIN_END"] = "TASTY_MORSELS";
    };
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_END] = {
        ["CHAIN_END"] = "FLORAL_CROWNS";
        ["TIMER_STOP"] = true;
    };
};

if (CLIENTLANG == "FRENCH") then
    import "CubePlugins.FestivalBuddyII.QuickGuides.Midsummer.QuickGuideStrings_MidsummerFR";
elseif (CLIENTLANG == "GERMAN") then
    import "CubePlugins.FestivalBuddyII.QuickGuides.Midsummer.QuickGuideStrings_MidsummerDE";
else
    import "CubePlugins.FestivalBuddyII.QuickGuides.Midsummer.QuickGuideStrings_MidsummerEN";
end