
_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CREDITS[MIDSUMMER] = "\nThis guide is based on LilRedHead's excellent LOTRO Midsummer Festival - Quick Guide at https://lifebeyondtheshire.com/lotro-midsummer-festival-quick-guide/. Thank you LRH!";

QG_MIDSUMMER = _G.CubePlugins.FestivalBuddyII._QUICK_GUIDE[MIDSUMMER];
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_PICKUP].DISPLAY = "Take 'En célébration du Solstice d'été' from Faeleth outside <rgb=#ffc000>City Stables</rgb>";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_PICKUP].DISPLAY = "Take 'Comme une fleur' from Merilien on the Citadel";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_PICKUP].DISPLAY = "Take 'Jusqu'à la dernière goutte' from Merilien";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_PICKUP].DISPLAY = "Take 'Fournitures de mariage' from Merilien";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_PICKUP].DISPLAY = "Take 'Pas de la petite bière' from Merilien";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TASTY_MORSELS_PICKUP].DISPLAY = "Take 'Amuse-bouche savoureux' from Othnoron on the Citadel";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_PICKUP].DISPLAY = "Take 'Dispositions d'arrangements' from Florist on the Citadel";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.FLORAL_CROWNS_PICKUP].DISPLAY = "Take 'Couronnes florales' from Florist";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_PICKUP].DISPLAY = "Take 'L'aide aux palefreniers' from Loborís in City Stables";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_BRUSH].DISPLAY = "L'aide aux palefreniers: Take brush from Equipment Crate";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_APPLES].DISPLAY = "L'aide aux palefreniers: Take apples from Crate of Apples";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_GROOM].DISPLAY = "L'aide aux palefreniers: Groom 3 horses";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_FEED].DISPLAY = "L'aide aux palefreniers: Feed 3 horses";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_END].DISPLAY = "Turn in 'L'aide aux palefreniers' to Loborís in City Stables";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.FLORAL_CROWNS_COLLECT].DISPLAY = "Couronnes florales: Continue quest with Florist's Daughter, collect 10 summer blossoms";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.FLORAL_CROWNS_CRAFT].DISPLAY = "Couronnes florales: Continue quest with Florist's Daughter, craft floral crown. [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_PICKUP].DISPLAY = "Take stable-master to <rgb=#ffc000>Niveau des soldats</rgb>, Take 'Direction artistique' from Borlach";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TOSS_A_COIN_PICKUP].DISPLAY = "Go south/left to Splintered Shield, Take 'Une petite pièce' from Ulthir upstairs";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TOSS_A_COIN_COMPLETE].DISPLAY = "Une petite pièce: Toss coins to 6 noisy minstrels.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_1].DISPLAY = "Pas de la petite bière: Get Barrel of Ale in The Splintered Shield.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_COMPLETE].DISPLAY = "Jusqu'à la dernière goutte: Take correct Barrel of Wine in The Splintered Shield.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TOSS_A_COIN_END].DISPLAY = "Turn in 'Une petite pièce' to Ulthir upstairs";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_2].DISPLAY = "Go south to Mûmak and Keep for 2nd 'Pas de la petite bière' Barrel, next to mûmak";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_LEBADAR].DISPLAY = "[Milestone] Take stable-master to <rgb=#ffc000>Niveau des artisans</rgb>. At bottom of ramp, continue 'Direction artistique' with Lebadar";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.GROWING_PAINS_PICKUP].DISPLAY = "Take 'Jardinier en herbe' from Lebadar";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_PICKUP].DISPLAY = "Take 'Chiens peu dociles' from Worried Woman in the square";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_CONTINUE].DISPLAY = "Chiens peu dociles: Find the missing ring";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_END].DISPLAY = "Turn in 'Chiens peu dociles' to Worried Woman";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_1].DISPLAY = "Ride up ramp, turn right, grab fournitures de mariage";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_POTTER].DISPLAY = "Continue 'Direction artistique' with Potter";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_3].DISPLAY = "Go into House of Craft, grab two more fournitures de mariage";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.HONOURING_HEALERS_PICKUP].DISPLAY = "Take 'L'hommage aux soignants' from the Postmaster";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.GROWING_PAINS_WATER].DISPLAY = "'Jardinier en herbe' (In garden at north end): Water 4 bushes";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.GROWING_PAINS_WEEDS].DISPLAY = "'Jardinier en herbe': Pull out 5 weeds";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.GROWING_PAINS_END].DISPLAY = "[Milestone] Take stable-master to <rgb=#ffc000>Niveau des artisans</rgb>. At bottom of ramp, turn in 'Jardinier en herbe'";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_CIRIEL].DISPLAY = "Ride up ramp, take stable-master to <rgb=#ffc000>Niveau des joueurs</rgb>. At bottom of ramp, continue 'Direction artistique' with Ciriel.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SWEET_TREATS_PICKUP].DISPLAY = "Take 'La fête pour tout le monde' from Ciriel";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SWEET_TREATS_2].DISPLAY = "Find the two guards to the north of Ciriel, continue 'La fête pour tout le monde' with each.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_4].DISPLAY = "Grab fournitures de mariage around the corner of Ciriel.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SWEET_TREATS_4].DISPLAY = "Find the two guards to the south of Ciriel, continue 'La fête pour tout le monde' with each.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_5].DISPLAY = "Grab final fournitures de mariage between two south guards.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_2].DISPLAY = "Go to Merry Swan, place two floral arrangements on stage for 'Dispositions d'arrangements'.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_3].DISPLAY = "Pas de la petite bière: Get Barrel of Ale in The Merry Swan.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SWEET_TREATS_END].DISPLAY = "Turn in 'La fête pour tout le monde' to Ciriel";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_END].DISPLAY = "Go up ramp, take stable-master to <rgb=#ffc000>Niveau des soldats</rgb>, turn in 'Direction artistique' to Borlach of Rimmon.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TASTY_MORSELS_COMPLETE].DISPLAY = "Take stable-master to <rgb=#ffc000>Niveau des joueurs</rgb>. Continue 'Amuse-bouche savoureux' with five loftier citizens. [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_PICKUP].DISPLAY = "Go to Blue Theater. Pick up 'Panique au Théâtre Bleu' from Duillam.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_HOLLUR].DISPLAY = "Find Hollur [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_POLLA].DISPLAY = "Find Polla [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_FROKI].DISPLAY = "Find Fróki [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_DAENAR].DISPLAY = "Find Daenar [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_ROBBO].DISPLAY = "Find Robbo [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_GORD].DISPLAY = "Find Gord [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_COMPLETE].DISPLAY = "Continue 'Panique au Théâtre Bleu' with Hollur, Polla, Fróki, Gord, Robbo, and Daenar.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_END].DISPLAY = "In the Blue Theater, place three floral arrangements on stage for 'Dispositions d'arrangements'.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_END].DISPLAY = "Turn in 'Panique au Théâtre Bleu' to Duillam";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_PICKUP].DISPLAY = "[Milestone] Take stable-master to <rgb=#ffc000>Hautes Écuries</rgb>, go to Houses of Healing, High Hall, and take 'Un remède pour tous les maux' from Ioreth.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_BOTTLES].DISPLAY = "Un remède pour tous les maux: Dispose of 10 half-emptied bottles";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_REVELLERS].DISPLAY = "Un remède pour tous les maux: Remove 6 noisy revellers [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_END].DISPLAY = "Turn in 'Un remède pour tous les maux' to Ioreth";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.HONOURING_HEALERS_COMPLETE].DISPLAY = "Go to Houses of Healing, House of Remedies and continue 'L'hommage aux soignants' with 6 Healers.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_COMPLETE].DISPLAY = "Take ramp down to <rgb=#ffc000>Niveau des sages</rgb>, go to Houses of Lore on the right, and place 6 floral arrangements for 'Comme une fleur'.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_PICKUP].DISPLAY = "Take 'Vraie romance' from Colladan.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_COMPLETE].DISPLAY = "Vraie romance: Catch 6 wayward verses";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_END].DISPLAY = "Turn in 'Vraie romance' to Colladan";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_4].DISPLAY = "Exit Houses of Lore, turn right and go to The Thirsty Seer. Go forward, then right. Get Barrel of Ale for 'Pas de la petite bière'.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_END].DISPLAY = "[Milestone] Turn in 'En célébration du Solstice d'été' to Faeleth.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.HONOURING_HEALERS_END].DISPLAY = "Take stable-master to <rgb=#ffc000>Niveau des artisans</rgb>. Enter House of Craft. Turn in 'L'hommage aux soignants' to Postmaster.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_END].DISPLAY = "Take stable-master to <rgb=#ffc000>Hautes Écuries</rgb>. Run to square on the Citadel. Turn in 'Comme une fleur' to Merilien.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_END].DISPLAY = "Turn in 'Jusqu'à la dernière goutte' to Merilien.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_END].DISPLAY = "Turn in 'Fournitures de mariage' to Merilien.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_END].DISPLAY = "Turn in 'Pas de la petite bière' to Merilien.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TASTY_MORSELS_END].DISPLAY = "Turn in 'Amuse-bouche savoureux' to Othnoron.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.FLORAL_CROWNS_END].DISPLAY = "Turn in 'Couronnes florales' to Florist.";

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_NEW_QUEST_STRINGS[MIDSUMMER] = {
    ["Nouvelle quête : En célébration du Solstice d'été"] = QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_PICKUP;
    ["Nouvelle quête : Comme une fleur"] = QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_PICKUP;
    ["Nouvelle quête : Jusqu'à la dernière goutte"] = QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_PICKUP;
    ["Nouvelle quête : Fournitures de mariage"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_PICKUP;
    ["Nouvelle quête : Pas de la petite bière"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_PICKUP;
    ["Nouvelle quête : Amuse-bouche savoureux"] = QG_MIDSUMMER_INDEX.TASTY_MORSELS_PICKUP;
    ["Nouvelle quête : Dispositions d'arrangements"] = QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_PICKUP;
    ["Nouvelle quête : Couronnes florales"] = QG_MIDSUMMER_INDEX.FLORAL_CROWNS_PICKUP;
    ["Nouvelle quête : L'aide aux palefreniers"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_PICKUP;
    ["Nouvelle quête : Direction artistique"] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_PICKUP;
    ["Nouvelle quête : Une petite pièce"] = QG_MIDSUMMER_INDEX.TOSS_A_COIN_PICKUP;
    ["Nouvelle quête : Jardinier en herbe"] = QG_MIDSUMMER_INDEX.GROWING_PAINS_PICKUP;
    ["Nouvelle quête : Chiens peu dociles"] = QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_PICKUP;
    ["Nouvelle quête : L'hommage aux soignants"] = QG_MIDSUMMER_INDEX.HONOURING_HEALERS_PICKUP;
    ["Nouvelle quête : La fête pour tout le monde"] = QG_MIDSUMMER_INDEX.SWEET_TREATS_PICKUP;
    ["Nouvelle quête : Panique au Théâtre Bleu"] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_PICKUP;
    ["Nouvelle quête : Un remède pour tous les maux"] = QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_PICKUP;
    ["Nouvelle quête : Vraie romance"] = QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_PICKUP;
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_COMPLETED_QUEST_STRINGS[MIDSUMMER] = {
    ["Terminé :\nL'aide aux palefreniers\n"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_END;
    ["Terminé :\nUne petite pièce\n"] = QG_MIDSUMMER_INDEX.TOSS_A_COIN_END;
    ["Terminé :\nChiens peu dociles\n"] = QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_END;
    ["Terminé :\nJardinier en herbe\n"] = QG_MIDSUMMER_INDEX.GROWING_PAINS_END;
    ["Terminé :\nLa fête pour tout le monde\n"] = QG_MIDSUMMER_INDEX.SWEET_TREATS_END;
    ["Terminé :\nDirection artistique\n"] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_END;
    ["Terminé :\nPanique au Théâtre Bleu\n"] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_END;
    ["Terminé :\nUn remède pour tous les maux\n"] = QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_END;
    ["Terminé :\nVraie romance\n"] = QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_END;
    ["Terminé :\nEn célébration du Solstice d'été\n"] = QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_END;
    ["Terminé :\nL'hommage aux soignants\n"] = QG_MIDSUMMER_INDEX.HONOURING_HEALERS_END;
    ["Terminé :\nComme une fleur\n"] = QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_END;
    ["Terminé :\nJusqu'à la dernière goutte\n"] = QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_END;
    ["Terminé :\nFournitures de mariage\n"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_END;
    ["Terminé :\nPas de la petite bière\n"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_END;
    ["Terminé :\nAmuse-bouche savoureux\n"] = QG_MIDSUMMER_INDEX.TASTY_MORSELS_END;
    ["Terminé :\nCouronnes florales\n"] = QG_MIDSUMMER_INDEX.FLORAL_CROWNS_END;
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_QUEST_OBJECTIVE_STRINGS[MIDSUMMER] = {
    ["Vous avez trouvé une étrille"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_BRUSH;
    ["Pommes récupérées"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_APPLES;
    ["Chevaux pansés (3/3)"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_GROOM;
    ["Cheval nourri (3/3)"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_FEED;
    ["Bourgeons d'été cueillis (10/10)"] = QG_MIDSUMMER_INDEX.FLORAL_CROWNS_COLLECT;
    ["Pièce lancée à un ménestrel bruyant (6/6)"] = QG_MIDSUMMER_INDEX.TOSS_A_COIN_COMPLETE;
    ["Tonneaux de bière récupérés (1/4)"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_1;
    ["Bon tonneau de vin ramassé"] = QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_COMPLETE;
    ["Tonneaux de bière récupérés (2/4)"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_2;
    ["Fleurs obtenues"] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_LEBADAR;
    ["Vous avez trouvé l'anneau !"] = QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_CONTINUE;
    ["Caisses de matériel de mariage récupérées (1/5)"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_1;
    ["Argile obtenue"] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_POTTER;
    ["Caisses de matériel de mariage récupérées (3/5)"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_3;
    ["Buissons arrosés (4/4)"] = QG_MIDSUMMER_INDEX.GROWING_PAINS_WATER;
    ["Mauvaises herbes arrachées (5/5)"] = QG_MIDSUMMER_INDEX.GROWING_PAINS_WEEDS;
    ["Morceau de charbon obtenu"] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_CIRIEL;
    ["Pâtisseries livrées (2/4)"] = QG_MIDSUMMER_INDEX.SWEET_TREATS_2;
    ["Caisses de matériel de mariage récupérées (4/5)"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_4;
    ["Pâtisseries livrées (4/4)"] = QG_MIDSUMMER_INDEX.SWEET_TREATS_4;
    ["Caisses de matériel de mariage récupérées (5/5)"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_5;
    ["Arrangements floraux disposés (2/5)"] = QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_2;
    ["Tonneaux de bière récupérés (3/4)"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_3;
    ["Diriger les Têtes Couvertes de manière à ce qu'elles se retrouvent en coulisse du Théâtre Bleu (6/6)"] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_COMPLETE;
    ["Arrangements floraux disposés (5/5)"] = QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_END;
    ["Bouteilles à moitié vides débarrassées de la Haute salle (10/10)"] = QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_BOTTLES;
    ["Mots de remerciement remis (6/6)"] = QG_MIDSUMMER_INDEX.HONOURING_HEALERS_COMPLETE;
    ["Arrangements floraux disposés (6/6)"] = QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_COMPLETE;
    ["Vers égarés retrouvés (6/6)"] = QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_COMPLETE;
    ["Tonneaux de bière récupérés (4/4)"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_4;
    --No count: 'Le convive ne dit rien, mais repart d'un air revêche', need it 6 times.
};
