
_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CREDITS[MIDSUMMER] = "\nThis guide is based on LilRedHead's excellent LOTRO Midsummer Festival - Quick Guide at https://lifebeyondtheshire.com/lotro-midsummer-festival-quick-guide/. Thank you LRH!";

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE[MIDSUMMER] = {
    [QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_PICKUP] = { ["DISPLAY"] = "Take 'Zur Feier von Mittsommer' from Faeleth outside <rgb=#ffc000>City Stables</rgb>"; ["CHAIN_BEGIN"] = "IN_CELEBRATION_OF_MIDSUMMER"; };
    [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_PICKUP] = { ["DISPLAY"] = "Take 'Etwas blumig' from Merilien on the Citadel"; ["CHAIN_BEGIN"] = "SOMETHING_FLORAL"; };
    [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_PICKUP] = { ["DISPLAY"] = "Take 'Bis zum letzten Tropfen' from Merilien"; ["CHAIN_BEGIN"] = "TO_THE_LAST_DROP"; };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_PICKUP] = { ["DISPLAY"] = "Take 'Hochzeitsmaterialien' from Merilien"; ["CHAIN_BEGIN"] = "WEDDING_SUPPLIES"; };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_PICKUP] = { ["DISPLAY"] = "Take 'Die Bier-Jahreszeiten' from Merilien"; ["CHAIN_BEGIN"] = "WHAT_ALES_YOU"; };
    [QG_MIDSUMMER_INDEX.TASTY_MORSELS_PICKUP] = { ["DISPLAY"] = "Take 'Köstliche Häppchen' from Othnoron on the Citadel"; ["CHAIN_BEGIN"] = "TASTY_MORSELS"; };
    [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_PICKUP] = { ["DISPLAY"] = "Take 'Schmuck für die Stadt' from Florist on the Citadel"; ["CHAIN_BEGIN"] = "ARRANGING_ARRANGEMENTS"; };
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_PICKUP] = { ["DISPLAY"] = "Take 'Blumenkronen' from Florist"; ["CHAIN_BEGIN"] = "FLORAL_CROWNS"; };
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_PICKUP] = { ["DISPLAY"] = "Take 'Hilfe für die Stallhelfer' from Loborís in City Stables"; ["CHAIN_BEGIN"] = "AIDING_THE_STABLE_HANDS"; };
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_BRUSH] = { ["DISPLAY"] = "Hilfe für die Stallhelfer: Take brush from Equipment Crate"; };
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_APPLES] = { ["DISPLAY"] = "Hilfe für die Stallhelfer: Take apples from Crate of Apples"; };
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_GROOM] = { ["DISPLAY"] = "Hilfe für die Stallhelfer: Groom 3 horses"};
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_FEED] = { ["DISPLAY"] = "Hilfe für die Stallhelfer: Feed 3 horses"};
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_END] = { ["DISPLAY"] = "Turn in 'Hilfe für die Stallhelfer' to Loborís in City Stables"; ["LOAD_QUEST"] = "FLORAL_CROWNS"; ["CHAIN_END"] = "AIDING_THE_STABLE_HANDS"; };
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_COLLECT] = { ["DISPLAY"] = "Blumenkronen: Continue quest with Florist's Daughter, collect 10 summer blossoms"; };
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_CRAFT] = { ["DISPLAY"] = "Blumenkronen: Continue quest with Florist's Daughter, craft floral crown. [Check manually]"; };
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_PICKUP] = { ["DISPLAY"] = "Take stable-master to <rgb=#ffc000>Soldatenring</rgb>, Take 'Richtungsweisende Kunst' from Borlach"; ["LOAD_QUEST"] = "TOSS_A_COIN"; ["CHAIN_BEGIN"] = "ARTISTIC_DIRECTION"; };
    [QG_MIDSUMMER_INDEX.TOSS_A_COIN_PICKUP] = { ["DISPLAY"] = "Go south/left to Splintered Shield, Take 'Münzwurf' from Ulthir upstairs"; ["CHAIN_BEGIN"] = "TOSS_A_COIN"; };
    [QG_MIDSUMMER_INDEX.TOSS_A_COIN_COMPLETE] = { ["DISPLAY"] = "Münzwurf: Toss coins to 6 noisy minstrels."; };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_1] = { ["DISPLAY"] = "Die Bier-Jahreszeiten: Get Barrel of Ale in The Splintered Shield."; ["LOAD_QUEST"] = "TO_THE_LAST_DROP"; };
    [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_COMPLETE] = { ["DISPLAY"] = "Bis zum letzten Tropfen: Take correct Barrel of Wine in The Splintered Shield."; ["LOAD_QUEST"] = "TOSS_A_COIN"; };
    [QG_MIDSUMMER_INDEX.TOSS_A_COIN_END] = { ["DISPLAY"] = "Turn in 'Münzwurf' to Ulthir upstairs"; ["LOAD_QUEST"] = "WHAT_ALES_YOU"; ["CHAIN_END"] = "TOSS_A_COIN"; };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_2] = { ["DISPLAY"] = "Go south to Mûmak and Keep for 2nd 'Die Bier-Jahreszeiten' Barrel, next to mûmak"; ["LOAD_QUEST"] = "ARTISTIC_DIRECTION"; };
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_LEBADAR] = { ["DISPLAY"] = "[Milestone] Take stable-master to <rgb=#ffc000>Handwerkerring</rgb>. At bottom of ramp, continue 'Richtungsweisende Kunst' with Lebadar"; }; -- too long
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_PICKUP] = { ["DISPLAY"] = "Take 'Wachstumsschmerzen' from Lebadar"; ["CHAIN_BEGIN"] = "GROWING_PAINS"; };
    [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_PICKUP] = { ["DISPLAY"] = "Take 'Unnütze Hunde' from Worried Woman in the square"; ["CHAIN_BEGIN"] = "UNHELPFUL_HOUNDS"; };
    [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_CONTINUE] = { ["DISPLAY"] = "Unnütze Hunde: Find the missing ring"; };
    [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_END] = { ["DISPLAY"] = "Turn in 'Unnütze Hunde' to Worried Woman"; ["LOAD_QUEST"] = "WEDDING_SUPPLIES"; ["CHAIN_END"] = "UNHELPFUL_HOUNDS"; };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_1] = { ["DISPLAY"] = "Ride up ramp, turn right, grab Hochzeitsmaterialien"; ["LOAD_QUEST"] = "ARTISTIC_DIRECTION"; };
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_POTTER] = { ["DISPLAY"] = "Continue 'Richtungsweisende Kunst' with Potter"; ["LOAD_QUEST"] = "WEDDING_SUPPLIES"; };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_3] = { ["DISPLAY"] = "Go into House of Craft, grab two more Hochzeitsmaterialien"; ["LOAD_QUEST"] = "GROWING_PAINS"; };
    [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_PICKUP] = { ["DISPLAY"] = "Take 'Ein Dank an die Heiler' from the Postmaster"; ["LOAD_QUEST"] = "GROWING_PAINS"; ["CHAIN_BEGIN"] = "HONOURING_HEALERS"; };
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_WATER] = { ["DISPLAY"] = "'Wachstumsschmerzen' (In garden at north end): Water 4 bushes"; };
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_WEEDS] = { ["DISPLAY"] = "'Wachstumsschmerzen': Pull out 5 weeds"; };
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_END] = { ["DISPLAY"] = "[Milestone] Take stable-master to <rgb=#ffc000>Handwerkerring</rgb>. At bottom of ramp, turn in 'Wachstumsschmerzen'"; ["LOAD_QUEST"] = "ARTISTIC_DIRECTION"; ["CHAIN_END"] = "GROWING_PAINS"; };
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_CIRIEL] = { ["DISPLAY"] = "Ride up ramp, take stable-master to <rgb=#ffc000>Spielerring</rgb>. At bottom of ramp, continue 'Richtungsweisende Kunst' with Ciriel."; };
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_PICKUP] = { ["DISPLAY"] = "Take 'Süße Grüße' from Ciriel"; ["CHAIN_BEGIN"] = "SWEET_TREATS"; };
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_2] = { ["DISPLAY"] = "Find the two guards to the north of Ciriel, continue 'Süße Grüße' with each."; ["LOAD_QUEST"] = "WEDDING_SUPPLIES"; };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_4] = { ["DISPLAY"] = "Grab Hochzeitsmaterialien around the corner of Ciriel."; };
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_4] = { ["DISPLAY"] = "Find the two guards to the south of Ciriel, continue 'Süße Grüße' with each."; ["LOAD_QUEST"] = "ARRANGING_ARRANGEMENTS"; };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_5] = { ["DISPLAY"] = "Grab final Hochzeitsmaterialien between two south guards.";  ["LOAD_QUEST"] = "SWEET_TREATS"; };
    [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_2] = { ["DISPLAY"] = "Go to Merry Swan, place two floral arrangements on stage for 'Schmuck für die Stadt'."; ["LOAD_QUEST"] = "WHAT_ALES_YOU"; };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_3] = { ["DISPLAY"] = "Die Bier-Jahreszeiten: Get Barrel of Ale in The Merry Swan."; ["LOAD_QUEST"] = "SWEET_TREATS"; };
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_END] = { ["DISPLAY"] = "Turn in 'Süße Grüße' to Ciriel"; ["LOAD_QUEST"] = "ARTISTIC_DIRECTION"; ["CHAIN_END"] = "SWEET_TREATS"; };
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_END] = { ["DISPLAY"] = "Go up ramp, take stable-master to <rgb=#ffc000>Soldatenring</rgb>, turn in 'Richtungsweisende Kunst' to Borlach of Rimmon."; ["LOAD_QUEST"] = "TASTY_MORSELS"; ["CHAIN_END"] = "ARTISTIC_DIRECTION"; };
    [QG_MIDSUMMER_INDEX.TASTY_MORSELS_COMPLETE] = { ["DISPLAY"] = "Take stable-master to <rgb=#ffc000>Spielerring</rgb>. Continue 'Köstliche Häppchen' with five loftier citizens. [Check manually]"; };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_PICKUP] = { ["DISPLAY"] = "Go to Blue Theater. Pick up 'Etwas Verlegtes, etwas Blaues' from Duillam."; ["CHAIN_BEGIN"] = "SOMETHING_MISPLACED"; };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_HOLLUR] = { ["DISPLAY"] = "Find Hollur [Check manually]"; };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_POLLA] = { ["DISPLAY"] = "Find Polla [Check manually]"; };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_FROKI] = { ["DISPLAY"] = "Find Fróki [Check manually]"; };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_DAENAR] = { ["DISPLAY"] = "Find Daenar [Check manually]"; };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_ROBBO] = { ["DISPLAY"] = "Find Robbo [Check manually]"; };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_GORD] = { ["DISPLAY"] = "Find Gord [Check manually]"; };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_COMPLETE] = { ["DISPLAY"] = "Continue 'Etwas Verlegtes, etwas Blaues' with Hollur, Polla, Fróki, Gord, Robbo, and Daenar."; ["LOAD_QUEST"] = "ARRANGING_ARRANGEMENTS"; ["ALSO_COMPLETES"] = { [1] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_HOLLUR; [2] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_POLLA; [3] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_FROKI; [4] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_DAENAR; [5] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_ROBBO; [6] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_GORD; }; };
    [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_END] = { ["DISPLAY"] = "In the Blue Theater, place three floral arrangements on stage for 'Schmuck für die Stadt'."; ["LOAD_QUEST"] = "SOMETHING_MISPLACED"; ["CHAIN_END"] = "ARRANGING_ARRANGEMENTS"; };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_END] = { ["DISPLAY"] = "Turn in 'Etwas Verlegtes, etwas Blaues' to Duillam"; ["LOAD_QUEST"] = "A_CURE_FOR_ALL_ILLS"; ["CHAIN_END"] = "SOMETHING_MISPLACED"; };
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_PICKUP] = { ["DISPLAY"] = "[Milestone] Take stable-master to <rgb=#ffc000>Obere Ställe</rgb>, go to Houses of Healing, High Hall, and take 'Ein Mittel gegen jedes Leid' from Ioreth."; ["CHAIN_BEGIN"] = "A_CURE_FOR_ALL_ILLS"; };
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_BOTTLES] = { ["DISPLAY"] = "Ein Mittel gegen jedes Leid: Dispose of 10 half-emptied bottles"; };
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_REVELLERS] = { ["DISPLAY"] = "Ein Mittel gegen jedes Leid: Remove 6 noisy revellers [Check manually]"; };
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_END] = { ["DISPLAY"] = "Turn in 'Ein Mittel gegen jedes Leid' to Ioreth"; ["LOAD_QUEST"] = "HONOURING_HEALERS"; ["CHAIN_END"] = "A_CURE_FOR_ALL_ILLS";  };
    [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_COMPLETE] = { ["DISPLAY"] = "Go to Houses of Healing, House of Remedies and continue 'Ein Dank an die Heiler' with 6 Healers."; ["LOAD_QUEST"] = "SOMETHING_FLORAL"; };
    [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_COMPLETE] = { ["DISPLAY"] = "Take ramp down to <rgb=#ffc000>Gelehrtenring</rgb>, go to Houses of Lore on the right, and place 6 floral arrangements for 'Etwas blumig'."; ["LOAD_QUEST"] = "LOVE_IS_IN_THE_AIR"; };
    [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_PICKUP] = { ["DISPLAY"] = "Take 'Liebe liegt in der Luft' from Colladan."; ["CHAIN_BEGIN"] = "LOVE_IS_IN_THE_AIR"; };
    [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_COMPLETE] = { ["DISPLAY"] = "Liebe liegt in der Luft: Catch 6 wayward verses"; };
    [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_END] = { ["DISPLAY"] = "Turn in 'Liebe liegt in der Luft' to Colladan"; ["LOAD_QUEST"] = "WHAT_ALES_YOU"; ["CHAIN_END"] = "LOVE_IS_IN_THE_AIR"; };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_4] = { ["DISPLAY"] = "Exit Houses of Lore, turn right and go to The Thirsty Seer. Go forward, then right. Get Barrel of Ale for 'Die Bier-Jahreszeiten'."; ["LOAD_QUEST"] = "IN_CELEBRATION_OF_MIDSUMMER"; };
    [QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_END] = { ["DISPLAY"] = "[Milestone] Turn in 'Zur Feier von Mittsommer' to Faeleth."; ["LOAD_QUEST"] = "HONOURING_HEALERS"; ["CHAIN_END"] = "IN_CELEBRATION_OF_MIDSUMMER"; };
    [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_END] = { ["DISPLAY"] = "Take stable-master to <rgb=#ffc000>Handwerkerring</rgb>. Enter House of Craft. Turn in 'Ein Dank an die Heiler' to Postmaster."; ["LOAD_QUEST"] = "SOMETHING_FLORAL"; ["CHAIN_END"] = "HONOURING_HEALERS"; };
    [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_END] = { ["DISPLAY"] = "Take stable-master to <rgb=#ffc000>Obere Ställe</rgb>. Run to square on the Citadel. Turn in 'Etwas blumig' to Merilien."; ["LOAD_QUEST"] = "TO_THE_LAST_DROP"; ["CHAIN_END"] = "SOMETHING_FLORAL"; };
    [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_END] = { ["DISPLAY"] = "Turn in 'Bis zum letzten Tropfen' to Merilien."; ["LOAD_QUEST"] = "WEDDING_SUPPLIES"; ["CHAIN_END"] = "TO_THE_LAST_DROP"; };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_END] = { ["DISPLAY"] = "Turn in 'Hochzeitsmaterialien' to Merilien."; ["LOAD_QUEST"] = "WHAT_ALES_YOU"; ["CHAIN_END"] = "WEDDING_SUPPLIES"; };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_END] = { ["DISPLAY"] = "Turn in 'Die Bier-Jahreszeiten' to Merilien."; ["LOAD_QUEST"] = "TASTY_MORSELS"; ["CHAIN_END"] = "WHAT_ALES_YOU"; };
    [QG_MIDSUMMER_INDEX.TASTY_MORSELS_END] = { ["DISPLAY"] = "Turn in 'Köstliche Häppchen' to Othnoron."; ["LOAD_QUEST"] = "FLORAL_CROWNS"; ["CHAIN_END"] = "TASTY_MORSELS"; };
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_END] = { ["DISPLAY"] = "Turn in 'Blumenkronen' to Florist."; ["CHAIN_END"] = "FLORAL_CROWNS"; };
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_NEW_QUEST_STRINGS[MIDSUMMER] = {
    ["Neue Aufgabe: Zur Feier von Mittsommer"] = QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_PICKUP;
    ["Neue Aufgabe: Etwas blumig"] = QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_PICKUP;
    ["Neue Aufgabe: Bis zum letzten Tropfen"] = QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_PICKUP;
    ["Neue Aufgabe: Hochzeitsmaterialien"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_PICKUP;
    ["Neue Aufgabe: Die Bier-Jahreszeiten"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_PICKUP;
    ["Neue Aufgabe: Köstliche Häppchen"] = QG_MIDSUMMER_INDEX.TASTY_MORSELS_PICKUP;
    ["Neue Aufgabe: Schmuck für die Stadt"] = QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_PICKUP;
    ["Neue Aufgabe: Blumenkronen"] = QG_MIDSUMMER_INDEX.FLORAL_CROWNS_PICKUP;
    ["Neue Aufgabe: Hilfe für die Stallhelfer"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_PICKUP;
    ["Neue Aufgabe: Richtungsweisende Kunst"] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_PICKUP;
    ["Neue Aufgabe: Münzwurf"] = QG_MIDSUMMER_INDEX.TOSS_A_COIN_PICKUP;
    ["Neue Aufgabe: Wachstumsschmerzen"] = QG_MIDSUMMER_INDEX.GROWING_PAINS_PICKUP;
    ["Neue Aufgabe: Unnütze Hunde"] = QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_PICKUP;
    ["Neue Aufgabe: Ein Dank an die Heiler"] = QG_MIDSUMMER_INDEX.HONOURING_HEALERS_PICKUP;
    ["Neue Aufgabe: Süße Grüße"] = QG_MIDSUMMER_INDEX.SWEET_TREATS_PICKUP;
    ["Neue Aufgabe: Etwas Verlegtes, etwas Blaues"] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_PICKUP;
    ["Neue Aufgabe: Ein Mittel gegen jedes Leid"] = QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_PICKUP;
    ["Neue Aufgabe: Liebe liegt in der Luft"] = QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_PICKUP;
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_COMPLETED_QUEST_STRINGS[MIDSUMMER] = {
    ["Abgeschlossen:\nHilfe für die Stallhelfer\n"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_END;
    ["Abgeschlossen:\nMünzwurf\n"] = QG_MIDSUMMER_INDEX.TOSS_A_COIN_END;
    ["Abgeschlossen:\nUnnütze Hunde\n"] = QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_END;
    ["Abgeschlossen:\nWachstumsschmerzen\n"] = QG_MIDSUMMER_INDEX.GROWING_PAINS_END;
    ["Abgeschlossen:\nSüße Grüße\n"] = QG_MIDSUMMER_INDEX.SWEET_TREATS_END;
    ["Abgeschlossen:\nRichtungsweisende Kunst\n"] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_END;
    ["Abgeschlossen:\nEtwas Verlegtes, etwas Blaues\n"] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_END;
    ["Abgeschlossen:\nEin Mittel gegen jedes Leid\n"] = QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_END;
    ["Abgeschlossen:\nLiebe liegt in der Luft\n"] = QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_END;
    ["Abgeschlossen:\nZur Feier von Mittsommer\n"] = QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_END;
    ["Abgeschlossen:\nEin Dank an die Heiler\n"] = QG_MIDSUMMER_INDEX.HONOURING_HEALERS_END;
    ["Abgeschlossen:\nEtwas blumig\n"] = QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_END;
    ["Abgeschlossen:\nBis zum letzten Tropfen\n"] = QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_END;
    ["Abgeschlossen:\nHochzeitsmaterialien\n"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_END;
    ["Abgeschlossen:\nDie Bier-Jahreszeiten\n"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_END;
    ["Abgeschlossen:\nKöstliche Häppchen\n"] = QG_MIDSUMMER_INDEX.TASTY_MORSELS_END;
    ["Abgeschlossen:\nBlumenkronen\n"] = QG_MIDSUMMER_INDEX.FLORAL_CROWNS_END;
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_QUEST_OBJECTIVE_STRINGS[MIDSUMMER] = {
    ["Ihr habt einen Striegel gefunden."] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_BRUSH;
    ["Ihr habt Äpfel an Euch genommen."] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_APPLES;
    ["Anzahl gestriegelter Pferde (3/3)"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_GROOM;
    ["Anzahl gefütterter Pferde (3/3)"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_FEED;
    ["Anzahl gesammelter Sommerblumen (10/10)"] = QG_MIDSUMMER_INDEX.FLORAL_CROWNS_COLLECT;
    ["Anzahl der lästigen Barden zugeworfenen Münzen (6/6)"] = QG_MIDSUMMER_INDEX.TOSS_A_COIN_COMPLETE;
    ["Anzahl gesammelter Bierfässer (1/4)"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_1;
    ["Ihr habt das richtige Weinfass aufgenommen."] = QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_COMPLETE;
    ["Anzahl gesammelter Bierfässer (2/4)"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_2;
    ["Ihr habt Blumen beschafft."] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_LEBADAR;
    ["Ihr habt den Ring gefunden!"] = QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_CONTINUE;
    ["Anzahl gesammelter Kisten mit Hochzeitsmaterialien (1/5)"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_1;
    ["Ihr habt Lehm beschafft."] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_POTTER;
    ["Anzahl gesammelter Kisten mit Hochzeitsmaterialien (3/5)"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_3;
    ["Anzahl der gegossenen Büsche (4/4)"] = QG_MIDSUMMER_INDEX.GROWING_PAINS_WATER;
    ["Menge an gejätetem Unkraut (5/5)"] = QG_MIDSUMMER_INDEX.GROWING_PAINS_WEEDS;
    ["Ihr habt Kohle beschafft."] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_CIRIEL;
    ["Anzahl der verteilten Backwaren (2/4)"] = QG_MIDSUMMER_INDEX.SWEET_TREATS_2;
    ["Anzahl gesammelter Kisten mit Hochzeitsmaterialien (4/5)"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_4;
    ["Anzahl der verteilten Backwaren (4/4)"] = QG_MIDSUMMER_INDEX.SWEET_TREATS_4;
    ["Anzahl gesammelter Kisten mit Hochzeitsmaterialien (5/5)"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_5;
    ["Anzahl platzierten Blumenschmucks (2/5)"] = QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_2;
    ["Anzahl gesammelter Bierfässer (3/4)"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_3;
    ["Anzahl der hinter die Bühne im Blauen Theater geschickten Wolkenköpfe (6/6)"] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_COMPLETE;
    ["Anzahl platzierten Blumenschmucks (5/5)"] = QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_END;
    ["Anzahl der in der Hohen Halle entsorgten halb geleerten Flaschen (10/10)"] = QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_BOTTLES;
    ["Anzahl überbrachter Dankesbriefe (6/6)"] = QG_MIDSUMMER_INDEX.HONOURING_HEALERS_COMPLETE;
    ["Anzahl platzierten Blumenschmucks (6/6)"] = QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_COMPLETE;
    ["Anzahl gefundener fortgewehter Verse (6/6)"] = QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_COMPLETE;
    ["Anzahl gesammelter Bierfässer (4/4)"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_4;
    --No count: 'Der Feiernde sagt nichts und verschwindet mit mürrischem Blick.', need it 6 times.
};
