
_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CREDITS[MIDSUMMER] = "\nDiese Anleitung basiert auf LilRedHeads herausragendem 'LOTRO Midsummer Festival - Quick Guide', nachzulesen bei https://lifebeyondtheshire.com/lotro-midsummer-festival-quick-guide/. Vielen Dank LRH!";

QG_MIDSUMMER = _G.CubePlugins.FestivalBuddyII._QUICK_GUIDE[MIDSUMMER];
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_PICKUP].DISPLAY = "Nimm 'Zur Feier von Mittsommer' von Faeleth vor den <rgb=#ffc000>Städtischen Ställen</rgb> an!";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_PICKUP].DISPLAY = "Nimm 'Etwas blumig' von Merilien in der Zitadelle an";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_PICKUP].DISPLAY = "Nimm 'Bis zum letzten Tropfen' von Merilien in der Zitadelle an";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_PICKUP].DISPLAY = "Nimm 'Hochzeitsmaterialien' von Merilien in der Zitadelle an";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_PICKUP].DISPLAY = "Nimm 'Die Bier-Jahreszeiten' von Merilien in der Zitadelle an";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TASTY_MORSELS_PICKUP].DISPLAY = "Nimm 'Köstliche Häppchen' von Othnoron  in der Zitadelle an";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_PICKUP].DISPLAY = "Nimm 'Schmuck für die Stadt' vom Blumenhändler in der Zitadelle an";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.FLORAL_CROWNS_PICKUP].DISPLAY = "Nimm 'Blumenkronen' vom Blumenhändler in der Zitadelle an";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_PICKUP].DISPLAY = "Nimm 'Hilfe für die Stallhelfer' von Loborís in den Städtischen Ställen";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_BRUSH].DISPLAY = "Hilfe für die Stallhelfer: Nimm den Striegel aus der Ausrüstungskiste";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_APPLES].DISPLAY = "Hilfe für die Stallhelfer: Nimm die Äpfel aus der Apfelkiste";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_GROOM].DISPLAY = "Hilfe für die Stallhelfer: Striegle 3 Pferde";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_FEED].DISPLAY = "Hilfe für die Stallhelfer: Füttere 3 Pferde";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_END].DISPLAY = "Gib 'Hilfe für die Stallhelfer' bei Loborís in den Städtischen Ställen ab";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.FLORAL_CROWNS_COLLECT].DISPLAY = "Blumenkronen: Setze die Aufgabe mit der Tochter der Blumenhändlerin fort, sammle 10 Sommerblumen";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.FLORAL_CROWNS_CRAFT].DISPLAY = "Blumenkronen: Setze die Aufgabe mit der Tochter der Blumenhändlerin fort, stelle Blumenkronen her. [Händisch abhaken]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_PICKUP].DISPLAY = "Nimm den Stallmeister zum <rgb=#ffc000>Soldatenring</rgb>, nimm 'Richtungsweisende Kunst' von Borlach an";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TOSS_A_COIN_PICKUP].DISPLAY = "Nach Süden (links) zum Gespaltenen Schild, Nimm 'Münzwurf' bei Ulthir (obere Etage) an";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TOSS_A_COIN_COMPLETE].DISPLAY = "Münzwurf: Wirf den lärmenden Barden 6 Münzen zu.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_1].DISPLAY = "Die Bier-Jahreszeiten: Nimm das Bierfaß im Gespaltenen Schild.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_COMPLETE].DISPLAY = "Bis zum letzten Tropfen: Nimm das richtige Weinfaß im Gespaltenen Schild.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TOSS_A_COIN_END].DISPLAY = "Gib 'Münzwurf' bei Ulthir (obere Etage) ab";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_2].DISPLAY = "Nach Süden zum Mûmak und Feste für das zweite 'Die Bier-Jahreszeiten' Faß, Neben dem Mûmak";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_LEBADAR].DISPLAY = "[Milestone] Nimm den Stallmeister zum <rgb=#ffc000>Handwerkerring</rgb>. Am Fuß der Rampe, führe 'Richtungsweisende Kunst' mit Lebadar fort";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.GROWING_PAINS_PICKUP].DISPLAY = "Nimm 'Wachstumsschmerzen' bei Lebadar an";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_PICKUP].DISPLAY = "Nimm 'Unnütze Hunde' bei der Besorgten Frau am Platz an";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_CONTINUE].DISPLAY = "Unnütze Hunde: Finde den vermißten Ring";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_END].DISPLAY = "Gib 'Unnütze Hunde' bei der Besorgten Frau ab.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_1].DISPLAY = "Reite die Rampe hinauf, wende Dich rechts, nimm Hochzeitsmaterialien";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_POTTER].DISPLAY = "Führe 'Richtungsweisende Kunst' mit Töpfer fort";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_3].DISPLAY = "Gehe in die Häuser der Handwerkskunst, nimm zwei weitere Hochzeitsmaterialien";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.HONOURING_HEALERS_PICKUP].DISPLAY = "Nimm 'Ein Dank an die Heiler' beim Postmeister an";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.GROWING_PAINS_WATER].DISPLAY = "'Wachstumsschmerzen' (Im Garten am Nordende): Wässere 4 Büsche";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.GROWING_PAINS_WEEDS].DISPLAY = "'Wachstumsschmerzen': Rupfe 5 mal Unkraut";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.GROWING_PAINS_END].DISPLAY = "[Milestone] Nimm den Stallmeister zum <rgb=#ffc000>Handwerkerring</rgb>. Am Fuß der Rampe, gib 'Wachstumsschmerzen' ab";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_CIRIEL].DISPLAY = "Reite die Rampe hinauf, nimm den Stallmeister zum <rgb=#ffc000>Spielerring</rgb>. Am Fuß der Rampe, führe 'Richtungsweisende Kunst' bei Ciriel fort.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SWEET_TREATS_PICKUP].DISPLAY = "Nimm 'Süße Grüße' bei Ciriel an";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SWEET_TREATS_2].DISPLAY = "Finde die beiden Wachen nördlich von Ciriel, führe 'Süße Grüße' mit jeder fort.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_4].DISPLAY = "Nimm Hochzeitsmaterialien um die Ecke bei Ciriel.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SWEET_TREATS_4].DISPLAY = "Finde die beiden Wachen südlich von Ciriel, führe 'Süße Grüße' mit jeder fort.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_5].DISPLAY = "Nimm die letzten Hochzeitsmaterialien zwischen beiden südlichen Wachen.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_2].DISPLAY = "Geh zum Fröhlichen Schwan, platziere zwei Blumenarrangements auf der Bühne für 'Schmuck für die Stadt'.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_3].DISPLAY = "Die Bier-Jahreszeiten: Nimm das Bierfaß im Fröhlichen Schwan.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SWEET_TREATS_END].DISPLAY = "Gib 'Süße Grüße' bei Ciriel ab";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_END].DISPLAY = "Go up ramp, take stable-master to <rgb=#ffc000>Soldatenring</rgb>, turn in 'Richtungsweisende Kunst' to Borlach of Rimmon.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TASTY_MORSELS_COMPLETE].DISPLAY = "Take stable-master to <rgb=#ffc000>Spielerring</rgb>. Continue 'Köstliche Häppchen' with five loftier citizens. [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_PICKUP].DISPLAY = "Go to Blue Theater. Pick up 'Etwas Verlegtes, etwas Blaues' from Duillam.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_HOLLUR].DISPLAY = "Find Hollur [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_POLLA].DISPLAY = "Find Polla [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_FROKI].DISPLAY = "Find Fróki [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_DAENAR].DISPLAY = "Find Daenar [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_ROBBO].DISPLAY = "Find Robbo [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_GORD].DISPLAY = "Find Gord [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_COMPLETE].DISPLAY = "Continue 'Etwas Verlegtes, etwas Blaues' with Hollur, Polla, Fróki, Gord, Robbo, and Daenar.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_END].DISPLAY = "In the Blue Theater, place three floral arrangements on stage for 'Schmuck für die Stadt'.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_END].DISPLAY = "Turn in 'Etwas Verlegtes, etwas Blaues' to Duillam";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_PICKUP].DISPLAY = "[Milestone] Take stable-master to <rgb=#ffc000>Obere Ställe</rgb>, go to Houses of Healing, High Hall, and take 'Ein Mittel gegen jedes Leid' from Ioreth.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_BOTTLES].DISPLAY = "Ein Mittel gegen jedes Leid: Dispose of 10 half-emptied bottles";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_REVELLERS].DISPLAY = "Ein Mittel gegen jedes Leid: Remove 6 noisy revellers [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_END].DISPLAY = "Turn in 'Ein Mittel gegen jedes Leid' to Ioreth";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.HONOURING_HEALERS_COMPLETE].DISPLAY = "Go to Houses of Healing, House of Remedies and continue 'Ein Dank an die Heiler' with 6 Healers.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_COMPLETE].DISPLAY = "Take ramp down to <rgb=#ffc000>Gelehrtenring</rgb>, go to Houses of Lore on the right, and place 6 floral arrangements for 'Etwas blumig'.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_PICKUP].DISPLAY = "Take 'Liebe liegt in der Luft' from Colladan.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_COMPLETE].DISPLAY = "Liebe liegt in der Luft: Catch 6 wayward verses";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_END].DISPLAY = "Turn in 'Liebe liegt in der Luft' to Colladan";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_4].DISPLAY = "Exit Houses of Lore, turn right and go to The Thirsty Seer. Go forward, then right. Get Barrel of Ale for 'Die Bier-Jahreszeiten'.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_END].DISPLAY = "[Milestone] Turn in 'Zur Feier von Mittsommer' to Faeleth.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.HONOURING_HEALERS_END].DISPLAY = "Take stable-master to <rgb=#ffc000>Handwerkerring</rgb>. Enter House of Craft. Turn in 'Ein Dank an die Heiler' to Postmaster.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_END].DISPLAY = "Take stable-master to <rgb=#ffc000>Obere Ställe</rgb>. Run to square on the Citadel. Turn in 'Etwas blumig' to Merilien.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_END].DISPLAY = "Turn in 'Bis zum letzten Tropfen' to Merilien.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_END].DISPLAY = "Turn in 'Hochzeitsmaterialien' to Merilien.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_END].DISPLAY = "Turn in 'Die Bier-Jahreszeiten' to Merilien.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TASTY_MORSELS_END].DISPLAY = "Turn in 'Köstliche Häppchen' to Othnoron.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.FLORAL_CROWNS_END].DISPLAY = "Turn in 'Blumenkronen' to Florist.";

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_NEW_QUEST_STRINGS[MIDSUMMER] = {
    ["Neue Aufgabe: Zur Feier von Mittsommer"] = QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_PICKUP;
    ["Neue Aufgabe: Etwas blumig"] = QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_PICKUP;
    ["Neue Aufgabe: Bis zum letzten Tropfen"] = QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_PICKUP;
    ["Neue Aufgabe: Hochzeitsmaterialien"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_PICKUP;
    ["Neue Aufgabe: Die Bier-Jahreszeiten"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_PICKUP;
    ["Neue Aufgabe: Köstliche Häppchen"] = QG_MIDSUMMER_INDEX.TASTY_MORSELS_PICKUP;
    ["Neue Aufgabe: Schmuck für die Stadt"] = QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_PICKUP;
    ["Neue Aufgabe: Blumenkronen"] = QG_MIDSUMMER_INDEX.FLORAL_CROWNS_PICKUP;
    ["Neue Aufgabe: Hilfe für die Stallhelfer"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_PICKUP;
    ["Neue Aufgabe: Richtungsweisende Kunst"] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_PICKUP;
    ["Neue Aufgabe: Münzwurf"] = QG_MIDSUMMER_INDEX.TOSS_A_COIN_PICKUP;
    ["Neue Aufgabe: Wachstumsschmerzen"] = QG_MIDSUMMER_INDEX.GROWING_PAINS_PICKUP;
    ["Neue Aufgabe: Unnütze Hunde"] = QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_PICKUP;
    ["Neue Aufgabe: Ein Dank an die Heiler"] = QG_MIDSUMMER_INDEX.HONOURING_HEALERS_PICKUP;
    ["Neue Aufgabe: Süße Grüße"] = QG_MIDSUMMER_INDEX.SWEET_TREATS_PICKUP;
    ["Neue Aufgabe: Etwas Verlegtes, etwas Blaues"] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_PICKUP;
    ["Neue Aufgabe: Ein Mittel gegen jedes Leid"] = QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_PICKUP;
    ["Neue Aufgabe: Liebe liegt in der Luft"] = QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_PICKUP;
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_COMPLETED_QUEST_STRINGS[MIDSUMMER] = {
    ["Abgeschlossen:\nHilfe für die Stallhelfer\n"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_END;
    ["Abgeschlossen:\nMünzwurf\n"] = QG_MIDSUMMER_INDEX.TOSS_A_COIN_END;
    ["Abgeschlossen:\nUnnütze Hunde\n"] = QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_END;
    ["Abgeschlossen:\nWachstumsschmerzen\n"] = QG_MIDSUMMER_INDEX.GROWING_PAINS_END;
    ["Abgeschlossen:\nSüße Grüße\n"] = QG_MIDSUMMER_INDEX.SWEET_TREATS_END;
    ["Abgeschlossen:\nRichtungsweisende Kunst\n"] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_END;
    ["Abgeschlossen:\nEtwas Verlegtes, etwas Blaues\n"] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_END;
    ["Abgeschlossen:\nEin Mittel gegen jedes Leid\n"] = QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_END;
    ["Abgeschlossen:\nLiebe liegt in der Luft\n"] = QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_END;
    ["Abgeschlossen:\nZur Feier von Mittsommer\n"] = QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_END;
    ["Abgeschlossen:\nEin Dank an die Heiler\n"] = QG_MIDSUMMER_INDEX.HONOURING_HEALERS_END;
    ["Abgeschlossen:\nEtwas blumig\n"] = QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_END;
    ["Abgeschlossen:\nBis zum letzten Tropfen\n"] = QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_END;
    ["Abgeschlossen:\nHochzeitsmaterialien\n"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_END;
    ["Abgeschlossen:\nDie Bier-Jahreszeiten\n"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_END;
    ["Abgeschlossen:\nKöstliche Häppchen\n"] = QG_MIDSUMMER_INDEX.TASTY_MORSELS_END;
    ["Abgeschlossen:\nBlumenkronen\n"] = QG_MIDSUMMER_INDEX.FLORAL_CROWNS_END;
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_QUEST_OBJECTIVE_STRINGS[MIDSUMMER] = {
    ["Ihr habt einen Striegel gefunden."] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_BRUSH;
    ["Ihr habt Äpfel an Euch genommen."] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_APPLES;
    ["Anzahl gestriegelter Pferde (3/3)"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_GROOM;
    ["Anzahl gefütterter Pferde (3/3)"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_FEED;
    ["Anzahl gesammelter Sommerblumen (10/10)"] = QG_MIDSUMMER_INDEX.FLORAL_CROWNS_COLLECT;
    ["Anzahl der lästigen Barden zugeworfenen Münzen (6/6)"] = QG_MIDSUMMER_INDEX.TOSS_A_COIN_COMPLETE;
    ["Anzahl gesammelter Bierfässer (1/4)"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_1;
    ["Ihr habt das richtige Weinfass aufgenommen."] = QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_COMPLETE;
    ["Anzahl gesammelter Bierfässer (2/4)"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_2;
    ["Ihr habt Blumen beschafft."] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_LEBADAR;
    ["Ihr habt den Ring gefunden!"] = QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_CONTINUE;
    ["Anzahl gesammelter Kisten mit Hochzeitsmaterialien (1/5)"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_1;
    ["Ihr habt Lehm beschafft."] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_POTTER;
    ["Anzahl gesammelter Kisten mit Hochzeitsmaterialien (3/5)"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_3;
    ["Anzahl der gegossenen Büsche (4/4)"] = QG_MIDSUMMER_INDEX.GROWING_PAINS_WATER;
    ["Menge an gejätetem Unkraut (5/5)"] = QG_MIDSUMMER_INDEX.GROWING_PAINS_WEEDS;
    ["Ihr habt Kohle beschafft."] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_CIRIEL;
    ["Anzahl der verteilten Backwaren (2/4)"] = QG_MIDSUMMER_INDEX.SWEET_TREATS_2;
    ["Anzahl gesammelter Kisten mit Hochzeitsmaterialien (4/5)"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_4;
    ["Anzahl der verteilten Backwaren (4/4)"] = QG_MIDSUMMER_INDEX.SWEET_TREATS_4;
    ["Anzahl gesammelter Kisten mit Hochzeitsmaterialien (5/5)"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_5;
    ["Anzahl platzierten Blumenschmucks (2/5)"] = QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_2;
    ["Anzahl gesammelter Bierfässer (3/4)"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_3;
    ["Anzahl der hinter die Bühne im Blauen Theater geschickten Wolkenköpfe (6/6)"] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_COMPLETE;
    ["Anzahl platzierten Blumenschmucks (5/5)"] = QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_END;
    ["Anzahl der in der Hohen Halle entsorgten halb geleerten Flaschen (10/10)"] = QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_BOTTLES;
    ["Anzahl überbrachter Dankesbriefe (6/6)"] = QG_MIDSUMMER_INDEX.HONOURING_HEALERS_COMPLETE;
    ["Anzahl platzierten Blumenschmucks (6/6)"] = QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_COMPLETE;
    ["Anzahl gefundener fortgewehter Verse (6/6)"] = QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_COMPLETE;
    ["Anzahl gesammelter Bierfässer (4/4)"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_4;
    --No count: 'Der Feiernde sagt nichts und verschwindet mit mürrischem Blick.', need it 6 times.
};
