
_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CREDITS[MIDSUMMER] = "\nThis guide is based on LilRedHead's excellent LOTRO Midsummer Festival - Quick Guide at https://lifebeyondtheshire.com/lotro-midsummer-festival-quick-guide/. Thank you LRH!";

QG_MIDSUMMER = _G.CubePlugins.FestivalBuddyII._QUICK_GUIDE[MIDSUMMER];
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_PICKUP].DISPLAY = "Take 'In Celebration of Midsummer' from Faeleth outside <rgb=#ffc000>City Stables</rgb>";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_PICKUP].DISPLAY = "Take 'Something Floral' from Merilien on the Citadel";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_PICKUP].DISPLAY = "Take 'To the Last Drop' from Merilien";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_PICKUP].DISPLAY = "Take 'Wedding Supplies' from Merilien";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_PICKUP].DISPLAY = "Take 'What Ales You' from Merilien";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TASTY_MORSELS_PICKUP].DISPLAY = "Take 'Tasty Morsels' from Othnoron on the Citadel";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_PICKUP].DISPLAY = "Take 'Arranging Arrangements' from Florist on the Citadel";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.FLORAL_CROWNS_PICKUP].DISPLAY = "Take 'Floral Crowns' from Florist";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_PICKUP].DISPLAY = "Take 'Aiding the Stable-hands' from Loborís in City Stables";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_BRUSH].DISPLAY = "Aiding the Stable-hands: Take brush from Equipment Crate";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_APPLES].DISPLAY = "Aiding the Stable-hands: Take apples from Crate of Apples";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_GROOM].DISPLAY = "Aiding the Stable-hands: Groom 3 horses"
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_FEED].DISPLAY = "Aiding the Stable-hands: Feed 3 horses"
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_END].DISPLAY = "Turn in 'Aiding the Stable-hands' to Loborís in City Stables";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.FLORAL_CROWNS_COLLECT].DISPLAY = "Floral Crowns: Continue quest with Florist's Daughter, collect 10 summer blossoms";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.FLORAL_CROWNS_CRAFT].DISPLAY = "Floral Crowns: Continue quest with Florist's Daughter, craft floral crown. [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_PICKUP].DISPLAY = "Take stable-master to <rgb=#ffc000>Soldiers' Tier</rgb>, Take 'Artistic Direction' from Borlach";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TOSS_A_COIN_PICKUP].DISPLAY = "Go south/left to Splintered Shield, Take 'Toss a Coin' from Ulthir upstairs";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TOSS_A_COIN_COMPLETE].DISPLAY = "Toss a Coin: Toss coins to 6 noisy minstrels.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_1].DISPLAY = "What Ales You: Get Barrel of Ale in The Splintered Shield.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_COMPLETE].DISPLAY = "To the Last Drop: Take correct Barrel of Wine in The Splintered Shield.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TOSS_A_COIN_END].DISPLAY = "Turn in 'Toss a Coin' to Ulthir upstairs";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_2].DISPLAY = "Go south to Mûmak and Keep for 2nd 'What Ales You' Barrel, next to mûmak";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_LEBADAR].DISPLAY = "[Milestone] Take stable-master to <rgb=#ffc000>Craftsmen's Tier</rgb>. At bottom of ramp, continue 'Artistic Direction' with Lebadar";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.GROWING_PAINS_PICKUP].DISPLAY = "Take 'Growing Pains' from Lebadar";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_PICKUP].DISPLAY = "Take 'Unhelpful Hounds' from Worried Woman in the square";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_CONTINUE].DISPLAY = "Unhelpful Hounds: Find the missing ring";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_END].DISPLAY = "Turn in 'Unhelpful Hounds' to Worried Woman";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_1].DISPLAY = "Ride up ramp, turn right, grab Wedding Supplies";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_POTTER].DISPLAY = "Continue 'Artistic Direction' with Potter";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_3].DISPLAY = "Go into House of Craft, grab two more Wedding Supplies";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.HONOURING_HEALERS_PICKUP].DISPLAY = "Take 'Honouring Healers' from the Postmaster";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.GROWING_PAINS_WATER].DISPLAY = "'Growing Pains' (In garden at north end): Water 4 bushes";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.GROWING_PAINS_WEEDS].DISPLAY = "'Growing Pains': Pull out 5 weeds";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.GROWING_PAINS_END].DISPLAY = "[Milestone] Take stable-master to <rgb=#ffc000>Craftsmen's Tier</rgb>. At bottom of ramp, turn in 'Growing Pains'";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_CIRIEL].DISPLAY = "Ride up ramp, take stable-master to <rgb=#ffc000>Players' Tier</rgb>. At bottom of ramp, continue 'Artistic Direction' with Ciriel.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SWEET_TREATS_PICKUP].DISPLAY = "Take 'Sweet Treats' from Ciriel";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SWEET_TREATS_2].DISPLAY = "Find the two guards to the north of Ciriel, continue 'Sweet Treats' with each.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_4].DISPLAY = "Grab Wedding Supplies around the corner of Ciriel.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SWEET_TREATS_4].DISPLAY = "Find the two guards to the south of Ciriel, continue 'Sweet Treats' with each.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_5].DISPLAY = "Grab final Wedding Supplies between two south guards."; 
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_2].DISPLAY = "Go to Merry Swan, place two floral arrangements on stage for 'Arranging Arrangements'.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_3].DISPLAY = "What Ales You: Get Barrel of Ale in The Merry Swan.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SWEET_TREATS_END].DISPLAY = "Turn in 'Sweet Treats' to Ciriel";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_END].DISPLAY = "Go up ramp, take stable-master to <rgb=#ffc000>Soldiers' Tier</rgb>, turn in 'Artistic Direction' to Borlach of Rimmon.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TASTY_MORSELS_COMPLETE].DISPLAY = "Take stable-master to <rgb=#ffc000>Players' Tier</rgb>. Continue 'Tasty Morsels' with five loftier citizens. [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_PICKUP].DISPLAY = "Go to Blue Theater. Pick up 'Something Misplaced, Something Blue' from Duillam.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_HOLLUR].DISPLAY = "Find Hollur [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_POLLA].DISPLAY = "Find Polla [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_FROKI].DISPLAY = "Find Fróki [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_DAENAR].DISPLAY = "Find Daenar [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_ROBBO].DISPLAY = "Find Robbo [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_GORD].DISPLAY = "Find Gord [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_COMPLETE].DISPLAY = "Continue 'Something Misplaced, Something Blue' with Hollur, Polla, Fróki, Gord, Robbo, and Daenar.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_END].DISPLAY = "In the Blue Theater, place three floral arrangements on stage for 'Arranging Arrangements'.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_END].DISPLAY = "Turn in 'Something Misplaced, Something Blue' to Duillam";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_PICKUP].DISPLAY = "[Milestone] Take stable-master to <rgb=#ffc000>High Stables</rgb>, go to Houses of Healing, High Hall, and take 'A Cure For All Ills' from Ioreth.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_BOTTLES].DISPLAY = "A Cure For All Ills: Dispose of 10 half-emptied bottles";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_REVELLERS].DISPLAY = "A Cure For All Ills: Remove 6 noisy revellers [Check manually]";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_END].DISPLAY = "Turn in 'A Cure For All Ills' to Ioreth";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.HONOURING_HEALERS_COMPLETE].DISPLAY = "Go to Houses of Healing, House of Remedies and continue 'Honouring Healers' with 6 Healers.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_COMPLETE].DISPLAY = "Take ramp down to <rgb=#ffc000>Sages' Tier</rgb>, go to Houses of Lore on the right, and place 6 floral arrangements for 'Something Floral'.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_PICKUP].DISPLAY = "Take 'Love Is In the Air' from Colladan.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_COMPLETE].DISPLAY = "Love Is In the Air: Catch 6 wayward verses";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_END].DISPLAY = "Turn in 'Love Is In the Air' to Colladan";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_4].DISPLAY = "Exit Houses of Lore, turn right and go to The Thirsty Seer. Go forward, then right. Get Barrel of Ale for 'What Ales You'.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_END].DISPLAY = "[Milestone] Turn in 'In Celebration of Midsummer' to Faeleth.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.HONOURING_HEALERS_END].DISPLAY = "Take stable-master to <rgb=#ffc000>Craftsmen's Tier</rgb>. Enter House of Craft. Turn in 'Honouring Healers' to Postmaster.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_END].DISPLAY = "Take stable-master to <rgb=#ffc000>High Stables</rgb>. Run to square on the Citadel. Turn in 'Something Floral' to Merilien.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_END].DISPLAY = "Turn in 'To the Last Drop' to Merilien.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_END].DISPLAY = "Turn in 'Wedding Supplies' to Merilien.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_END].DISPLAY = "Turn in 'What Ales You' to Merilien.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.TASTY_MORSELS_END].DISPLAY = "Turn in 'Tasty Morsels' to Othnoron.";
QG_MIDSUMMER[QG_MIDSUMMER_INDEX.FLORAL_CROWNS_END].DISPLAY = "Turn in 'Floral Crowns' to Florist.";

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_NEW_QUEST_STRINGS[MIDSUMMER] = {
    ["New Quest: In Celebration of Midsummer"] = QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_PICKUP;
    ["New Quest: Something Floral"] = QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_PICKUP;
    ["New Quest: To the Last Drop"] = QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_PICKUP;
    ["New Quest: Wedding Supplies"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_PICKUP;
    ["New Quest: What Ales You"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_PICKUP;
    ["New Quest: Tasty Morsels"] = QG_MIDSUMMER_INDEX.TASTY_MORSELS_PICKUP;
    ["New Quest: Arranging Arrangements"] = QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_PICKUP;
    ["New Quest: Floral Crowns"] = QG_MIDSUMMER_INDEX.FLORAL_CROWNS_PICKUP;
    ["New Quest: Aiding the Stable-hands"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_PICKUP;
    ["New Quest: Artistic Direction"] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_PICKUP;
    ["New Quest: Toss a Coin"] = QG_MIDSUMMER_INDEX.TOSS_A_COIN_PICKUP;
    ["New Quest: Growing Pains"] = QG_MIDSUMMER_INDEX.GROWING_PAINS_PICKUP;
    ["New Quest: Unhelpful Hounds"] = QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_PICKUP;
    ["New Quest: Honouring Healers"] = QG_MIDSUMMER_INDEX.HONOURING_HEALERS_PICKUP;
    ["New Quest: Sweet Treats"] = QG_MIDSUMMER_INDEX.SWEET_TREATS_PICKUP;
    ["New Quest: Something Misplaced, Something Blue"] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_PICKUP;
    ["New Quest: A Cure For All Ills"] = QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_PICKUP;
    ["New Quest: Love Is In the Air"] = QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_PICKUP;
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_COMPLETED_QUEST_STRINGS[MIDSUMMER] = {
    ["Completed:\nAiding the Stable-hands\n"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_END;
    ["Completed:\nToss a Coin\n"] = QG_MIDSUMMER_INDEX.TOSS_A_COIN_END;
    ["Completed:\nUnhelpful Hounds\n"] = QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_END;
    ["Completed:\nGrowing Pains\n"] = QG_MIDSUMMER_INDEX.GROWING_PAINS_END;
    ["Completed:\nSweet Treats\n"] = QG_MIDSUMMER_INDEX.SWEET_TREATS_END;
    ["Completed:\nArtistic Direction\n"] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_END;
    ["Completed:\nSomething Misplaced, Something Blue\n"] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_END;
    ["Completed:\nA Cure For All Ills\n"] = QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_END;
    ["Completed:\nLove Is In the Air\n"] = QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_END;
    ["Completed:\nIn Celebration of Midsummer\n"] = QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_END;
    ["Completed:\nHonouring Healers\n"] = QG_MIDSUMMER_INDEX.HONOURING_HEALERS_END;
    ["Completed:\nSomething Floral\n"] = QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_END;
    ["Completed:\nTo the Last Drop\n"] = QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_END;
    ["Completed:\nWedding Supplies\n"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_END;
    ["Completed:\nWhat Ales You\n"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_END;
    ["Completed:\nTasty Morsels\n"] = QG_MIDSUMMER_INDEX.TASTY_MORSELS_END;
    ["Completed:\nFloral Crowns\n"] = QG_MIDSUMMER_INDEX.FLORAL_CROWNS_END;
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_QUEST_OBJECTIVE_STRINGS[MIDSUMMER] = {
    ["Found a grooming brush"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_BRUSH;
    ["Collected apples"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_APPLES;
    ["Groomed horse (3/3)"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_GROOM;
    ["Fed horse (3/3)"] = QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_FEED;
    ["Collected summer blossoms (10/10)"] = QG_MIDSUMMER_INDEX.FLORAL_CROWNS_COLLECT;
    ["Tossed a coin to a noisy minstrel (6/6)"] = QG_MIDSUMMER_INDEX.TOSS_A_COIN_COMPLETE;
    ["Collected barrels of ale (1/4)"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_1;
    ["Picked up the proper wine cask"] = QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_COMPLETE;
    ["Collected barrels of ale (2/4)"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_2;
    ["Obtained flowers"] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_LEBADAR;
    ["You found the ring!"] = QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_CONTINUE;
    ["Collected wedding supply crates (1/5)"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_1;
    ["Obtained clay"] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_POTTER;
    ["Collected wedding supply crates (3/5)"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_3;
    ["Watered bushes (4/4)"] = QG_MIDSUMMER_INDEX.GROWING_PAINS_WATER;
    ["Pulled out weeds (5/5)"] = QG_MIDSUMMER_INDEX.GROWING_PAINS_WEEDS;
    ["Obtained charcoal"] = QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_CIRIEL;
    ["Delivered pastries (2/4)"] = QG_MIDSUMMER_INDEX.SWEET_TREATS_2;
    ["Collected wedding supply crates (4/5)"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_4;
    ["Delivered pastries (4/4)"] = QG_MIDSUMMER_INDEX.SWEET_TREATS_4;
    ["Collected wedding supply crates (5/5)"] = QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_5;
    ["Placed floral arrangements (2/5)"] = QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_2;
    ["Collected barrels of ale (3/4)"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_3;
    ["Direct the Cloudyheads to meet backstage in the Blue Theatre (6/6)"] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_COMPLETE;
    ["Placed floral arrangements (5/5)"] = QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_END;
    ["Disposed of half-emptied bottles in the High Hall (10/10)"] = QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_BOTTLES;
    ["Delivered thank you notes (6/6)"] = QG_MIDSUMMER_INDEX.HONOURING_HEALERS_COMPLETE;
    ["Placed floral arrangements (6/6)"] = QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_COMPLETE;
    ["Caught wayward verses (6/6)"] = QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_COMPLETE;
    ["Collected barrels of ale (4/4)"] = QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_4;
    --No count: 'The reveller says nothing, but departs with a sour look', need it 6 times.
};
