-- Midsummer Quest Indexes:

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_INDICIES[MIDSUMMER] = {};
QG_MIDSUMMER_INDEX = _G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_INDICIES[MIDSUMMER];

local i = 1;
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "IN_CELEBRATION_OF_MIDSUMMER_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SOMETHING_FLORAL_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "TO_THE_LAST_DROP_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "WEDDING_SUPPLIES_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "WHAT_ALES_YOU_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "TASTY_MORSELS_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ARRANGING_ARRANGEMENTS_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "FLORAL_CROWNS_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "AIDING_THE_STABLE_HANDS_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "AIDING_THE_STABLE_HANDS_BRUSH");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "AIDING_THE_STABLE_HANDS_APPLES");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "AIDING_THE_STABLE_HANDS_GROOM");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "AIDING_THE_STABLE_HANDS_FEED");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "AIDING_THE_STABLE_HANDS_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "FLORAL_CROWNS_COLLECT");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "FLORAL_CROWNS_CRAFT");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ARTISTIC_DIRECTION_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "TOSS_A_COIN_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "TOSS_A_COIN_COMPLETE");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "WHAT_ALES_YOU_1");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "TO_THE_LAST_DROP_COMPLETE");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "TOSS_A_COIN_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "WHAT_ALES_YOU_2");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ARTISTIC_DIRECTION_LEBADAR");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "GROWING_PAINS_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "UNHELPFUL_HOUNDS_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "UNHELPFUL_HOUNDS_CONTINUE");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "UNHELPFUL_HOUNDS_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "WEDDING_SUPPLIES_1");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ARTISTIC_DIRECTION_POTTER");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "WEDDING_SUPPLIES_3");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "HONOURING_HEALERS_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "GROWING_PAINS_WATER");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "GROWING_PAINS_WEEDS");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "GROWING_PAINS_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ARTISTIC_DIRECTION_CIRIEL");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SWEET_TREATS_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SWEET_TREATS_2");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "WEDDING_SUPPLIES_4");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SWEET_TREATS_4");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "WEDDING_SUPPLIES_5");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ARRANGING_ARRANGEMENTS_2");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "WHAT_ALES_YOU_3");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SWEET_TREATS_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ARTISTIC_DIRECTION_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "TASTY_MORSELS_COMPLETE");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SOMETHING_MISPLACED_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SOMETHING_MISPLACED_HOLLUR");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SOMETHING_MISPLACED_POLLA");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SOMETHING_MISPLACED_FROKI");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SOMETHING_MISPLACED_DAENAR");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SOMETHING_MISPLACED_ROBBO");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SOMETHING_MISPLACED_GORD");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SOMETHING_MISPLACED_COMPLETE");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ARRANGING_ARRANGEMENTS_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SOMETHING_MISPLACED_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "A_CURE_FOR_ALL_ILLS_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "A_CURE_FOR_ALL_ILLS_BOTTLES");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "A_CURE_FOR_ALL_ILLS_REVELLERS");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "A_CURE_FOR_ALL_ILLS_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "HONOURING_HEALERS_COMPLETE");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SOMETHING_FLORAL_COMPLETE");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "LOVE_IS_IN_THE_AIR_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "LOVE_IS_IN_THE_AIR_COMPLETE");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "LOVE_IS_IN_THE_AIR_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "WHAT_ALES_YOU_4");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "IN_CELEBRATION_OF_MIDSUMMER_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "HONOURING_HEALERS_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SOMETHING_FLORAL_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "TO_THE_LAST_DROP_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "WEDDING_SUPPLIES_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "WHAT_ALES_YOU_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "TASTY_MORSELS_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "FLORAL_CROWNS_END");

i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "HOUSEKEEPING_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "TIDAL_TREASURES_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ASSISTING_THE_COOK_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "BUILDING_CASTLES_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "FISHING_FOR_ADVICE_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "OFFERING_TO_HELP_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SEARCHING_FOR_SWIMMING_SPOTS_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "BUILDING_CASTLES_1");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "OFFERING_TO_HELP_BEACHGOER_1");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "OFFERING_TO_HELP_BEACHGOER_2");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "OFFERING_TO_HELP_BEACHGOER_3");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "A_FLOCK_OF_SEAGULLS_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "CAT_CONUNDRUM_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "CAT_CONUNDRUM_QUEST");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "EYESORES_DRIFTED_ASHORE_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "CAT_CONUNDRUM_SCRUFFY");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "A_FLOCK_OF_SEAGULLS_1");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "A_FLOCK_OF_SEAGULLS_2");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "A_FLOCK_OF_SEAGULLS_3");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "FISHING_FOR_ADVICE_1_FOUND");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "FISHING_FOR_ADVICE_1_CAUGHT");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "A_FLOCK_OF_SEAGULLS_4");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "CAT_CONUNDRUM_SKINNY");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "LETS_GO_FLY_A_KITE_PICKUP");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "A_FLOCK_OF_SEAGULLS_5");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "OFFERING_TO_HELP_HOLIDAYER_1");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "BUILDING_CASTLES_2");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "LETS_GO_FLY_A_KITE_WEST_END_OF_HARBOUR");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "CAT_CONUNDRUM_SLINKY");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "FISHING_FOR_ADVICE_2_FOUND");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "FISHING_FOR_ADVICE_2_CAUGHT");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "A_FLOCK_OF_SEAGULLS_6");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "A_FLOCK_OF_SEAGULLS_7");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "HOUSEKEEPING_BEDS");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "HOUSEKEEPING_FLOORS");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "OFFERING_TO_HELP_HOLIDAYER_2");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "CAT_CONUNDRUM_SLEEPY");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "CAT_CONUNDRUM_SMELLY");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "A_FLOCK_OF_SEAGULLS_8");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "LETS_GO_FLY_A_KITE_SAND_IN_FRONT_OF_INN");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "LETS_GO_FLY_A_KITE_EASTERN_BRIDGE");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SEARCHING_FOR_SWIMMING_SPOTS_WEST_HARBOR");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "OFFERING_TO_HELP_HOLIDAYER_3");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "CAT_CONUNDRUM_SASSY");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "EYESORES_DRIFTED_ASHORE_1");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "LETS_GO_FLY_A_KITE_SOUTHERN_BEACH");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "OFFERING_TO_HELP_SIGHTSEER_1");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "EYESORES_DRIFTED_ASHORE_2");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "OFFERING_TO_HELP_SIGHTSEER_2");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "OFFERING_TO_HELP_SIGHTSEER_3");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "OFFERING_TO_HELP_SUITOR_1");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "OFFERING_TO_HELP_SUITOR_2");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "OFFERING_TO_HELP_SUITOR_3");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "LETS_GO_FLY_A_KITE_SOUTHERN_COVE");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "OFFERING_TO_HELP_MERRYMAKER_1");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "OFFERING_TO_HELP_MERRYMAKER_2");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "OFFERING_TO_HELP_MERRYMAKER_3");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "BUILDING_CASTLES_3");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "EYESORES_DRIFTED_ASHORE_3");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "EYESORES_DRIFTED_ASHORE_4");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "EYESORES_DRIFTED_ASHORE_5");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "BUILDING_CASTLES_4");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "EYESORES_DRIFTED_ASHORE_6");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SEARCHING_FOR_SWIMMING_SPOTS_SOUTHERN_COVE");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ASSISTING_THE_COOK_HERB_1");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ASSISTING_THE_COOK_LEMON_1");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ASSISTING_THE_COOK_HERB_2");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ASSISTING_THE_COOK_LEMON_2");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ASSISTING_THE_COOK_HERB_3");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ASSISTING_THE_COOK_OLIVE_1");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ASSISTING_THE_COOK_HERB_4");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ASSISTING_THE_COOK_OLIVE_2");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "FISHING_FOR_ADVICE_3_FOUND");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "FISHING_FOR_ADVICE_3_CAUGHT");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ASSISTING_THE_COOK_OLIVE_3");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ASSISTING_THE_COOK_LEMON_3");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ASSISTING_THE_COOK_OLIVE_4");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "TIDAL_TREASURES_SEASHELLS");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SEARCHING_FOR_SWIMMING_SPOTS_NORTHERN_CHANNEL");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "FISHING_FOR_ADVICE_4_FOUND");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "FISHING_FOR_ADVICE_4_CAUGHT");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SEARCHING_FOR_SWIMMING_SPOTS_WESTERN_BEACH");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ASSISTING_THE_COOK_LEMON_4");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SEARCHING_FOR_SWIMMING_SPOTS_SOUTH_WESTERN_BEACH");

i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "LETS_GO_FLY_A_KITE_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "A_FLOCK_OF_SEAGULLS_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "CAT_CONUNDRUM_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "EYESORES_DRIFTED_ASHORE_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "BUILDING_CASTLES_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "FISHING_FOR_ADVICE_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "OFFERING_TO_HELP_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "SEARCHING_FOR_SWIMMING_SPOTS_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "ASSISTING_THE_COOK_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "HOUSEKEEPING_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "TIDAL_TREASURES_END");
i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "IN_CELEBRATION_OF_MIDSUMMER_END");

i = AddNextQuickguideValue(QG_MIDSUMMER_INDEX, i, "RESET");

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CHAINS[MIDSUMMER] = {
    ["A_CURE_FOR_ALL_ILLS"] = {
        [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_BOTTLES] = true;
        [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_END] = true;
        [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_REVELLERS] = true;
    };

    ["AIDING_THE_STABLE_HANDS"] = {
        [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_APPLES] = true;
        [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_BRUSH] = true;
        [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_END] = true;
        [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_FEED] = true;
        [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_GROOM] = true;
        [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_PICKUP] = true;
    };

    ["ARRANGING_ARRANGEMENTS"] = {
        [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_2] = true;
        [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_END] = true;
        [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_PICKUP] = true;
    };

    ["ARTISTIC_DIRECTION"] = {
        [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_CIRIEL] = true;
        [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_END] = true;
        [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_LEBADAR] = true;
        [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_POTTER] = true;
    };

    ["FLORAL_CROWNS"] = {
        [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_COLLECT] = true;
        [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_CRAFT] = true;
        [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_END] = true;
        [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_PICKUP] = true;
    };

    ["GROWING_PAINS"] = {
        [QG_MIDSUMMER_INDEX.GROWING_PAINS_END] = true;
        [QG_MIDSUMMER_INDEX.GROWING_PAINS_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.GROWING_PAINS_WATER] = true;
        [QG_MIDSUMMER_INDEX.GROWING_PAINS_WEEDS] = true;
    };

    ["HONOURING_HEALERS"] = {
        [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_COMPLETE] = true;
        [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_END] = true;
        [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_PICKUP] = true;
    };

    ["IN_CELEBRATION_OF_MIDSUMMER"] = {
        [QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_END] = true;
        [QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_PICKUP] = true;
    };

    ["LOVE_IS_IN_THE_AIR"] = {
        [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_COMPLETE] = true;
        [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_END] = true;
        [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_PICKUP] = true;
    };

    ["SOMETHING_FLORAL"] = {
        [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_COMPLETE] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_END] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_PICKUP] = true;
    };

    ["SOMETHING_MISPLACED"] = {
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_COMPLETE] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_DAENAR] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_END] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_FROKI] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_GORD] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_HOLLUR] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_POLLA] = true;
        [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_ROBBO] = true;
    };

    ["SWEET_TREATS"] = {
        [QG_MIDSUMMER_INDEX.SWEET_TREATS_2] = true;
        [QG_MIDSUMMER_INDEX.SWEET_TREATS_4] = true;
        [QG_MIDSUMMER_INDEX.SWEET_TREATS_END] = true;
        [QG_MIDSUMMER_INDEX.SWEET_TREATS_PICKUP] = true;
    };

    ["TASTY_MORSELS"] = {
        [QG_MIDSUMMER_INDEX.TASTY_MORSELS_COMPLETE] = true;
        [QG_MIDSUMMER_INDEX.TASTY_MORSELS_END] = true;
        [QG_MIDSUMMER_INDEX.TASTY_MORSELS_PICKUP] = true;
    };

    ["TO_THE_LAST_DROP"] = {
        [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_COMPLETE] = true;
        [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_END] = true;
        [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_PICKUP] = true;
    };

    ["TOSS_A_COIN"] = {
        [QG_MIDSUMMER_INDEX.TOSS_A_COIN_COMPLETE] = true;
        [QG_MIDSUMMER_INDEX.TOSS_A_COIN_END] = true;
        [QG_MIDSUMMER_INDEX.TOSS_A_COIN_PICKUP] = true;
    };

    ["UNHELPFUL_HOUNDS"] = {
        [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_CONTINUE] = true;
        [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_END] = true;
        [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_PICKUP] = true;
    };

    ["WEDDING_SUPPLIES"] = {
        [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_1] = true;
        [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_3] = true;
        [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_4] = true;
        [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_5] = true;
        [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_END] = true;
        [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_PICKUP] = true;
    };

    ["WHAT_ALES_YOU"] = {
        [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_1] = true;
        [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_2] = true;
        [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_3] = true;
        [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_4] = true;
        [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_END] = true;
        [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_PICKUP] = true;
    };


    ["HOUSEKEEPING"] = {
        [QG_MIDSUMMER_INDEX.HOUSEKEEPING_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.HOUSEKEEPING_BEDS] = true;
        [QG_MIDSUMMER_INDEX.HOUSEKEEPING_FLOORS] = true;
        [QG_MIDSUMMER_INDEX.HOUSEKEEPING_END] = true;
    };

    ["TIDAL_TREASURES"] = {
        [QG_MIDSUMMER_INDEX.TIDAL_TREASURES_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.TIDAL_TREASURES_SEASHELLS] = true;
        [QG_MIDSUMMER_INDEX.TIDAL_TREASURES_END] = true;
    };

    ["ASSISTING_THE_COOK"] = {
        [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_HERB_1] = true;
        [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_HERB_2] = true;
        [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_HERB_3] = true;
        [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_HERB_4] = true;
        [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_LEMON_1] = true;
        [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_LEMON_2] = true;
        [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_LEMON_3] = true;
        [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_LEMON_4] = true;
        [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_OLIVE_1] = true;
        [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_OLIVE_2] = true;
        [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_OLIVE_3] = true;
        [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_OLIVE_4] = true;
        [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_END] = true;
    };

    ["BUILDING_CASTLES"] = {
        [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_1] = true;
        [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_2] = true;
        [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_3] = true;
        [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_4] = true;
        [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_END] = true;
    };

    ["FISHING_FOR_ADVICE"] = {
        [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_1_FOUND] = true;
        [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_1_CAUGHT] = true;
        [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_2_FOUND] = true;
        [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_2_CAUGHT] = true;
        [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_3_FOUND] = true;
        [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_3_CAUGHT] = true;
        [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_4_FOUND] = true;
        [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_4_CAUGHT] = true;
        [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_END] = true;
    };

    ["OFFERING_TO_HELP"] = {
        [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_BEACHGOER_1] = true;
        [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_BEACHGOER_2] = true;
        [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_BEACHGOER_3] = true;
        [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_HOLIDAYER_1] = true;
        [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_HOLIDAYER_2] = true;
        [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_HOLIDAYER_3] = true;
        [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SIGHTSEER_1] = true;
        [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SIGHTSEER_2] = true;
        [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SIGHTSEER_3] = true;
        [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SUITOR_1] = true;
        [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SUITOR_2] = true;
        [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SUITOR_3] = true;
        [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_MERRYMAKER_1] = true;
        [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_MERRYMAKER_2] = true;
        [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_MERRYMAKER_3] = true;
        [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_END] = true;
    };

    ["SEARCHING_FOR_SWIMMING_SPOTS"] = {
        [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_WEST_HARBOR] = true;
        [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_SOUTHERN_COVE] = true;
        [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_NORTHERN_CHANNEL] = true;
        [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_WESTERN_BEACH] = true;
        [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_SOUTH_WESTERN_BEACH] = true;
        [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_END] = true;
    };

    ["A_FLOCK_OF_SEAGULLS"] = {
        [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_1] = true;
        [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_2] = true;
        [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_3] = true;
        [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_4] = true;
        [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_5] = true;
        [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_6] = true;
        [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_7] = true;
        [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_8] = true;
        [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_END] = true;
    };

    ["CAT_CONUNDRUM"] = {
        [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_QUEST] = true;
        [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SCRUFFY] = true;
        [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SKINNY] = true;
        [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SLINKY] = true;
        [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SMELLY] = true;
        [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SASSY] = true;
        [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SLEEPY] = true;
        [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_END] = true;
    };

    ["EYESORES_DRIFTED_ASHORE"] = {
        [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_1] = true;
        [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_2] = true;
        [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_3] = true;
        [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_4] = true;
        [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_5] = true;
        [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_6] = true;
        [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_END] = true;
    };

    ["LETS_GO_FLY_A_KITE"] = {
        [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_PICKUP] = true;
        [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_SOUTHERN_BEACH] = true;
        [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_SOUTHERN_COVE] = true;
        [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_WEST_END_OF_HARBOUR] = true;
        [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_EASTERN_BRIDGE] = true;
        [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_SAND_IN_FRONT_OF_INN] = true;
        [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_END] = true;
    }

};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CHAIN_LOOKUP[MIDSUMMER] = {
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_BOTTLES] = "A_CURE_FOR_ALL_ILLS";
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_END] = "A_CURE_FOR_ALL_ILLS";
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_PICKUP] = "A_CURE_FOR_ALL_ILLS";
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_REVELLERS] = "A_CURE_FOR_ALL_ILLS";

    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_APPLES] = "AIDING_THE_STABLE_HANDS";
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_BRUSH] = "AIDING_THE_STABLE_HANDS";
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_END] = "AIDING_THE_STABLE_HANDS";
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_FEED] = "AIDING_THE_STABLE_HANDS";
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_GROOM] = "AIDING_THE_STABLE_HANDS";
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_PICKUP] = "AIDING_THE_STABLE_HANDS";

    [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_2] = "ARRANGING_ARRANGEMENTS";
    [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_END] = "ARRANGING_ARRANGEMENTS";
    [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_PICKUP] = "ARRANGING_ARRANGEMENTS";

    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_CIRIEL] = "ARTISTIC_DIRECTION";
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_END] = "ARTISTIC_DIRECTION";
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_LEBADAR] = "ARTISTIC_DIRECTION";
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_PICKUP] = "ARTISTIC_DIRECTION";
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_POTTER] = "ARTISTIC_DIRECTION";

    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_COLLECT] = "FLORAL_CROWNS";
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_CRAFT] = "FLORAL_CROWNS";
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_END] = "FLORAL_CROWNS";
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_PICKUP] = "FLORAL_CROWNS";

    [QG_MIDSUMMER_INDEX.GROWING_PAINS_END] = "GROWING_PAINS";
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_PICKUP] = "GROWING_PAINS";
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_WATER] = "GROWING_PAINS";
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_WEEDS] = "GROWING_PAINS";

    [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_COMPLETE] = "HONOURING_HEALERS";
    [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_END] = "HONOURING_HEALERS";
    [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_PICKUP] = "HONOURING_HEALERS";

    [QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_END] = "IN_CELEBRATION_OF_MIDSUMMER";
    [QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_PICKUP] = "IN_CELEBRATION_OF_MIDSUMMER";

    [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_COMPLETE] = "LOVE_IS_IN_THE_AIR";
    [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_END] = "LOVE_IS_IN_THE_AIR";
    [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_PICKUP] = "LOVE_IS_IN_THE_AIR";

    [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_COMPLETE] = "SOMETHING_FLORAL";
    [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_END] = "SOMETHING_FLORAL";
    [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_PICKUP] = "SOMETHING_FLORAL";

    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_COMPLETE] = "SOMETHING_MISPLACED";
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_DAENAR] = "SOMETHING_MISPLACED";
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_END] = "SOMETHING_MISPLACED";
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_FROKI] = "SOMETHING_MISPLACED";
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_GORD] = "SOMETHING_MISPLACED";
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_HOLLUR] = "SOMETHING_MISPLACED";
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_PICKUP] = "SOMETHING_MISPLACED";
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_POLLA] = "SOMETHING_MISPLACED";
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_ROBBO] = "SOMETHING_MISPLACED";

    [QG_MIDSUMMER_INDEX.SWEET_TREATS_2] = "SWEET_TREATS";
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_4] = "SWEET_TREATS";
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_END] = "SWEET_TREATS";
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_PICKUP] = "SWEET_TREATS";

    [QG_MIDSUMMER_INDEX.TASTY_MORSELS_COMPLETE] = "TASTY_MORSELS";
    [QG_MIDSUMMER_INDEX.TASTY_MORSELS_END] = "TASTY_MORSELS";
    [QG_MIDSUMMER_INDEX.TASTY_MORSELS_PICKUP] = "TASTY_MORSELS";

    [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_COMPLETE] = "TO_THE_LAST_DROP";
    [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_END] = "TO_THE_LAST_DROP";
    [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_PICKUP] = "TO_THE_LAST_DROP";

    [QG_MIDSUMMER_INDEX.TOSS_A_COIN_COMPLETE] = "TOSS_A_COIN";
    [QG_MIDSUMMER_INDEX.TOSS_A_COIN_END] = "TOSS_A_COIN";
    [QG_MIDSUMMER_INDEX.TOSS_A_COIN_PICKUP] = "TOSS_A_COIN";

    [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_CONTINUE] = "UNHELPFUL_HOUNDS";
    [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_END] = "UNHELPFUL_HOUNDS";
    [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_PICKUP] = "UNHELPFUL_HOUNDS";

    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_1] = "WEDDING_SUPPLIES";
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_3] = "WEDDING_SUPPLIES";
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_4] = "WEDDING_SUPPLIES";
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_5] = "WEDDING_SUPPLIES";
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_END] = "WEDDING_SUPPLIES";
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_PICKUP] = "WEDDING_SUPPLIES";

    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_1] = "WHAT_ALES_YOU";
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_2] = "WHAT_ALES_YOU";
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_3] = "WHAT_ALES_YOU";
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_4] = "WHAT_ALES_YOU";
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_END] = "WHAT_ALES_YOU";
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_PICKUP] = "WHAT_ALES_YOU";


    [QG_MIDSUMMER_INDEX.HOUSEKEEPING_PICKUP] = "HOUSEKEEPING";
    [QG_MIDSUMMER_INDEX.HOUSEKEEPING_BEDS] = "HOUSEKEEPING";
    [QG_MIDSUMMER_INDEX.HOUSEKEEPING_FLOORS] = "HOUSEKEEPING";
    [QG_MIDSUMMER_INDEX.HOUSEKEEPING_END] = "HOUSEKEEPING";

    [QG_MIDSUMMER_INDEX.TIDAL_TREASURES_PICKUP] = "TIDAL_TREASURES";
    [QG_MIDSUMMER_INDEX.TIDAL_TREASURES_SEASHELLS] = "TIDAL_TREASURES";
    [QG_MIDSUMMER_INDEX.TIDAL_TREASURES_END] = "TIDAL_TREASURES";

    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_PICKUP] = "ASSISTING_THE_COOK";
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_HERB_1] = "ASSISTING_THE_COOK";
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_HERB_2] = "ASSISTING_THE_COOK";
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_HERB_3] = "ASSISTING_THE_COOK";
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_HERB_4] = "ASSISTING_THE_COOK";
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_LEMON_1] = "ASSISTING_THE_COOK";
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_LEMON_2] = "ASSISTING_THE_COOK";
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_LEMON_3] = "ASSISTING_THE_COOK";
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_LEMON_4] = "ASSISTING_THE_COOK";
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_OLIVE_1] = "ASSISTING_THE_COOK";
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_OLIVE_2] = "ASSISTING_THE_COOK";
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_OLIVE_3] = "ASSISTING_THE_COOK";
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_OLIVE_4] = "ASSISTING_THE_COOK";
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_END] = "ASSISTING_THE_COOK";

    [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_PICKUP] = "BUILDING_CASTLES";
    [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_1] = "BUILDING_CASTLES";
    [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_2] = "BUILDING_CASTLES";
    [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_3] = "BUILDING_CASTLES";
    [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_4] = "BUILDING_CASTLES";
    [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_END] = "BUILDING_CASTLES";

    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_PICKUP] = "FISHING_FOR_ADVICE";
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_1_FOUND] = "FISHING_FOR_ADVICE";
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_1_CAUGHT] = "FISHING_FOR_ADVICE";
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_2_FOUND] = "FISHING_FOR_ADVICE";
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_2_CAUGHT] = "FISHING_FOR_ADVICE";
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_3_FOUND] = "FISHING_FOR_ADVICE";
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_3_CAUGHT] = "FISHING_FOR_ADVICE";
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_4_FOUND] = "FISHING_FOR_ADVICE";
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_4_CAUGHT] = "FISHING_FOR_ADVICE";
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_END] = "FISHING_FOR_ADVICE";

    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_PICKUP] = "OFFERING_TO_HELP";
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_BEACHGOER_1] = "OFFERING_TO_HELP";
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_BEACHGOER_2] = "OFFERING_TO_HELP";
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_BEACHGOER_3] = "OFFERING_TO_HELP";
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_HOLIDAYER_1] = "OFFERING_TO_HELP";
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_HOLIDAYER_2] = "OFFERING_TO_HELP";
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_HOLIDAYER_3] = "OFFERING_TO_HELP";
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SIGHTSEER_1] = "OFFERING_TO_HELP";
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SIGHTSEER_2] = "OFFERING_TO_HELP";
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SIGHTSEER_3] = "OFFERING_TO_HELP";
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SUITOR_1] = "OFFERING_TO_HELP";
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SUITOR_2] = "OFFERING_TO_HELP";
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SUITOR_3] = "OFFERING_TO_HELP";
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_MERRYMAKER_1] = "OFFERING_TO_HELP";
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_MERRYMAKER_2] = "OFFERING_TO_HELP";
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_MERRYMAKER_3] = "OFFERING_TO_HELP";
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_END] = "OFFERING_TO_HELP";

    [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_PICKUP] = "SEARCHING_FOR_SWIMMING_SPOTS";
    [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_WEST_HARBOR] = "SEARCHING_FOR_SWIMMING_SPOTS";
    [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_SOUTHERN_COVE] = "SEARCHING_FOR_SWIMMING_SPOTS";
    [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_NORTHERN_CHANNEL] = "SEARCHING_FOR_SWIMMING_SPOTS";
    [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_WESTERN_BEACH] = "SEARCHING_FOR_SWIMMING_SPOTS";
    [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_SOUTH_WESTERN_BEACH] = "SEARCHING_FOR_SWIMMING_SPOTS";
    [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_END] = "SEARCHING_FOR_SWIMMING_SPOTS";

    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_PICKUP] = "A_FLOCK_OF_SEAGULLS";
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_1] = "A_FLOCK_OF_SEAGULLS";
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_2] = "A_FLOCK_OF_SEAGULLS";
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_3] = "A_FLOCK_OF_SEAGULLS";
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_4] = "A_FLOCK_OF_SEAGULLS";
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_5] = "A_FLOCK_OF_SEAGULLS";
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_6] = "A_FLOCK_OF_SEAGULLS";
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_7] = "A_FLOCK_OF_SEAGULLS";
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_8] = "A_FLOCK_OF_SEAGULLS";
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_END] = "A_FLOCK_OF_SEAGULLS";

    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_PICKUP] = "CAT_CONUNDRUM";
    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_QUEST] = "CAT_CONUNDRUM";
    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SCRUFFY] = "CAT_CONUNDRUM";
    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SKINNY] = "CAT_CONUNDRUM";
    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SLINKY] = "CAT_CONUNDRUM";
    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SMELLY] = "CAT_CONUNDRUM";
    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SASSY] = "CAT_CONUNDRUM";
    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SLEEPY] = "CAT_CONUNDRUM";
    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_END] = "CAT_CONUNDRUM";

    [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_PICKUP] = "EYESORES_DRIFTED_ASHORE";
    [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_1] = "EYESORES_DRIFTED_ASHORE";
    [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_2] = "EYESORES_DRIFTED_ASHORE";
    [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_3] = "EYESORES_DRIFTED_ASHORE";
    [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_4] = "EYESORES_DRIFTED_ASHORE";
    [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_5] = "EYESORES_DRIFTED_ASHORE";
    [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_6] = "EYESORES_DRIFTED_ASHORE";
    [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_END] = "EYESORES_DRIFTED_ASHORE";

    [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_PICKUP] = "LETS_GO_FLY_A_KITE";
    [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_SOUTHERN_BEACH] = "LETS_GO_FLY_A_KITE";
    [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_SOUTHERN_COVE] = "LETS_GO_FLY_A_KITE";
    [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_WEST_END_OF_HARBOUR] = "LETS_GO_FLY_A_KITE";
    [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_EASTERN_BRIDGE] = "LETS_GO_FLY_A_KITE";
    [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_SAND_IN_FRONT_OF_INN] = "LETS_GO_FLY_A_KITE";
    [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_END] = "LETS_GO_FLY_A_KITE";

};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE[MIDSUMMER] = {
    [QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_PICKUP] = {
        ["CHAIN_BEGIN"] = "IN_CELEBRATION_OF_MIDSUMMER";
        ["TIMER_START"] = true;
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_PICKUP] = {
        ["CHAIN_BEGIN"] = "SOMETHING_FLORAL";
    };
    [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_PICKUP] = {
        ["CHAIN_BEGIN"] = "TO_THE_LAST_DROP";
    };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_PICKUP] = {
        ["CHAIN_BEGIN"] = "WEDDING_SUPPLIES";
    };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_PICKUP] = {
        ["CHAIN_BEGIN"] = "WHAT_ALES_YOU";
    };
    [QG_MIDSUMMER_INDEX.TASTY_MORSELS_PICKUP] = {
        ["CHAIN_BEGIN"] = "TASTY_MORSELS";
    };
    [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_PICKUP] = {
        ["CHAIN_BEGIN"] = "ARRANGING_ARRANGEMENTS";
    };
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_PICKUP] = {
        ["CHAIN_BEGIN"] = "FLORAL_CROWNS";
    };
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_PICKUP] = {
        ["CHAIN_BEGIN"] = "AIDING_THE_STABLE_HANDS";
    };
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_BRUSH] = {
    };
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_APPLES] = {
    };
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_GROOM] = {
    };
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_FEED] = {
    };
    [QG_MIDSUMMER_INDEX.AIDING_THE_STABLE_HANDS_END] = {
        ["LOAD_QUEST"] = "FLORAL_CROWNS";
        ["CHAIN_END"] = "AIDING_THE_STABLE_HANDS";
    };
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_COLLECT] = {
    };
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_CRAFT] = {
    };
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_PICKUP] = {
        ["LOAD_QUEST"] = "TOSS_A_COIN";
        ["CHAIN_BEGIN"] = "ARTISTIC_DIRECTION";
    };
    [QG_MIDSUMMER_INDEX.TOSS_A_COIN_PICKUP] = {
        ["CHAIN_BEGIN"] = "TOSS_A_COIN";
    };
    [QG_MIDSUMMER_INDEX.TOSS_A_COIN_COMPLETE] = {
    };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_1] = {
        ["LOAD_QUEST"] = "TO_THE_LAST_DROP";
    };
    [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_COMPLETE] = {
        ["LOAD_QUEST"] = "TOSS_A_COIN";
    };
    [QG_MIDSUMMER_INDEX.TOSS_A_COIN_END] = {
        ["LOAD_QUEST"] = "WHAT_ALES_YOU";
        ["CHAIN_END"] = "TOSS_A_COIN";
    };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_2] = {
        ["LOAD_QUEST"] = "ARTISTIC_DIRECTION";
    };
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_LEBADAR] = {
    };
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_PICKUP] = {
        ["CHAIN_BEGIN"] = "GROWING_PAINS";
    };
    [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_PICKUP] = {
        ["CHAIN_BEGIN"] = "UNHELPFUL_HOUNDS";
    };
    [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_CONTINUE] = {
    };
    [QG_MIDSUMMER_INDEX.UNHELPFUL_HOUNDS_END] = {
        ["LOAD_QUEST"] = "WEDDING_SUPPLIES";
        ["CHAIN_END"] = "UNHELPFUL_HOUNDS";
    };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_1] = {
        ["LOAD_QUEST"] = "ARTISTIC_DIRECTION";
    };
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_POTTER] = {
        ["LOAD_QUEST"] = "WEDDING_SUPPLIES";
    };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_3] = {
        ["LOAD_QUEST"] = "GROWING_PAINS";
    };
    [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_PICKUP] = {
        ["LOAD_QUEST"] = "GROWING_PAINS";
        ["CHAIN_BEGIN"] = "HONOURING_HEALERS";
    };
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_WATER] = {
    };
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_WEEDS] = {
    };
    [QG_MIDSUMMER_INDEX.GROWING_PAINS_END] = {
        ["LOAD_QUEST"] = "ARTISTIC_DIRECTION";
        ["CHAIN_END"] = "GROWING_PAINS";
    };
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_CIRIEL] = {
    };
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_PICKUP] = {
        ["CHAIN_BEGIN"] = "SWEET_TREATS";
    };
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_2] = {
        ["LOAD_QUEST"] = "WEDDING_SUPPLIES";
    };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_4] = {
    };
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_4] = {
        ["LOAD_QUEST"] = "ARRANGING_ARRANGEMENTS";
    };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_5] = {
        ["LOAD_QUEST"] = "SWEET_TREATS";
    };
    [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_2] = {
        ["LOAD_QUEST"] = "WHAT_ALES_YOU";
    };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_3] = {
        ["LOAD_QUEST"] = "SWEET_TREATS";
    };
    [QG_MIDSUMMER_INDEX.SWEET_TREATS_END] = {
        ["LOAD_QUEST"] = "ARTISTIC_DIRECTION";
        ["CHAIN_END"] = "SWEET_TREATS";
    };
    [QG_MIDSUMMER_INDEX.ARTISTIC_DIRECTION_END] = {
        ["LOAD_QUEST"] = "TASTY_MORSELS";
        ["CHAIN_END"] = "ARTISTIC_DIRECTION";
    };
    [QG_MIDSUMMER_INDEX.TASTY_MORSELS_COMPLETE] = {
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_PICKUP] = {
        ["CHAIN_BEGIN"] = "SOMETHING_MISPLACED";
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_HOLLUR] = {
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_POLLA] = {
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_FROKI] = {
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_DAENAR] = {
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_ROBBO] = {
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_GORD] = {
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_COMPLETE] = {
        ["LOAD_QUEST"] = "ARRANGING_ARRANGEMENTS";
        ["ALSO_COMPLETES"] = {
            [1] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_HOLLUR;
            [2] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_POLLA;
            [3] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_FROKI;
            [4] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_DAENAR;
            [5] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_ROBBO;
            [6] = QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_GORD;
        };
    };
    [QG_MIDSUMMER_INDEX.ARRANGING_ARRANGEMENTS_END] = {
        ["LOAD_QUEST"] = "A_CURE_FOR_ALL_ILLS";
        ["CHAIN_END"] = "ARRANGING_ARRANGEMENTS";
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_MISPLACED_END] = {
        ["LOAD_QUEST"] = "A_CURE_FOR_ALL_ILLS";
        ["CHAIN_END"] = "SOMETHING_MISPLACED";
    };
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_CURE_FOR_ALL_ILLS";
    };
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_BOTTLES] = {
    };
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_REVELLERS] = {
    };
    [QG_MIDSUMMER_INDEX.A_CURE_FOR_ALL_ILLS_END] = {
        ["LOAD_QUEST"] = "HONOURING_HEALERS";
        ["CHAIN_END"] = "A_CURE_FOR_ALL_ILLS";
    };
    [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_COMPLETE] = {
        ["LOAD_QUEST"] = "SOMETHING_FLORAL";
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_COMPLETE] = {
        ["LOAD_QUEST"] = "LOVE_IS_IN_THE_AIR";
    };
    [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_PICKUP] = {
        ["CHAIN_BEGIN"] = "LOVE_IS_IN_THE_AIR";
    };
    [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_COMPLETE] = {
    };
    [QG_MIDSUMMER_INDEX.LOVE_IS_IN_THE_AIR_END] = {
        ["LOAD_QUEST"] = "WHAT_ALES_YOU";
        ["CHAIN_END"] = "LOVE_IS_IN_THE_AIR";
    };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_4] = {
        ["LOAD_QUEST"] = "IN_CELEBRATION_OF_MIDSUMMER";
    };
    [QG_MIDSUMMER_INDEX.IN_CELEBRATION_OF_MIDSUMMER_END] = {
        ["LOAD_QUEST"] = "HONOURING_HEALERS";
        ["CHAIN_END"] = "IN_CELEBRATION_OF_MIDSUMMER";
    };
    [QG_MIDSUMMER_INDEX.HONOURING_HEALERS_END] = {
        ["LOAD_QUEST"] = "SOMETHING_FLORAL";
        ["CHAIN_END"] = "HONOURING_HEALERS";
    };
    [QG_MIDSUMMER_INDEX.SOMETHING_FLORAL_END] = {
        ["LOAD_QUEST"] = "TO_THE_LAST_DROP";
        ["CHAIN_END"] = "SOMETHING_FLORAL";
    };
    [QG_MIDSUMMER_INDEX.TO_THE_LAST_DROP_END] = {
        ["LOAD_QUEST"] = "WEDDING_SUPPLIES";
        ["CHAIN_END"] = "TO_THE_LAST_DROP";
    };
    [QG_MIDSUMMER_INDEX.WEDDING_SUPPLIES_END] = {
        ["LOAD_QUEST"] = "WHAT_ALES_YOU";
        ["CHAIN_END"] = "WEDDING_SUPPLIES";
    };
    [QG_MIDSUMMER_INDEX.WHAT_ALES_YOU_END] = {
        ["LOAD_QUEST"] = "TASTY_MORSELS";
        ["CHAIN_END"] = "WHAT_ALES_YOU";
    };
    [QG_MIDSUMMER_INDEX.TASTY_MORSELS_END] = {
        ["LOAD_QUEST"] = "FLORAL_CROWNS";
        ["CHAIN_END"] = "TASTY_MORSELS";
    };
    [QG_MIDSUMMER_INDEX.FLORAL_CROWNS_END] = {
        ["CHAIN_END"] = "FLORAL_CROWNS";
        ["TIMER_STOP"] = true;

    [QG_MIDSUMMER_INDEX.HOUSEKEEPING_PICKUP] = {
        ["CHAIN_BEGIN"] = "HOUSEKEEPING";
    };
    [QG_MIDSUMMER_INDEX.HOUSEKEEPING_BEDS] = {};
    [QG_MIDSUMMER_INDEX.HOUSEKEEPING_FLOORS] = {};
    [QG_MIDSUMMER_INDEX.TIDAL_TREASURES_PICKUP] = {
        ["CHAIN_BEGIN"] = "TIDAL_TREASURES";
    };
    [QG_MIDSUMMER_INDEX.TIDAL_TREASURES_SEASHELLS] = {};
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_PICKUP] = {
        ["CHAIN_BEGIN"] = "ASSISTING_THE_COOK";
    };
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_HERB_1] = {};
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_HERB_2] = {};
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_HERB_3] = {};
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_HERB_4] = {};
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_LEMON_1] = {};
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_LEMON_2] = {};
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_LEMON_3] = {};
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_LEMON_4] = {};
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_OLIVE_1] = {};
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_OLIVE_2] = {};
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_OLIVE_3] = {};
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_OLIVE_4] = {};
    [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_PICKUP] = {
        ["CHAIN_BEGIN"] = "BUILDING_CASTLES";
    };
    [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_1] = {};
    [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_2] = {};
    [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_3] = {};
    [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_4] = {};
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_PICKUP] = {
        ["CHAIN_BEGIN"] = "FISHING_FOR_ADVICE";
    };
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_1_FOUND] = {};
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_1_CAUGHT] = {};
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_2_FOUND] = {};
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_2_CAUGHT] = {};
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_3_FOUND] = {};
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_3_CAUGHT] = {};
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_4_FOUND] = {};
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_4_CAUGHT] = {};
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_PICKUP] = {
        ["CHAIN_BEGIN"] = "OFFERING_TO_HELP";
    };
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_BEACHGOER_1] = {};
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_BEACHGOER_2] = {};
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_BEACHGOER_3] = {};
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_HOLIDAYER_1] = {};
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_HOLIDAYER_2] = {};
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_HOLIDAYER_3] = {};
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SIGHTSEER_1] = {};
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SIGHTSEER_2] = {};
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SIGHTSEER_3] = {};
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SUITOR_1] = {};
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SUITOR_2] = {};
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_SUITOR_3] = {};
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_MERRYMAKER_1] = {};
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_MERRYMAKER_2] = {};
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_MERRYMAKER_3] = {};
    [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_PICKUP] = {
        ["CHAIN_BEGIN"] = "SEARCHING_FOR_SWIMMING_SPOTS";
    };
    [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_WEST_HARBOR] = {};
    [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_SOUTHERN_COVE] = {};
    [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_NORTHERN_CHANNEL] = {};
    [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_WESTERN_BEACH] = {};
    [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_SOUTH_WESTERN_BEACH] = {};
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_PICKUP] = 
    {
        ["CHAIN_BEGIN"] = "A_FLOCK_OF_SEAGULLS";
    };
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_1] = {};
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_2] = {};
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_3] = {};
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_4] = {};
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_5] = {};
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_6] = {};
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_7] = {};
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_8] = {};
    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_PICKUP] = 
    {
        ["CHAIN_BEGIN"] = "CAT_CONUNDRUM";
    };
    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_QUEST] = {};
    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SCRUFFY] = {};
    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SKINNY] = {};
    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SLINKY] = {};
    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SMELLY] = {};
    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SASSY] = {};
    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_SLEEPY] = {};
    [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_PICKUP] =
    {
        ["CHAIN_BEGIN"] = "EYESORES_DRIFTED_ASHORE";
    };
    [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_1] = {};
    [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_2] = {};
    [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_3] = {};
    [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_4] = {};
    [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_5] = {};
    [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_6] = {};
    [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_PICKUP] =
    {
        ["CHAIN_BEGIN"] = "LETS_GO_FLY_A_KITE";
    };
    [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_SOUTHERN_BEACH] = {};
    [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_SOUTHERN_COVE] = {};
    [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_WEST_END_OF_HARBOUR] = {};
    [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_EASTERN_BRIDGE] = {};
    [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_SAND_IN_FRONT_OF_INN] = {};
    [QG_MIDSUMMER_INDEX.HOUSEKEEPING_END] = {
        ["CHAIN_END"] = "HOUSEKEEPING";
    };
    [QG_MIDSUMMER_INDEX.TIDAL_TREASURES_END] = {
        ["CHAIN_END"] = "TIDAL_TREASURES";
    };
    [QG_MIDSUMMER_INDEX.ASSISTING_THE_COOK_END] = {
        ["CHAIN_END"] = "ASSISTING_THE_COOK";
    };
    [QG_MIDSUMMER_INDEX.BUILDING_CASTLES_END] = {
        ["CHAIN_END"] = "BUILDING_CASTLES";
    };
    [QG_MIDSUMMER_INDEX.FISHING_FOR_ADVICE_END] = {
        ["CHAIN_END"] = "FISHING_FOR_ADVICE";
    };
    [QG_MIDSUMMER_INDEX.OFFERING_TO_HELP_END] = {
        ["CHAIN_END"] = "OFFERING_TO_HELP";
    };
    [QG_MIDSUMMER_INDEX.SEARCHING_FOR_SWIMMING_SPOTS_END] = {
        ["CHAIN_END"] = "SEARCHING_FOR_SWIMMING_SPOTS";
    };
    [QG_MIDSUMMER_INDEX.A_FLOCK_OF_SEAGULLS_END] = {
        ["CHAIN_END"] = "A_FLOCK_OF_SEAGULLS";
    };
    [QG_MIDSUMMER_INDEX.CAT_CONUNDRUM_END] = {
        ["CHAIN_END"] = "CAT_CONUNDRUM";
    };
    [QG_MIDSUMMER_INDEX.EYESORES_DRIFTED_ASHORE_END] = {
        ["CHAIN_END"] = "EYESORES_DRIFTED_ASHORE";
    };
    [QG_MIDSUMMER_INDEX.LETS_GO_FLY_A_KITE_END] = {
        ["CHAIN_END"] = "LETS_GO_FLY_A_KITE";
    };

};

if (CLIENTLANG == "FRENCH") then
    import "CubePlugins.FestivalBuddyII.QuickGuides.Midsummer.QuickGuideStrings_MidsummerFR";
elseif (CLIENTLANG == "GERMAN") then
    import "CubePlugins.FestivalBuddyII.QuickGuides.Midsummer.QuickGuideStrings_MidsummerDE";
else
    import "CubePlugins.FestivalBuddyII.QuickGuides.Midsummer.QuickGuideStrings_MidsummerEN";
end