-- Farmers Faire Quest Indexes:

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_INDICIES[FARMERSFAIRE] = {};
_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_INDICIES[FARMERSFAIRE][DEFAULT_QUICK_GUIDE] = {};
QG_FARMERSFAIRE_INDEX = _G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_INDICIES[FARMERSFAIRE][DEFAULT_QUICK_GUIDE];

-- Move Parasol sooner
local i = 1;
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_SUNNY_FAIRE_DAY_PICKUP");

i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FROZEN_SWEET_CREAM_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FROZEN_SWEET_CREAM_COLLECT_CREAM");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FROZEN_SWEET_CREAM_COLLECT_FRUIT");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "BOUNDER_ROUNDS_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FAT_MAYOR_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "THE_GREAT_MATHOM_FISHING_SWAP_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "THE_GREAT_MATHOM_FISHING_SWAP_PROGRESS");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "MANNING_THE_MARKET_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "APPLE_SHOPPING_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "APPLE_SHOPPING_GREEN");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "APPLE_SHOPPING_RED");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "APPLE_SHOPPING_GOLDEN");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "APPLE_SHOPPING_END");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FRESH_SAVOURY_MUSHROOM_STEW_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FRESH_SAVOURY_MUSHROOM_STEW_FIND_RECIPE");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FRESH_SAVOURY_MUSHROOM_STEW_RECIPE");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FRESH_SAVOURY_MUSHROOM_STEW_FIND_BEEF");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FRESH_SAVOURY_MUSHROOM_STEW_BEEF");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FRESH_SAVOURY_MUSHROOM_STEW_FIND_SALT");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FRESH_SAVOURY_MUSHROOM_STEW_SALT");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FRESH_SAVOURY_MUSHROOM_STEW_FIND_WATER");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FRESH_SAVOURY_MUSHROOM_STEW_WATER");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FRESH_SAVOURY_MUSHROOM_STEW_FIND_CARROTS");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FRESH_SAVOURY_MUSHROOM_STEW_CARROTS");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FRESH_SAVOURY_MUSHROOM_STEW_FIND_BACON");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FRESH_SAVOURY_MUSHROOM_STEW_BACON");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FRESH_SAVOURY_MUSHROOM_STEW_FIND_MUSHROOMS");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FRESH_SAVOURY_MUSHROOM_STEW_MUSHROOMS");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FRESH_SAVOURY_MUSHROOM_STEW_COOK");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FRESH_SAVOURY_MUSHROOM_STEW_END");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_NOSEY_REQUEST_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FROZEN_SWEET_CREAM_COLLECT_HONEY");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_NOSEY_REQUEST_ERNWYD");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_NOSEY_REQUEST_OPALESSA");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_NOSEY_REQUEST_ALRIC");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_NOSEY_REQUEST_END");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_SHOPPING_LIST_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_SHOPPING_LIST_SMALL_HEAD_OF_CABBAGE");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_SHOPPING_LIST_GREEN_APPLE");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_SHOPPING_LIST_HAUNCH_OF_PORK");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_SHOPPING_LIST_LOAF_OF_WHITE_BREAD");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_SHOPPING_LIST_RED_ONION");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_SHOPPING_LIST_BLOCK_OF_MILD_CHEESE");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_SHOPPING_LIST_END");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "REVENGE_OF_THE_DRUNKARDS_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "REVENGE_OF_THE_DRUNKARDS_DRINK");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "REVENGE_OF_THE_DRUNKARDS_PROGRESS");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "REVENGE_OF_THE_DRUNKARDS_END");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_MARKET_LIST_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_MARKET_LIST_APPLE");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_MARKET_LIST_BREAD");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_MARKET_LIST_ONION");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_MARKET_LIST_CHEESE");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_MARKET_LIST_END");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_VENDOR_LIST_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_VENDOR_LIST_CABBAGE");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_VENDOR_LIST_MEAT");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_VENDOR_LIST_BREAD");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_VENDOR_LIST_ONION");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_VENDOR_LIST_CHEESE");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_VENDOR_LIST_END");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "BOUNDER_ROUNDS_PROGRESS");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "BOUNDER_ROUNDS_END");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FAT_MAYOR_PROGRESS");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FAT_MAYOR_END");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FROZEN_SWEET_CREAM_COLLECT_MIX");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FROZEN_SWEET_CREAM_END");

i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "COOLING_OFF_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "DEFEAT_THE_HEAT_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "COOLING_OFF_JUG");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "DEFEAT_THE_HEAT_PROGRESS");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "CRASH_LANDING_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FLYING_HIGH_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "GOING_HUNGRY_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "TOO_MUCH_FESTIVAL_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "TOO_MUCH_FESTIVAL_WINE");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "TOO_MUCH_FESTIVAL_TEAPOT");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "CRASH_LANDING_KITE_1");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "TOO_MUCH_FESTIVAL_BOOK");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "COOLING_OFF_1");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "CRASH_LANDING_KITE_2");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "TOO_MUCH_FESTIVAL_TWINE");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "COOLING_OFF_2");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "CRASH_LANDING_KITE_3");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "CRASH_LANDING_KITE_4");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "GOING_HUNGRY_CHEESE");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FLYING_HIGH_1");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "CRASH_LANDING_KITE_5");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "GOING_HUNGRY_PORRIDGE");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "CRASH_LANDING_KITE_6");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FLYING_HIGH_2");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "GOING_HUNGRY_MUSHROOMS");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FLYING_HIGH_3");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FLYING_HIGH_4");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "COOLING_OFF_3");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "TOO_MUCH_FESTIVAL_PARASOL");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "GOING_HUNGRY_EGG");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FLYING_HIGH_5");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "COOLING_OFF_4");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "GOING_HUNGRY_BREAD");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "COOLING_OFF_5");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "TOO_MUCH_FESTIVAL_END");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "GOING_HUNGRY_END");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "FLYING_HIGH_END");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "CRASH_LANDING_END");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "COOLING_OFF_END");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "DEFEAT_THE_HEAT_END");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "ICE_DELIVERY_PICKUP");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "ICE_DELIVERY_BLOCK");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "ICE_DELIVERY_DELIVER");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "ICE_DELIVERY_END");

i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "MANNING_THE_MARKET_END");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "THE_GREAT_MATHOM_FISHING_SWAP_END");
i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "A_SUNNY_FAIRE_DAY_END");

i = AddNextQuickguideValue(QG_FARMERSFAIRE_INDEX, i, "RESET");

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CHAINS[FARMERSFAIRE] = {};
_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CHAINS[FARMERSFAIRE][DEFAULT_QUICK_GUIDE] = {
    ["A_SUNNY_FAIRE_DAY"] = {
        [QG_FARMERSFAIRE_INDEX.A_SUNNY_FAIRE_DAY_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.A_SUNNY_FAIRE_DAY_END] = true;
    };

    ["GOING_HUNGRY"] = {
        [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_PORRIDGE] = true;
        [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_CHEESE] = true;
        [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_BREAD] = true;
        [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_EGG] = true;
        [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_MUSHROOMS] = true;
        [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_END] = true;
    };

    ["TOO_MUCH_FESTIVAL"] = {
        [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_TWINE] = true;
        [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_TEAPOT] = true;
        [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_WINE] = true;
        [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_PARASOL] = true;
        [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_BOOK] = true;
        [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_END] = true;
    };

    ["FLYING_HIGH"] = {
        [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_1] = true;
        [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_2] = true;
        [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_3] = true;
        [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_4] = true;
        [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_5] = true;
        [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_END] = true;
    };

    ["CRASH_LANDING"] = {
        [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_1] = true;
        [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_2] = true;
        [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_3] = true;
        [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_4] = true;
        [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_5] = true;
        [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_6] = true;
        [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_END] = true;
    };

    ["COOLING_OFF"] = {
        [QG_FARMERSFAIRE_INDEX.COOLING_OFF_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.COOLING_OFF_JUG] = true;
        [QG_FARMERSFAIRE_INDEX.COOLING_OFF_1] = true;
        [QG_FARMERSFAIRE_INDEX.COOLING_OFF_2] = true;
        [QG_FARMERSFAIRE_INDEX.COOLING_OFF_3] = true;
        [QG_FARMERSFAIRE_INDEX.COOLING_OFF_4] = true;
        [QG_FARMERSFAIRE_INDEX.COOLING_OFF_5] = true;
        [QG_FARMERSFAIRE_INDEX.COOLING_OFF_END] = true;
    };

    ["DEFEAT_THE_HEAT"] = {
        [QG_FARMERSFAIRE_INDEX.DEFEAT_THE_HEAT_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.DEFEAT_THE_HEAT_PROGRESS] = true;
        [QG_FARMERSFAIRE_INDEX.DEFEAT_THE_HEAT_END] = true;
    };

    ["ICE_DELIVERY"] = {
        [QG_FARMERSFAIRE_INDEX.ICE_DELIVERY_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.ICE_DELIVERY_BLOCK] = true;
        [QG_FARMERSFAIRE_INDEX.ICE_DELIVERY_DELIVER] = true;
        [QG_FARMERSFAIRE_INDEX.ICE_DELIVERY_END] = true;
    };

    ["BOUNDER_ROUNDS"] = {
        [QG_FARMERSFAIRE_INDEX.BOUNDER_ROUNDS_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.BOUNDER_ROUNDS_PROGRESS] = true;
        [QG_FARMERSFAIRE_INDEX.BOUNDER_ROUNDS_END] = true;
    };

    ["REVENGE_OF_THE_DRUNKARDS"] = {
        [QG_FARMERSFAIRE_INDEX.REVENGE_OF_THE_DRUNKARDS_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.REVENGE_OF_THE_DRUNKARDS_DRINK] = true;
        [QG_FARMERSFAIRE_INDEX.REVENGE_OF_THE_DRUNKARDS_PROGRESS] = true;
        [QG_FARMERSFAIRE_INDEX.REVENGE_OF_THE_DRUNKARDS_END] = true;
    };

    ["FAT_MAYOR"] = {
        [QG_FARMERSFAIRE_INDEX.FAT_MAYOR_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.FAT_MAYOR_PROGRESS] = true;
        [QG_FARMERSFAIRE_INDEX.FAT_MAYOR_END] = true;
    };

    ["FROZEN_SWEET_CREAM"] = {
        [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_COLLECT_CREAM] = true;
        [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_COLLECT_FRUIT] = true;
        [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_COLLECT_HONEY] = true;
        [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_COLLECT_MIX] = true;
        [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_END] = true;
    };

    ["MANNING_THE_MARKET"] = {
        [QG_FARMERSFAIRE_INDEX.MANNING_THE_MARKET_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.MANNING_THE_MARKET_END] = true;
    };

    ["A_MARKET_LIST"] = {
        [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_APPLE] = true;
        [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_BREAD] = true;
        [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_ONION] = true;
        [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_CHEESE] = true;
        [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_END] = true;
    };

    ["A_NOSEY_REQUEST"] = {
        [QG_FARMERSFAIRE_INDEX.A_NOSEY_REQUEST_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.A_NOSEY_REQUEST_ERNWYD] = true;
        [QG_FARMERSFAIRE_INDEX.A_NOSEY_REQUEST_OPALESSA] = true;
        [QG_FARMERSFAIRE_INDEX.A_NOSEY_REQUEST_ALRIC] = true;
        [QG_FARMERSFAIRE_INDEX.A_NOSEY_REQUEST_END] = true;
    };

    ["A_SHOPPING_LIST"] = {
        [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_RED_ONION] = true;
        [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_GREEN_APPLE] = true;
        [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_LOAF_OF_WHITE_BREAD] = true;
        [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_SMALL_HEAD_OF_CABBAGE] = true;
        [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_HAUNCH_OF_PORK] = true;
        [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_BLOCK_OF_MILD_CHEESE] = true;
        [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_END] = true;
    };

    ["A_VENDOR_LIST"] = {
        [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_CABBAGE] = true;
        [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_MEAT] = true;
        [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_BREAD] = true;
        [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_ONION] = true;
        [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_CHEESE] = true;
        [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_END] = true;
    };

    ["APPLE_SHOPPING"] = {
        [QG_FARMERSFAIRE_INDEX.APPLE_SHOPPING_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.APPLE_SHOPPING_GREEN] = true;
        [QG_FARMERSFAIRE_INDEX.APPLE_SHOPPING_RED] = true;
        [QG_FARMERSFAIRE_INDEX.APPLE_SHOPPING_GOLDEN] = true;
        [QG_FARMERSFAIRE_INDEX.APPLE_SHOPPING_END] = true;
    };

    ["FRESH_SAVOURY_MUSHROOM_STEW"] = {
        [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_RECIPE] = true;
        [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_RECIPE] = true;
        [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_BEEF] = true;
        [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_BEEF] = true;
        [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_SALT] = true;
        [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_SALT] = true;
        [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_WATER] = true;
        [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_WATER] = true;
        [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_CARROTS] = true;
        [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_CARROTS] = true;
        [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_BACON] = true;
        [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_BACON] = true;
        [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_MUSHROOMS] = true;
        [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_MUSHROOMS] = true;
        [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_COOK] = true;
        [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_END] = true;
    };

    ["THE_GREAT_MATHOM_FISHING_SWAP"] = {
        [QG_FARMERSFAIRE_INDEX.THE_GREAT_MATHOM_FISHING_SWAP_PICKUP] = true;
        [QG_FARMERSFAIRE_INDEX.THE_GREAT_MATHOM_FISHING_SWAP_PROGRESS] = true;
        [QG_FARMERSFAIRE_INDEX.THE_GREAT_MATHOM_FISHING_SWAP_END] = true;
    };
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CHAIN_LOOKUP[FARMERSFAIRE] = {};
_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE_CHAIN_LOOKUP[FARMERSFAIRE][DEFAULT_QUICK_GUIDE] = {
    [QG_FARMERSFAIRE_INDEX.A_SUNNY_FAIRE_DAY_PICKUP] = "A_SUNNY_FAIRE_DAY";
    [QG_FARMERSFAIRE_INDEX.A_SUNNY_FAIRE_DAY_END] = "A_SUNNY_FAIRE_DAY";

    [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_PICKUP] = "GOING_HUNGRY";
    [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_PORRIDGE] = "GOING_HUNGRY";
    [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_CHEESE] = "GOING_HUNGRY";
    [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_BREAD] = "GOING_HUNGRY";
    [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_EGG] = "GOING_HUNGRY";
    [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_MUSHROOMS] = "GOING_HUNGRY";
    [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_END] = "GOING_HUNGRY";

    [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_PICKUP] = "TOO_MUCH_FESTIVAL";
    [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_TWINE] = "TOO_MUCH_FESTIVAL";
    [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_TEAPOT] = "TOO_MUCH_FESTIVAL";
    [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_WINE] = "TOO_MUCH_FESTIVAL";
    [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_PARASOL] = "TOO_MUCH_FESTIVAL";
    [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_BOOK] = "TOO_MUCH_FESTIVAL";
    [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_END] = "TOO_MUCH_FESTIVAL";

    [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_PICKUP] = "FLYING_HIGH";
    [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_1] = "FLYING_HIGH";
    [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_2] = "FLYING_HIGH";
    [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_3] = "FLYING_HIGH";
    [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_4] = "FLYING_HIGH";
    [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_5] = "FLYING_HIGH";
    [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_END] = "FLYING_HIGH";

    [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_PICKUP] = "CRASH_LANDING";
    [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_1] = "CRASH_LANDING";
    [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_2] = "CRASH_LANDING";
    [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_3] = "CRASH_LANDING";
    [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_4] = "CRASH_LANDING";
    [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_5] = "CRASH_LANDING";
    [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_6] = "CRASH_LANDING";
    [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_END] = "CRASH_LANDING";

    [QG_FARMERSFAIRE_INDEX.COOLING_OFF_PICKUP] = "COOLING_OFF";
    [QG_FARMERSFAIRE_INDEX.COOLING_OFF_JUG] = "COOLING_OFF";
    [QG_FARMERSFAIRE_INDEX.COOLING_OFF_1] = "COOLING_OFF";
    [QG_FARMERSFAIRE_INDEX.COOLING_OFF_2] = "COOLING_OFF";
    [QG_FARMERSFAIRE_INDEX.COOLING_OFF_3] = "COOLING_OFF";
    [QG_FARMERSFAIRE_INDEX.COOLING_OFF_4] = "COOLING_OFF";
    [QG_FARMERSFAIRE_INDEX.COOLING_OFF_5] = "COOLING_OFF";
    [QG_FARMERSFAIRE_INDEX.COOLING_OFF_END] = "COOLING_OFF";

    [QG_FARMERSFAIRE_INDEX.DEFEAT_THE_HEAT_PICKUP] = "DEFEAT_THE_HEAT";
    [QG_FARMERSFAIRE_INDEX.DEFEAT_THE_HEAT_PROGRESS] = "DEFEAT_THE_HEAT";
    [QG_FARMERSFAIRE_INDEX.DEFEAT_THE_HEAT_END] = "DEFEAT_THE_HEAT";

    [QG_FARMERSFAIRE_INDEX.ICE_DELIVERY_PICKUP] = "ICE_DELIVERY";
    [QG_FARMERSFAIRE_INDEX.ICE_DELIVERY_BLOCK] = "ICE_DELIVERY";
    [QG_FARMERSFAIRE_INDEX.ICE_DELIVERY_DELIVER] = "ICE_DELIVERY";
    [QG_FARMERSFAIRE_INDEX.ICE_DELIVERY_END] = "ICE_DELIVERY";

    [QG_FARMERSFAIRE_INDEX.BOUNDER_ROUNDS_PICKUP] = "BOUNDER_ROUNDS";
    [QG_FARMERSFAIRE_INDEX.BOUNDER_ROUNDS_PROGRESS] = "BOUNDER_ROUNDS";
    [QG_FARMERSFAIRE_INDEX.BOUNDER_ROUNDS_END] = "BOUNDER_ROUNDS";

    [QG_FARMERSFAIRE_INDEX.REVENGE_OF_THE_DRUNKARDS_PICKUP] = "REVENGE_OF_THE_DRUNKARDS";
    [QG_FARMERSFAIRE_INDEX.REVENGE_OF_THE_DRUNKARDS_DRINK] = "REVENGE_OF_THE_DRUNKARDS";
    [QG_FARMERSFAIRE_INDEX.REVENGE_OF_THE_DRUNKARDS_PROGRESS] = "REVENGE_OF_THE_DRUNKARDS";
    [QG_FARMERSFAIRE_INDEX.REVENGE_OF_THE_DRUNKARDS_END] = "REVENGE_OF_THE_DRUNKARDS";

    [QG_FARMERSFAIRE_INDEX.FAT_MAYOR_PICKUP] = "FAT_MAYOR";
    [QG_FARMERSFAIRE_INDEX.FAT_MAYOR_PROGRESS] = "FAT_MAYOR";
    [QG_FARMERSFAIRE_INDEX.FAT_MAYOR_END] = "FAT_MAYOR";

    [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_PICKUP] = "FROZEN_SWEET_CREAM";
    [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_COLLECT_CREAM] = "FROZEN_SWEET_CREAM";
    [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_COLLECT_FRUIT] = "FROZEN_SWEET_CREAM";
    [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_COLLECT_HONEY] = "FROZEN_SWEET_CREAM";
    [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_COLLECT_MIX] = "FROZEN_SWEET_CREAM";
    [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_END] = "FROZEN_SWEET_CREAM";

    [QG_FARMERSFAIRE_INDEX.MANNING_THE_MARKET_PICKUP] = "MANNING_THE_MARKET";
    [QG_FARMERSFAIRE_INDEX.MANNING_THE_MARKET_END] = "MANNING_THE_MARKET";

    [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_PICKUP] = "A_MARKET_LIST";
    [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_APPLE] = "A_MARKET_LIST";
    [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_BREAD] = "A_MARKET_LIST";
    [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_ONION] = "A_MARKET_LIST";
    [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_CHEESE] = "A_MARKET_LIST";
    [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_END] = "A_MARKET_LIST";

    [QG_FARMERSFAIRE_INDEX.A_NOSEY_REQUEST_PICKUP] = "A_NOSEY_REQUEST";
    [QG_FARMERSFAIRE_INDEX.A_NOSEY_REQUEST_ERNWYD] = "A_NOSEY_REQUEST";
    [QG_FARMERSFAIRE_INDEX.A_NOSEY_REQUEST_OPALESSA] = "A_NOSEY_REQUEST";
    [QG_FARMERSFAIRE_INDEX.A_NOSEY_REQUEST_ALRIC] = "A_NOSEY_REQUEST";
    [QG_FARMERSFAIRE_INDEX.A_NOSEY_REQUEST_END] = "A_NOSEY_REQUEST";

    [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_PICKUP] = "A_SHOPPING_LIST";
    [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_RED_ONION] = "A_SHOPPING_LIST";
    [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_GREEN_APPLE] = "A_SHOPPING_LIST";
    [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_LOAF_OF_WHITE_BREAD] = "A_SHOPPING_LIST";
    [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_SMALL_HEAD_OF_CABBAGE] = "A_SHOPPING_LIST";
    [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_HAUNCH_OF_PORK] = "A_SHOPPING_LIST";
    [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_BLOCK_OF_MILD_CHEESE] = "A_SHOPPING_LIST";
    [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_END] = "A_SHOPPING_LIST";

    [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_PICKUP] = "A_VENDOR_LIST";
    [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_CABBAGE] = "A_VENDOR_LIST";
    [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_MEAT] = "A_VENDOR_LIST";
    [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_BREAD] = "A_VENDOR_LIST";
    [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_ONION] = "A_VENDOR_LIST";
    [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_CHEESE] = "A_VENDOR_LIST";
    [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_END] = "A_VENDOR_LIST";

    [QG_FARMERSFAIRE_INDEX.APPLE_SHOPPING_PICKUP] = "APPLE_SHOPPING";
    [QG_FARMERSFAIRE_INDEX.APPLE_SHOPPING_GREEN] = "APPLE_SHOPPING";
    [QG_FARMERSFAIRE_INDEX.APPLE_SHOPPING_RED] = "APPLE_SHOPPING";
    [QG_FARMERSFAIRE_INDEX.APPLE_SHOPPING_GOLDEN] = "APPLE_SHOPPING";
    [QG_FARMERSFAIRE_INDEX.APPLE_SHOPPING_END] = "APPLE_SHOPPING";

    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_PICKUP] = "FRESH_SAVOURY_MUSHROOM_STEW";
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_RECIPE] = "FRESH_SAVOURY_MUSHROOM_STEW";
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_RECIPE] = "FRESH_SAVOURY_MUSHROOM_STEW";
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_BEEF] = "FRESH_SAVOURY_MUSHROOM_STEW";
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_BEEF] = "FRESH_SAVOURY_MUSHROOM_STEW";
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_SALT] = "FRESH_SAVOURY_MUSHROOM_STEW";
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_SALT] = "FRESH_SAVOURY_MUSHROOM_STEW";
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_WATER] = "FRESH_SAVOURY_MUSHROOM_STEW";
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_WATER] = "FRESH_SAVOURY_MUSHROOM_STEW";
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_CARROTS] = "FRESH_SAVOURY_MUSHROOM_STEW";
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_CARROTS] = "FRESH_SAVOURY_MUSHROOM_STEW";
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_BACON] = "FRESH_SAVOURY_MUSHROOM_STEW";
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_BACON] = "FRESH_SAVOURY_MUSHROOM_STEW";
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_MUSHROOMS] = "FRESH_SAVOURY_MUSHROOM_STEW";
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_MUSHROOMS] = "FRESH_SAVOURY_MUSHROOM_STEW";
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_COOK] = "FRESH_SAVOURY_MUSHROOM_STEW";
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_END] = "FRESH_SAVOURY_MUSHROOM_STEW";

    [QG_FARMERSFAIRE_INDEX.THE_GREAT_MATHOM_FISHING_SWAP_PICKUP] = "THE_GREAT_MATHOM_FISHING_SWAP";
    [QG_FARMERSFAIRE_INDEX.THE_GREAT_MATHOM_FISHING_SWAP_PROGRESS] = "THE_GREAT_MATHOM_FISHING_SWAP";
    [QG_FARMERSFAIRE_INDEX.THE_GREAT_MATHOM_FISHING_SWAP_END] = "THE_GREAT_MATHOM_FISHING_SWAP";
};

_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE[FARMERSFAIRE] = {};
_G.CubePlugins.FestivalBuddyII._QUICK_GUIDE[FARMERSFAIRE][DEFAULT_QUICK_GUIDE] = {
    [QG_FARMERSFAIRE_INDEX.A_SUNNY_FAIRE_DAY_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_SUNNY_FAIRE_DAY";
        ["TIMER_START"] = true;
    };
    [QG_FARMERSFAIRE_INDEX.A_SUNNY_FAIRE_DAY_END] = {
        ["CHAIN_END"] = "A_SUNNY_FAIRE_DAY";
        ["TIMER_STOP"] = true;
    };

    [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_PICKUP] = {
        ["CHAIN_BEGIN"] = "GOING_HUNGRY";
    };
    [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_PORRIDGE] = {};
    [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_CHEESE] = {};
    [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_BREAD] = {};
    [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_EGG] = {};
    [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_MUSHROOMS] = {};
    [QG_FARMERSFAIRE_INDEX.GOING_HUNGRY_END] = {
        ["CHAIN_END"] = "GOING_HUNGRY";
    };

    [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_PICKUP] = {
        ["CHAIN_BEGIN"] = "TOO_MUCH_FESTIVAL";
    };
    [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_TWINE] = {};
    [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_TEAPOT] = {};
    [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_WINE] = {};
    [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_PARASOL] = {};
    [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_BOOK] = {};
    [QG_FARMERSFAIRE_INDEX.TOO_MUCH_FESTIVAL_END] = {
        ["CHAIN_END"] = "TOO_MUCH_FESTIVAL";
    };

    [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_PICKUP] = {
        ["CHAIN_BEGIN"] = "FLYING_HIGH";
    };
    [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_1] = {};
    [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_2] = {};
    [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_3] = {};
    [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_4] = {};
    [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_5] = {};
    [QG_FARMERSFAIRE_INDEX.FLYING_HIGH_END] = {
        ["CHAIN_END"] = "FLYING_HIGH";
    };

    [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_PICKUP] = {
        ["CHAIN_BEGIN"] = "CRASH_LANDING";
    };
    [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_1] = {};
    [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_2] = {};
    [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_3] = {};
    [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_4] = {};
    [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_5] = {};
    [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_KITE_6] = {};
    [QG_FARMERSFAIRE_INDEX.CRASH_LANDING_END] = {
        ["CHAIN_END"] = "CRASH_LANDING";
    };

    [QG_FARMERSFAIRE_INDEX.COOLING_OFF_PICKUP] = {
        ["CHAIN_BEGIN"] = "COOLING_OFF";
    };
    [QG_FARMERSFAIRE_INDEX.COOLING_OFF_JUG] = {};
    [QG_FARMERSFAIRE_INDEX.COOLING_OFF_1] = {};
    [QG_FARMERSFAIRE_INDEX.COOLING_OFF_2] = {};
    [QG_FARMERSFAIRE_INDEX.COOLING_OFF_3] = {};
    [QG_FARMERSFAIRE_INDEX.COOLING_OFF_4] = {};
    [QG_FARMERSFAIRE_INDEX.COOLING_OFF_5] = {};
    [QG_FARMERSFAIRE_INDEX.COOLING_OFF_END] = {
        ["CHAIN_END"] = "COOLING_OFF";
    };

    [QG_FARMERSFAIRE_INDEX.DEFEAT_THE_HEAT_PICKUP] = {
        ["CHAIN_BEGIN"] = "DEFEAT_THE_HEAT";
    };
    [QG_FARMERSFAIRE_INDEX.DEFEAT_THE_HEAT_PROGRESS] = {};
    [QG_FARMERSFAIRE_INDEX.DEFEAT_THE_HEAT_END] = {
        ["CHAIN_END"] = "DEFEAT_THE_HEAT";
    };

    [QG_FARMERSFAIRE_INDEX.ICE_DELIVERY_PICKUP] = {
        ["CHAIN_BEGIN"] = "ICE_DELIVERY";
    };
    [QG_FARMERSFAIRE_INDEX.ICE_DELIVERY_BLOCK] = {};
    [QG_FARMERSFAIRE_INDEX.ICE_DELIVERY_DELIVER] = {};
    [QG_FARMERSFAIRE_INDEX.ICE_DELIVERY_END] = {
        ["CHAIN_END"] = "ICE_DELIVERY";
    };

    [QG_FARMERSFAIRE_INDEX.BOUNDER_ROUNDS_PICKUP] = {
        ["CHAIN_BEGIN"] = "BOUNDER_ROUNDS";
    };
    [QG_FARMERSFAIRE_INDEX.BOUNDER_ROUNDS_PROGRESS] = {};
    [QG_FARMERSFAIRE_INDEX.BOUNDER_ROUNDS_END] = {
        ["CHAIN_END"] = "BOUNDER_ROUNDS";
    };

    [QG_FARMERSFAIRE_INDEX.REVENGE_OF_THE_DRUNKARDS_PICKUP] = {
        ["CHAIN_BEGIN"] = "REVENGE_OF_THE_DRUNKARDS";
    };
    [QG_FARMERSFAIRE_INDEX.REVENGE_OF_THE_DRUNKARDS_DRINK] = {};
    [QG_FARMERSFAIRE_INDEX.REVENGE_OF_THE_DRUNKARDS_PROGRESS] = {};
    [QG_FARMERSFAIRE_INDEX.REVENGE_OF_THE_DRUNKARDS_END] = {
        ["CHAIN_END"] = "REVENGE_OF_THE_DRUNKARDS";
    };

    [QG_FARMERSFAIRE_INDEX.FAT_MAYOR_PICKUP] = {
        ["CHAIN_BEGIN"] = "FAT_MAYOR";
    };
    [QG_FARMERSFAIRE_INDEX.FAT_MAYOR_PROGRESS] = {};
    [QG_FARMERSFAIRE_INDEX.FAT_MAYOR_END] = {
        ["CHAIN_END"] = "FAT_MAYOR";
    };

    [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_PICKUP] = {
        ["CHAIN_BEGIN"] = "FROZEN_SWEET_CREAM";
    };
    [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_COLLECT_CREAM] = {};
    [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_COLLECT_FRUIT] = {};
    [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_COLLECT_HONEY] = {};
    [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_COLLECT_MIX] = {};
    [QG_FARMERSFAIRE_INDEX.FROZEN_SWEET_CREAM_END] = {
        ["CHAIN_END"] = "FROZEN_SWEET_CREAM";
    };

    [QG_FARMERSFAIRE_INDEX.MANNING_THE_MARKET_PICKUP] = {
        ["CHAIN_BEGIN"] = "MANNING_THE_MARKET";
    };
    [QG_FARMERSFAIRE_INDEX.MANNING_THE_MARKET_END] = {
        ["CHAIN_END"] = "MANNING_THE_MARKET";
    };

    [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_MARKET_LIST";
    };
    [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_APPLE] = {};
    [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_BREAD] = {};
    [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_ONION] = {};
    [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_CHEESE] = {};
    [QG_FARMERSFAIRE_INDEX.A_MARKET_LIST_END] = {
        ["CHAIN_END"] = "A_MARKET_LIST";
    };

    [QG_FARMERSFAIRE_INDEX.A_NOSEY_REQUEST_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_NOSEY_REQUEST";
    };
    [QG_FARMERSFAIRE_INDEX.A_NOSEY_REQUEST_ERNWYD] = {};
    [QG_FARMERSFAIRE_INDEX.A_NOSEY_REQUEST_OPALESSA] = {};
    [QG_FARMERSFAIRE_INDEX.A_NOSEY_REQUEST_ALRIC] = {};
    [QG_FARMERSFAIRE_INDEX.A_NOSEY_REQUEST_END] = {
        ["CHAIN_END"] = "A_NOSEY_REQUEST";
    };

    [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_SHOPPING_LIST";
    };
    [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_RED_ONION] = {};
    [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_GREEN_APPLE] = {};
    [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_LOAF_OF_WHITE_BREAD] = {};
    [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_SMALL_HEAD_OF_CABBAGE] = {};
    [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_HAUNCH_OF_PORK] = {};
    [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_BLOCK_OF_MILD_CHEESE] = {};
    [QG_FARMERSFAIRE_INDEX.A_SHOPPING_LIST_END] = {
        ["CHAIN_END"] = "A_SHOPPING_LIST";
    };

    [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_PICKUP] = {
        ["CHAIN_BEGIN"] = "A_VENDOR_LIST";
    };
    [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_CABBAGE] = {};
    [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_MEAT] = {};
    [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_BREAD] = {};
    [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_ONION] = {};
    [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_CHEESE] = {};
    [QG_FARMERSFAIRE_INDEX.A_VENDOR_LIST_END] = {
        ["CHAIN_END"] = "A_VENDOR_LIST";
    };

    [QG_FARMERSFAIRE_INDEX.APPLE_SHOPPING_PICKUP] = {
        ["CHAIN_BEGIN"] = "APPLE_SHOPPING";
    };
    [QG_FARMERSFAIRE_INDEX.APPLE_SHOPPING_GREEN] = {};
    [QG_FARMERSFAIRE_INDEX.APPLE_SHOPPING_RED] = {};
    [QG_FARMERSFAIRE_INDEX.APPLE_SHOPPING_GOLDEN] = {};
    [QG_FARMERSFAIRE_INDEX.APPLE_SHOPPING_END] = {
        ["CHAIN_END"] = "APPLE_SHOPPING";
    };

    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_PICKUP] = {
        ["CHAIN_BEGIN"] = "FRESH_SAVOURY_MUSHROOM_STEW";
    };
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_RECIPE] = {};
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_RECIPE] = {};
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_BEEF] = {};
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_BEEF] = {};
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_SALT] = {};
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_SALT] = {};
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_WATER] = {};
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_WATER] = {};
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_CARROTS] = {};
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_CARROTS] = {};
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_BACON] = {};
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_BACON] = {};
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_FIND_MUSHROOMS] = {};
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_MUSHROOMS] = {};
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_COOK] = {};
    [QG_FARMERSFAIRE_INDEX.FRESH_SAVOURY_MUSHROOM_STEW_END] = {
        ["CHAIN_END"] = "FRESH_SAVOURY_MUSHROOM_STEW";
    };

    [QG_FARMERSFAIRE_INDEX.THE_GREAT_MATHOM_FISHING_SWAP_PICKUP] = {
        ["CHAIN_BEGIN"] = "THE_GREAT_MATHOM_FISHING_SWAP";
    };
    [QG_FARMERSFAIRE_INDEX.THE_GREAT_MATHOM_FISHING_SWAP_PROGRESS] = {};
    [QG_FARMERSFAIRE_INDEX.THE_GREAT_MATHOM_FISHING_SWAP_END] = {
        ["CHAIN_END"] = "THE_GREAT_MATHOM_FISHING_SWAP";
    };
};

if (CLIENTLANG == "FRENCH") then
    import "CubePlugins.FestivalBuddyII.QuickGuides.FarmersFaire.QuickGuideStrings_FarmersFaireFR";
elseif (CLIENTLANG == "GERMAN") then
    import "CubePlugins.FestivalBuddyII.QuickGuides.FarmersFaire.QuickGuideStrings_FarmersFaireDE";
else
    import "CubePlugins.FestivalBuddyII.QuickGuides.FarmersFaire.QuickGuideStrings_FarmersFaireEN";
end